mozsearch/mozsearch

- router/router.py
Not tested locally, but this should work if I understood the code.
> Apply path filter to symbol/id searches

- tools/src/tokenize.rs
This is a first draft to add C++ raw literals to the tokenizer. I couldn't get the test setup working, so I added some rust-style tests to the tokenizer module. I ran them via `cargo test`. I wasn't sure how much syntax checking I should be doing here, so this corresponds very closely to [this reference](http://en.cppreference.com/w/cpp/language/string_literal). If needed, I could pare this down to assume that someone else checked for correctness if that would be preferable.
Do I need to add a test for this in `LanguageSpec`? Also, any simplifications would be appreciated. I'm especially not terribly happy with how this plugs into the main if/else structure.
Thanks.
> Add C++ raw literals to the tokenizer

- tools/src/tokenize.rs
This is a little clunky, but it seems to work. With this, we don't have to try to scan ahead looking for the end of the template string and we properly tokenize regexps and strings as to not be confused by them. This also handles nested functions or object literals that could also have caused confusion with the original code.
> Make nested template strings in JS work

- scripts/nginx-setup.py
Need to test this on dev before merging
> Forward to https if coming in from http on X-Forwarded-Proto

- tools/src/bin/ipdl-analyze.rs
The indexer is currently failing in the IPDL analysis step due to
failing to find a symbol. I'm not sure why that is not working, so
instead this patch makes it so that we don't output anything in that
case. We've lived this long without IPDL indexing working correctly.
> Make failures in find_analysis non-fatal.

- tools/src/bin/output-file.rs
This is a nice feature that DXR has. It exposes an item in the navigation panel to quickly switch between .h and .cpp files.
> Add link to switch between .h and .cpp files

- clang-plugin/MozsearchIndexer.cpp
This change was made in m-c but should be made in this repo as well to keep the two in sync.
> Copy over change from bug 1418434 to mozsearch repo

- tools/src/blame.rs
- tools/src/format.rs
- tools/src/lib.rs
- tools/src/links.rs
Just a refactoring, no functional changes.
> Bug 1418072 - Move linkification code into its own module

- clang-plugin/MozsearchIndexer.cpp
This is either the dumbest API, or the worst documented API. Or both.
> Fix visiting of constructor expressions

- infrastructure/web-server-run.sh
- tools/Cargo.toml
Not sure how much this will actually help in practice but it would have helped a little bit with diagnosing the web-server panic today.
> Build rust code with debug info and run with backtrace dumping

- tools/src/bin/rust-indexer.rs
This shows "Go to definition of function foo" instead of
"Go to definition of foo", and similar changes in other parts of the UI.
> rust-indexer: Prettify definitions.

- static/css/mozsearch.css
Followup to #84 to fix the regression bz reported
> Bug 1434816 - Apply the max-height to line number rows as well

- static/js/context-menu.js
I basically stole this straight from dxr's context-menu.js. Seems to work pretty well.
> Bug 1426249 - Add substring search option when clicking on code.

- scripts/rust-analyze.sh
- tools/src/bin/rust-indexer.rs
Found these while working on the taskcluster integration
> Couple of rust-indexing tweaks

- infrastructure/aws/ssh.py
> Make ssh.py compatible with python3

- infrastructure/aws/index.sh
- infrastructure/aws/main.sh
- infrastructure/aws/send-done-email.py
- infrastructure/aws/send-failure-email.py
I kicked off a dev run to test this, will only merge if that's successful.
> Bug 1416806 - Indicate channel and branch on searchfox completion emails

- router/codesearch.py
Based on server logs, we can get exceptions thrown while searching for a number of
different reasons, including e.g. bad regex queries. In all of these cases we
were attempting to start a new instance of the server, which is wrong - we only
want to do it if we got a connection error indicating the server died. In the other
cases we just return an empty result for now, but in the future we should do a
better job of reporting some error message details back to the user.
> Bug 1483933 - Don't start a new instance of livegrep so eagerly

- docs/analysis.md
- scripts/merge-analyses.py
This script can be used to merge analysis files from different
platforms; it will union the symbols for source lines.
> Bug 1490521 - Add script to better merge analysis files.

- README.md
- docs/analysis.md
- docs/aws.md
Did a pass over the documentation and fleshed out some things. I couldn't figure out what the peekRange stuff in the analysis files was for, does anybody know? As far as I can tell it is not used anywhere.
> Bug 1492322 - Update documentation

- static/css/icons.css
This PR changes the styling of the <kbd> elements in the sidebar to be a little less aggressive. The new styling is inspired by the one used on github.
> Change accelerator indicator styling

- docs/aws.md
- infrastructure/indexer-provision.sh
Also fix docs for provisioning.
> Add dos2unix to the indexer

- scripts/mkdirs.sh
- scripts/objdir-mkdirs.sh
- scripts/output-dir.js
- scripts/output.js
- static/css/mozsearch.css
- tests/tests/files/bug1432300.cpp
- tests/tests/files/bug1435345.cpp
- tests/tests/files/simple.rs
- tests/tests/files/some_python.py
- tools/Cargo.lock
- tools/Cargo.toml
- tools/src/bin/output-file.rs
- tools/src/describe.rs
- tools/src/lib.rs
- tools/src/links.rs
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1453327
Currently deployed to https://kats.searchfox.org/ if you want to try it out - see https://kats.searchfox.org/mozilla-central/source/mfbt or https://kats.searchfox.org/mozilla-central/source/gfx/layers/apz/test/mochitest for particularly nice examples
> Add file descriptions to directory listings

- tools/src/bin/output-file.rs
Depends on https://github.com/mozsearch/mozsearch-mozilla/pull/27
> Add links to file bugs

- Makefile
We might want something fancier later but for now this is better than nothing
> Add a Makefile to make it easer to run commonly-run commands

- tools/src/bin/rust-indexer.rs
This is a follow-up to #182 since I realized I did the comma-sanitization for the context menu items as well (which are derived from the `AnalysisSource::pretty` field). So this patch preserves the sanitization for all the uses of the mangled symbol except for that one.
Also I extracted the code to construct the qualified name and reused it for the `trait_dependent_name` construction since I was touching the code anyway.
> Bug 1512044 - Allow the source-analysis pretty name to have commas

- static/css/mozsearch.css
- static/js/blame.js
- static/js/dxr.js
- tools/src/format.rs
This just implements the suggestions from the indicated bugs.
> accessibility fixes

- clang-plugin/MozsearchIndexer.cpp
Change was reviewed in bugzilla
> Re-sync MozsearchIndexer.cpp after changes in bug 1523082

- infrastructure/indexer-provision.sh
- infrastructure/web-server-provision.sh
- router/codesearch.py
- scripts/build-codesearch.py
- tests/find-repo-files.py
> Add support for text search in submodules

- tools/src/tokenize.rs
If an .rs file had a `r#` sequence with no `"` characters following it,
the tokenizer would run off the end of the file and panic. This can
happen in valid rust files thanks to the magic of macros.
> Bug 1544046 - Prevent tokenizer crash.

- tools/src/languages.rs
I tested that this compiles locally.
> Bug 1549611 - Update reserved words list for XPIDL and IPDL files.

- scripts/rust-analyze.sh
- tools/src/bin/rust-indexer.rs
Rebased version of #123. Depends on https://github.com/mozsearch/mozsearch-mozilla/pull/40 which downloads the src and analysis data from taskcluster.
> Index rust stdlib source

- infrastructure/aws/ssh.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1552299
> Bug 1552299 - Show age of instance in infrastructure/aws/ssh.py listing. r=kats

- static/js/code-highlighter.js
Patch also actually by :kats :)
> Bug 1511275 - bustage fix for scrolling to anchored lines at startup. r=kats

- static/css/mozsearch.css
:heycam's proposal with CSS variables.
> Bug 1557139 - :heycam proposes a less blue solution. r=kats

- clang-plugin/MozsearchIndexer.cpp
The corresponding phabricator review is up at https://phabricator.services.mozilla.com/D44755 and I had to claim emilio was the reviewer because moz-phab wouldn't let me submit with made-up reviewers or myself.
The try push for phabricator was https://treeherder.mozilla.org/#/jobs?repo=try&revision=7e464b889edbd73eec4f7c74ab03048254ee459e
I'll trigger a just mozilla-central run on asuth.searchfox.org now.
> Bug 1511025 - correct template traversal. r=kats

- infrastructure/aws/scp-while-sshed.py
I now see I also left some comments out-of-date.  I'm fine to iterate on this, I just want to avoid letting this bit-rot or me duplicating this command from my laptop.
> Bug 1579882 - Add a very basic scp command to copy from the server to the local machine. r=kats

- scripts/nginx-setup.py
- tools/src/languages.rs
Some tests and Android products have webp files.
> Bug 1585501 - webp should be recognized as binary.

- tools/src/bin/crossref.rs
- tools/src/bin/ipdl-analyze.rs
- tools/src/bin/merge-analyses.rs
- tools/src/bin/output-file.rs
- tools/src/bin/rust-indexer.rs
- tools/src/bin/web-server.rs
- tools/src/blame.rs
- tools/src/config.rs
- tools/src/describe.rs
- tools/src/file_format/analysis.rs
- tools/src/file_format/identifiers.rs
- tools/src/format.rs
- tools/src/git_ops.rs
- tools/src/languages.rs
- tools/src/lib.rs
- tools/src/links.rs
- tools/src/output.rs
- tools/src/tokenize.rs
See each individual commit for details.
> A bunch of mostly-automated cleanups to the rust code.

- infrastructure/aws/web-serve.sh
- infrastructure/web-server-setup.sh
- scripts/nginx-setup.py
> Bug 1593372 - Add proxy_cache and proxy_cache_path settings to searchfox nginx to cache dynamic content.

- README.md
Hopefully no one uses this command in a trial-and-error process on metered data...
> Bug 1595492 - Update mapper usage docs. r=kats

- tests/tests/files/templates_nsTArray.cpp
Emilio, this is the test-case you authored in https://bugzilla.mozilla.org/show_bug.cgi?id=1511025#c17 that I had in my graph-support branch that the template fixes from that bug came from.  But I forgot to include this in the landing!
I feel weird just landing this, so you get to review your reduction here that I've already technically reviewed!  Thanks! ;)
> Bug 1511025 - reduced template testcase. r=asuth

- tools/src/languages.rs
Regular statics work for this.
> Use less lazy_static in languages.rs

- static/css/mozsearch.css
- static/js/code-highlighter.js
- static/js/dxr.js
This is the part of my work for https://bugzilla.mozilla.org/show_bug.cgi?id=1561900 which is worth landing, I think.
> Rename scrollIntoView -> createSyntheticAnchor.

- README.md
This is the result of repeated testing of vagrant provisioning on Ubuntu 19.10 and OS X 10.14.6.
I'm setting this up as a pull request to hopefully make it easier to provide feedback on the changes, but I think it's also okay for people to just directly tweak the docs wiki-style if there's a clear improvement.  (I've done this a few times on this doc previously when the changes seemed clear-cut.  These are larger and more substantial changes that I think review would normally be appropriate for, but because of time pressure factors related to the all-hands and the time in Berlin and Toronto,  I'm just going to land this immediately.)
cc'ing @staktrace @emilio
> Improve vagrant setup documentation

- static/js/blame.js
- static/js/context-menu.js
- static/templates/context-menu.html
This is not for perf, just to try to make it saner.
> No bug - Rewrite the context menu code.

- .eslintrc.js
- .prettierrc
- static/js/blame.js
- static/js/code-highlighter.js
- static/js/dxr.js
- static/js/filter.js
- static/js/panel.js
- static/js/utils.js
I need to admit I'm totally not a fan of curly braces but oh well :)
> Add an eslint and prettier config.

- tools/Cargo.lock
- tools/Cargo.toml
- tools/malloc_size_of/Cargo.toml
- tools/src/bin/build-blame.rs
- tools/src/config.rs
- tools/src/git_ops.rs
This should be 100% hash-compatible with the python version. The code structure is very similar as well, as I basically ported it from the python code directly. I will be restructuring a bunch of this code later to make it more amenable to parallelization.
> Initial implementation of rusty blame builder

- clang-plugin/MozsearchIndexer.cpp
https://treeherder.mozilla.org/#/jobs?repo=try&revision=58a1a8ad48de9ef1d8444ec08164fa6a816f2f2e came out green
> Bug 1635198 - Make make_unique work in multiple build scenarios. r=kats

- static/js/dxr.js
Another one in the "silly typos" category...
> Bug 1635269 - Fix regression in expando click event handler.

- docs/newrepo.md
Feel free to bikeshed on the "git" and "blame" folder names, I'm happy to change that before I write the config.json entry for the v-c-s repo.
> Update docs for new repos slightly

- docs/aws.md
- infrastructure/aws/attach-index-volume.py
- infrastructure/aws/awslib.py
- infrastructure/aws/build-lambda-indexer-start.sh
- infrastructure/aws/delete-volume.py
- infrastructure/aws/detach-volume.py
- infrastructure/aws/make-crontab.py
- infrastructure/aws/scp-while-sshed.py
- infrastructure/aws/send-done-email.py
- infrastructure/aws/send-failure-email.py
- infrastructure/aws/send-warning-email.py
- infrastructure/aws/ssh.py
- infrastructure/aws/terminate-indexer.py
- infrastructure/aws/trigger-provision.py
- infrastructure/aws/trigger-web-server.py
- infrastructure/aws/trigger_indexer.py
- infrastructure/aws/upload.py
- router/codesearch.py
- router/crossrefs.py
- router/identifiers.py
- router/logger.py
- router/router.py
- scripts/build-codesearch.py
- scripts/find-objdir-files.py
- scripts/indexer-setup.py
- scripts/lib.py
- scripts/nginx-setup.py
- tests/find-repo-files.py
> More python3 migration

- infrastructure/web-server-provision.sh
- router/codesearch.py
- router/crossrefs.py
- router/identifiers.py
- router/router.py
Requires a reprovisioning of the webserver before merging since there's a provisioning change in here.
> Make the router.py run with python3

- docs/aws.md
Just need one reviewer, but @asutherland and @emilio - you should both read the new docs and update your local setup accordingly. Let me know if you run into any problems.
> Bug 1633077 - Update AWS access docs to use new SSO/maws mechanism

- infrastructure/aws/attach-index-volume.py
- infrastructure/aws/detach-volume.py
- infrastructure/aws/main.sh
- infrastructure/aws/make-crontab.py
- infrastructure/aws/send-done-email.py
- infrastructure/aws/send-failure-email.py
- infrastructure/aws/send-warning-email.py
- infrastructure/aws/trigger-web-server.py
- infrastructure/aws/upload.py
Also a couple of miscellaneous changes
> Migrate remaining AWS scripts to python3

- scripts/nginx-setup.py
- static/robots.txt
- tests/help.html
> Improve indexing

- infrastructure/indexer-provision.sh
- infrastructure/web-server-provision.sh
Apparently it only comes in snap form.
> Bug 1672014 - Provision the yq tool

- static/css/icons.css
- static/css/mozsearch.css
- static/icons/copy.svg
- static/icons/tick.svg
- static/js/panel.js
- tools/src/bin/output-file.rs
- tools/src/format.rs
- tools/src/output.rs
More explicit alternative to #368.
> Add a "copy to clipboard" button to (some) panel entries.

- scripts/find-repo-files.py
There's only a handful of .mjs files so yeah we might as well do semantic analysis on them. (Re your comment on #381 )
> Bug 1672004 - Also do semantic analysis on mjs files

- tools/src/bin/web-server.rs
This should prevent errors like [1] from happening again.
[1]: https://bugzilla.mozilla.org/show_bug.cgi?id=1674271
> web-server: handle clients cutting the connection early more gracefully.

- router/router.py
- tests/tests/files/mobile/androidTest/asserts/inputs.html
geckoview-junit files are into mobile/android/geckoview/src/androidTest,
but these files isn't recognized as test files.
> Bug 1677731 - androidTest directory should be recognized as test files.

- tools/src/bin/build-blame.rs
I was catching up on reviews, and noticed these.
> build-blame: Some minor style nits.

- static/js/code-highlighter.js
https://asuth.searchfox.org/ has this using a config1 spare server from yesterday.
> Bug 1702319 - Update title based on last selected line or current sticky line.

- tests/tests/files/IGeckoEditableParent.aidl
- tools/src/languages.rs
The lexer file is https://android.googlesource.com/platform/system/tools/aidl/+/refs/heads/master/aidl_language_l.ll.
> Bug 1708684 - Add syntax highlighting for AIDL.

- docs/crossref.md
- router/crossrefs.py
- router/raw_search.py
- router/router.py
In the review fixes I renamed consumes to callees as suggested but my
renaming was not extensive enough!
> Bug 1641372 - Python s/consumes/callees/ fixes.

- Makefile
- infrastructure/web-server-run.sh
- tests/tests/checks/inputs/query__big_cpp__abstractart__json
- tests/tests/checks/inputs/query__big_cpp__abstractart_beart__json
- tests/tests/checks/inputs/query__big_cpp__human__json
- tests/tests/checks/inputs/query__big_cpp__practicalart__json
- tests/tests/checks/inputs/query__big_cpp__practicalart_beart__json
- tests/tests/checks/inputs/query__overs_cpp__doublePure__json
- tests/tests/checks/inputs/query__overs_cpp__triplePure__json
- tests/tests/checks/snapshots/check_glob@query__big_cpp__abstractart__json.snap
- tests/tests/checks/snapshots/check_glob@query__big_cpp__abstractart_beart__json.snap
- tests/tests/checks/snapshots/check_glob@query__big_cpp__human__json.snap
- tests/tests/checks/snapshots/check_glob@query__big_cpp__practicalart__json.snap
- tests/tests/checks/snapshots/check_glob@query__big_cpp__practicalart_beart__json.snap
- tests/tests/checks/snapshots/check_glob@query__overs_cpp__doublePure__json.snap
- tests/tests/checks/snapshots/check_glob@query__overs_cpp__triplePure__json.snap
- tests/tests/files/overs.cpp
- tools/src/abstract_server/remote_server.rs
- tools/src/bin/searchfox-tool.rs
- tools/src/cmd_pipeline/builder.rs
- tools/src/cmd_pipeline/cmd_query.rs
- tools/src/cmd_pipeline/interface.rs
- tools/src/cmd_pipeline/mod.rs
- tools/src/cmd_pipeline/parser.rs
- tools/tests/test_check_insta.rs
(See individual commits for more details.)
> Bug 1729178 - Add "query" test coverage and new test cases

- README.md
I just redid my VM as a regular sanity check and thought I should update the provisioning line.
> Update last line of successful provisioning

- README.md
Address https://github.com/mozsearch/mozsearch/pull/448#pullrequestreview-751374041
> Guidance to use the full 40char hash

- docs/aws.md
The docs are also the only way this gets run!
> Bug 1721037 - switch provision script order in docs.

- infrastructure/aws/indexer-provision.sh
- infrastructure/indexer-provision.sh
- infrastructure/web-server-provision.sh
- scripts/indexer-logs-analyze.sh
- scripts/indexer-logs-fetch.sh
- scripts/indexer-logs-print.py
- scripts/weblog-analyze.sh
Please see the individual commits which reference their relevant bug and the relevant bugs where I'll link these.
> Land git-cinnabar update, cloudwatch log removal, indexing helper scripts

- static/css/mozsearch.css
> Bug 1742144 - Dark mode: style info-boxes.

- static/css/mozsearch.css
Also simplify link styling while at it. We don't have links in bubbles
and :link+:visited is the same as :any-link.
> Bug 1742365 - Dark mode: better link colors.

- static/css/mozsearch.css
- static/js/context-menu.js
This is the part of #471 which should not mess with people's
muscle-memory :-)
> context-menu: Make context menu scrollable.

- tests/tests/checks/snapshots/check_glob@merge__big_cpp.snap
The snapshot changes for
https://github.com/mozsearch/mozsearch/commit/96b8f2b073622701620f18a398aa4ad50c2700cd
which I failed to commit due to not running `make review-test-repo` after
the test failed.  An argument in favor of getting CI running on PRs.
> Commit the snapshot changes from the test change.

- docs/aws.md
- infrastructure/aws/send-provision-email.py
- infrastructure/aws/trigger-provision.py
- infrastructure/aws/trigger-web-server.py
- infrastructure/aws/trigger_common.py
The remaining problems were due to not explicitly specifying the region
all the time.  Emails should be sent and tags automatically updated.
Indexers and web-servers should now use these new AMIs.
> Bug 1747289 - Finalize / use automatically generated AMIs.

- docs/aws.md
Follow-up to the documentation updates from bug 1747289
> Additional doc fixes

- README.md
- docs/searchfox-tool-cookbook.md
- docs/testing-checks.md
- router/codesearch.py
- tools/Cargo.lock
- tools/Cargo.toml
- tools/src/cmd_pipeline/cmd_query.rs
Details on the bug and in the revised docs.
> Bug 1760465 - Make it easier to investigate what's going on with searchfox queries

- static/js/code-highlighter.js
This fixes the issue Olli reported on Matrix.
> sticky: Accurately detect stuck position.

- .gitignore
- tools/templates/pipeline_explainer.liquid
Forgot to add the templates/ directory in https://github.com/mozsearch/mozsearch/pull/499.  I'm also including some additional .gitignore coverage here to make it less likely for me to make this error in the future!
> Whoops templates

- infrastructure/aws/trigger-provision.py
- infrastructure/indexer-provision.sh
- infrastructure/web-server-provision.sh
See https://bugzilla.mozilla.org/show_bug.cgi?id=1764957
> Provision failed

- .gitignore
This directory is created by test
https://github.com/mozsearch/mozsearch/blob/117e70d95008c48f83f7c16eb856488135265baf/tools/tests/test_check_insta.rs#L241-L242
> Ignore tests/tests/checks/explanations/ directory generated by test

- scripts/output.sh
- tools/src/bin/output-file.rs
- tools/src/format.rs
I'm going to land this immediately and trigger config2.json immediately for maximum fidelity.  I tested this locally and things didn't catch on fire, but it wouldn't surprise me if I have to put out some fires.
> Add more logging to investigate bug 1567724 more

- static/js/panel.js
Otherwise copying heavily-indented code blocks ends up copying a lot of
whitespace.
> panel: Deindent code blocks when copying them to markdown.

- docs/aws.md
It pays to make sure you save all buffers before committing!
> Bug 1766925 - Additional AWS doc updates.

- scripts/weblog-analyze.sh
This:
- Addresses new tac pipe errors by using `tac | tail | tac` instead of
`tac | tac | head` because tac on the newest ubuntu seemed to start
complaining about head closing the pipe again.
- We now show both cache hits and misses for cacheable URLs and not
just misses.  The rationale is that it's good to know how many hits
we're getting and also to be able to be aware of any S3 latency in
reading the files.  For example, I'm actually a little surprised
that we're not seeing more hits.
- We group by the hit/miss, of course.
> Bug 1779672 - weblog analyze improvements

- infrastructure/aws/trigger-web-server.py
- infrastructure/aws/web-serve.sh
- infrastructure/common-provision-pre.sh
I will immediately provision both of these.
> Bug 1779899 - pre-cache all m-c indices on release1

- scripts/weblog-analyze.sh
comm-central's search performance is now comparably much worse so we
don't want it impacting mozilla-central's stats which are the thing I
optimized.
> Bug 1779899 - be able to filter weblogs by tree

- router/codesearch.py
As captured in the added comments, although we don't ever want our
queries to take 30 seconds, the reality is that because of our caching
it's better for a query to take 30 seconds and return all the results
(up to max_limit) than take 10 seconds and truncate the results and
where our caching then prevents re-running the query with a hot disk
cache where it could potentially return the full results in under 10
seconds.
> Bug 1780902 - increase codesearch timeout to 30 seconds

- infrastructure/aws/trigger_common.py
This requires the lambda jobs to be regenerated (because they internalize
the trigger_indexer.py script and deps).  I'll do that after landing.
> Bug 1705961 - terminate stopped indexers too when triggering indexer

- tools/Cargo.lock
- tools/Cargo.toml
- tools/src/describe.rs
- tools/src/format.rs
- tools/src/languages.rs
- tools/src/tokenize.rs
This provides some basic syntax highlighting on CSS files.
> languages: Tokenize css.

- static/js/search.js
- tests/tests/checks/snapshots/web/dirs/check_glob@root_listing__html.snap
- tests/tests/files/some_javascript.js
This fixes Mozilla bug 1798496.
> search: Escape a little bit more.

- static/js/search.js
I didn't actually test this, but I think this should work
> Set JS icon for mjs files

- scripts/js-analyze.js
This should reduce noise in our inboxes.
> No bug: Add an intervention to avoid getting warnings due to 1822717-module.js

- static/js/code-highlighter.js
Also support finding a destructor from multiple symbols
> Bug 1843722 - Update DocumentTitler for SYM_INFO

- static/js/code-highlighter.js
depends on https://github.com/mozsearch/mozsearch/pull/640
> Bug 1773379 - Support multiple lines selection in DocumentTitler

- infrastructure/indexer-setup.sh
- infrastructure/indexer-upload.sh
- scripts/load-vars.sh
See commit messages for details.
> Bug 1842632 - Don't do continue-on-error during the setup phase

- README.md
- docs/aws.md
This is basically just translating the canonical docs at https://mozilla-hub.atlassian.net/l/cp/GH1kL2zg into our docs.
> Bug 1852805 - Update searchfox SSO workflow docs from maws.

- infrastructure/aws/trigger-provision.py
There's a limit on the data we send when triggering the indexer.  Right now we send a concatenation of our various provisioning scripts (wrapped inside a shell script HERE directive).  My recent other commit changes pushed us over this limit, so my pragmatic fix is to use a regexp to elide comment lines, avoiding removing hashbang lines which can be load bearing.  We leave single newlines for whitespace, compressing runs of newlines.
A `--dry-run` command with hacky parsing was added to aid in validating the changes.
Provisioning successfully completed with these changes and indexer runs then successfully completed on those provisioned jobs, so landing.
> Bug 1812838 - Elide comments from provisioning user data

- README.md
Let's add the explanation about the logging to README.
> Add explanation of logging after triggering indexer

- scripts/js-analyze.js
> Load sax.js only if necessary

- tests/tests/checks/snapshots/analysis/urlmap/root.html/check_glob@url_use_in_html__json.snap
- tests/tests/checks/snapshots/analysis/urlmap/root.js/check_glob@url_use_in_script__json.snap
- tests/tests/checks/snapshots/analysis/urlmap/root.mjs/check_glob@url_use_in_module__json.snap
- tests/tests/checks/snapshots/analysis/urlmap/root.xhtml/check_glob@url_use_in_xhtml__json.snap
- tests/tests/metadata/test.chrome-map.json
Fixed typo for filename extension
> Fix test chrome-map

- scripts/js-analyze.js
- tests/tests/checks/inputs/analysis/js/export8.mjs/ignore_anonymous_function_default__json
- tests/tests/checks/snapshots/analysis/js/export8.mjs/check_glob@ignore_anonymous_function_default__json.snap
- tests/tests/files/js/export8.mjs
Fixes "Invalid expression FunctionDeclaration" warnings happening on release
> Ignore anonymous FunctionDeclaration in export default

- scripts/js-analyze.js
Fixes warning for kaios indexing
> Ignore dom/media/test/test_imagecapture.html in kaios

- tests/tests/checks/snapshots/fancy/format-symbol/field-layout/big_cpp.cpp/check_glob@field_layout__outercat__json.snap
- tests/tests/checks/snapshots/fancy/format-symbol/field-layout/bitfields.cpp/check_glob@field_layout__bitfields__json.snap
- tests/tests/checks/snapshots/fancy/format-symbol/field-layout/holes.cpp/check_glob@field_layout__holes__json.snap
- tests/tests/checks/snapshots/fancy/format-symbol/field-layout/platform_specific_field.cpp/check_glob@field_layout__platform_specific_field_1__json.snap
- tests/tests/checks/snapshots/fancy/format-symbol/field-layout/platform_specific_field.cpp/check_glob@field_layout__platform_specific_field_2__json.snap
- tests/tests/checks/snapshots/fancy/format-symbol/field-layout/platform_specific_size.cpp/check_glob@field_layout__platform_specific_size__json.snap
- tests/tests/checks/snapshots/web/query/execution/field-layout/check_glob@query__field_layout__outercat__json.snap
I forgot to update test snapshots
> Bug 1900176 - followup: Update tests

- static/js/search.js
for https://bugzilla.mozilla.org/show_bug.cgi?id=1904323
> Bug 1904323 - Do not touch column selector objects when not available

- README.md
- build-docker.sh
- infrastructure/common-provision-pre.sh
- infrastructure/indexer-provision.sh
- infrastructure/web-server-provision.sh
A few fixes towards bug 1904474. I don't have it fully working yet though.
> Bug 1904474 - Miscellaneous fixes

- clang-plugin/MozsearchIndexer.cpp
Reverts mozsearch/mozsearch#766
As noted in https://github.com/mozsearch/mozsearch/pull/766#issuecomment-2190319836 this patch ended up bit-rotted.
> Revert "Reuse more code between the codepaths that emit structured info for different Decl types"

- tools/src/tokenize.rs
for https://bugzilla.mozilla.org/show_bug.cgi?id=1768480
* allow `[` to be followed by RegExp, which can be e.g. `[/foo/]`
* allow `}` to be followed by RegExp, which can be the first token after the last block statement
* allow `;` to be followed by RegExp, which can be the first token after last statement
* add tests
* add some comments about overlapping cases
> Bug 1768480 - Allow more characters to be followed by RegExp in tokenizer

- static/js/settings.js
For https://bugzilla.mozilla.org/show_bug.cgi?id=1910106
This does:
* Add `introducedIn` property for each setting
* Make `introducedIn` property required
* Verify the consistency (existence of `introducedIn`, and make sure `introducedIn` is within the `SETTINGS_VERSION`), on non-production env
> Bug 1910106 - Make introducedIn field for settings required, and verify the consistency on testing env.

- scripts/build-codesearch.py
- scripts/lib.py
This makes us emit the config file and the stdout/stderr of invoking codesearch so we can understand what's going on with mozilla-mobile.
> Bug 1924797 - instrument build-codsearch.py to understand mozilla-mobile problem

- tests/tests/checks/snapshots/analysis/cpp/ForwardingTemplates.cpp/check_glob@TypeDependentNewInMethodReportedAtCallSite.snap
- tests/tests/checks/snapshots/analysis/cpp/ForwardingTemplates.cpp/check_glob@TypeDependentNewInTemplateReportedAtCallSite.snap
- tests/tests/checks/snapshots/analysis/cpp/bug1781178.cpp/check_glob@Foo_E.snap
- tests/tests/checks/snapshots/analysis/cpp/bug1781178.cpp/check_glob@Foo_E_Waldo.snap
- tests/tests/checks/snapshots/crossref/crossref/big_cpp.cpp/check_glob@stackartholder__json.snap
- tests/tests/checks/snapshots/crossref/crossref/big_cpp.cpp/check_glob@thing__json.snap
- tests/tests/checks/snapshots/crossref/crossref/big_cpp.cpp/check_glob@thing_mHP__json.snap
- tests/tests/checks/snapshots/crossref/expand/big_cpp.cpp/check_glob@outercat__json.snap
- tests/tests/checks/snapshots/crossref/merge/check_glob@merge__big_cpp.snap
Revert the wrong change from #840
> Revert the wrong update for the test snapshot

- flake.lock
- flake.nix
- run-docker.sh
I've updated my Nix shell along the way but since I'm still the only user (I think?), I never actually pushed it.
> Nix Flake update

- tests/webtest/test_CopyAsMarkdown.js
- tests/webtest/test_LineNumberInURL.js
- tests/webtest/test_MacroExpansions.js
for https://bugzilla.mozilla.org/show_bug.cgi?id=1935291
* Part 1 is for removing unstable symbol in the test
* Part 2 and Part 3 are for updating the webtest to follow the code formatting in the test file
> Bug 1935291 - Update webtests

- tests/tests/checks/snapshots/web/files/nav-panel/check_glob@wpt__some_cross_global_test__navpanel__html.snap
- tests/tests/checks/snapshots/web/files/nav-panel/check_glob@wpt__test_ima_weird_meta_wpt__navpanel__html.snap
When testing the last few iterations of #852 I only used the searchfox repo for testing and didn't notice I needed to update snapshots for the test repo.
> Update insta snapshots following the addition of data-accel attributes

- infrastructure/aws/ssh.py
for https://bugzilla.mozilla.org/show_bug.cgi?id=1943886
* Add a special mode if the parameter is "-", which shows the list of instances and shows a prompt to select the instance
* The no parameter behavior isn't modified for backward compatibility, except for showing the help for the "-" parameter
The output without parameter
```
$ ./infrastructure/aws/ssh.py 
usage: ./infrastructure/aws/ssh.py (<instance-id>|-)
-: Show the instances and prompt for selecting it
Current instances:
i-xxx ...
i-yyy ...
...
i-www ...
```
The output with "-" parameter:
```
$ ./infrastructure/aws/ssh.py  -
Current instances:
1) i-xxx ...
2) i-yyy ...
...
8) i-www ...
index: 1   <<< prompt for the index
...        <<< logging in to the instance i-xxx
```
> Bug 1943886 - Let the instances list in ssh.py selectable.

- infrastructure/aws/ssh.py
For https://bugzilla.mozilla.org/show_bug.cgi?id=1992698
This does:
* Add an optional pattern parameter to ssh.py with "-" option, to apply a substring filter to the instance list
For example:
* `ssh.py - release1` lists only the instances with release1 channel
* `ssh.py - config1` lists only the instances with config1 config
* `ssh.py - arai` lists only the instances with arai channel
> Bug 1992698 - Add filter to ssh.py -.
