mozsearch/mozsearch

tools/src/tokenize.rs
I was reading the code over the weekend and realized that my patch to add C++ raw literals didn't handle newlines properly, which seems like a bug that's worth fixing. In doing so, I noticed that the code to split a token across a newline was duplicated a couple of times so I pulled it out -- that being said, I'm a little surprised that I had to explicitly pass `tokens` in as a `&mut Vec<>`. Do you know why that's required?
I also fixed error reporting for illegal regexps ending with an escaped newline. It probably isn't a big deal, but we handle that case correctly in the string literal code, so I figured it was worth being consistent.
=> Newline fixes

tools/src/languages.rs
I noticed recently that *.configure files in the tree weren't being recognized as Python.
=> Recognize moz.configure as Python

tools/src/languages.rs
http://searchfox.org/mozilla-central/source/browser/base/content/test/referrer/file_referrer_policyserver.sjs should be syntax highlighted as JS.
=> Register *.sjs as JavaScript

tools/src/languages.rs, tools/src/tokenize.rs
I don't know if this list of changes is exhaustive. I didn't bother adding a `LanguageSpec` field for each minor difference, though I could if that would be better.
The differences between Rust raw strings and C++ raw strings are so slight that I can *almost* use the same code for them, but they're also just different enough that it's hard. In particular, having the internal () structure of the C++ raw strings changes it just enough.
The Rust label vs. character literal thing is annoying, oh well.
I haven't tested beyond the tests added in the patches.
=> Rust tokenization

tools/src/tokenize.rs
Sorry for the spam – I just realized that there's a edge case in the comment parsing code that I got wrong.
=> Fix a rust nested comment edge case

tools/src/output.rs
I was looking at output.rs the other day and noticed a lot of string escaping going on. I think it's more natural to use raw strings, so I wrote a patch to switch over to using them. This shouldn't have any effect on anything, it just looks nicer IMO.
=> Use Rust raw strings instead of lots of escapes

tools/src/bin/output-file.rs
This changeset adds a link to the raw file on hg.mozilla.org. Comes in handy for SVG files, for example.
=> Add link to Raw file

tools/src/bin/ipdl-analyze.rs, tools/src/format.rs, tools/src/languages.rs, tools/src/output.rs, tools/src/tokenize.rs
There's never a need to use `&Vec<T>` over `&[T]`, since they're always
immutable.
Similarly, there's never a reason for using `&String` over `&str`.
=> tools: Remove unneeded indirections in a few places.

tools/src/blame.rs
While at it, also avoid creating a regex each time that function is called.
=> blame: Linkify servo PR in commit message headers.

tools/src/languages.rs
We have a decent amount of Java code in the tree and it's a bummer that searchfox doesn't syntax highlight it. It seemed easy enough to add, so I did that.
I was going to wait until I tested this to PR, but, well, I can't actually do that, since the vagrant build seems to be broken (due to livegrep failing to build? I had to add `--incompatible_disallow_set_constructor=false` [here](https://github.com/bill-mccloskey/searchfox/blob/master/infrastructure/indexer-provision.sh#L46), which made it get a bit further, but it still failed complaining but I guess it couldn't install libgit due to some issue with the checksum?).
I'm tcsc on moz irc if you need to ask me anything about this patch, or my issue with vagrant.
=> Add syntax highlighting for java files.

README.md
The comment says ~/config but the command uses ~/mozilla.config.
=> fix comment on command

tools/src/bin/crossref.rs
(This includes my patch for bug 1416876 because it is based on top of that and I don't know how to do that the right way.)
I did some light local testing, all the way up to running a webserver for the results of a full Firefox run and the few things I checked seemed ok. The output from this file was also unchanged, when I checked it for the small set of test files.
=> Reduce memory usage in crossref.rs by sharing strings

tests/config.json, tools/src/bin/output-file.rs, tools/src/config.rs, tools/src/format.rs
This makes it so that we can specify a git repo in the config.json
without a blame repo, and get the partial functionality that unlocks.
In particular this enables the navigation panel if the tree has a git
repo specified, even if it doesn't have the blame repo.
This also adds the searchfox git repo to the tests/config.json file, so
now using the test repos it's possible to exercise the navigation panel.
Note that the links in the navigation panel are still hard-coded to
mozilla-central/gecko-dev which is a separate pre-existing issue (happens
on e.g. the nss repo on searchfox.org as well).
=> Make the blame repo optional.

tools/src/bin/output-file.rs, tools/src/format.rs
This changes the type of the `commit` argument to be consistent with the
type of `blame_commit`. Conceptually I believe this is more in line with
the intent of the code, which is to have the function take an optional
commit, but without moving ownership of that thing into the function.
=> Follow-up to #30

blame/transform-repo.py
Ran into this problem when generating the blame repo for mozsearch itself.
=> Handle submodules when generating blame repos

clang-plugin/MozsearchIndexer.cpp
This makes it easier to look at the analysis file and compare it to the
raw source file because the line numbers are better sequenced.
(Feel free to reject this change - I just found it slightly useful in the particular thing I was looking at, but I don't know if it's going to be widely useful and is worth the extra bytes cost)
=> Zero-pad the line numbers in the analysis file.

.gitignore
Some editors (like atom) may be configured to hide directories that are
.gitignore'd.  When there's no slash, the ignore matches /static/js.
=> Don't ignore /static/js subtree.

static/js/context-menu.js
Some rust pretty symbols have angle brackets and such. Make sure to escape them so that they show up properly.
=> context-menu: Escape html special characters.

docs/aws.md, infrastructure/aws/ssh.py
I don't know if anybody else is having this problem, but putting the IdentityFile command in my .ssh/config file was causing my other ssh connections to always fail. So I kept having to comment it out for those connections and uncomment it for searchfox ssh connections.
This PR makes it so that the ssh.py script picks up the key from ~/.aws/private_key.pem (if it exists) so you don't need to put it in your .ssh/config file. (This is optional, so if you want to leave it in your .ssh/config file that's fine too).
=> Allow picking up the private key from ~/.aws

scripts/idl-analyze.sh
This change makes it less annoying to run the indexer-run script. I needed it yesterday on the airplane since I didn't have a network connection.
=> Don't download XPIDL parser if not needed

js-analyze.js
This change removes the ability to search for local JS variables. This should reduce the load on the cross-referencer and make it more likely that we'll be able to index add-on JS. It will also bring the JS indexer in line with the C++ one. Note that globals variables are treated as properties, so they'll still be indexed.
=> Don't cross-reference local JS variables

infrastructure/indexer-provision.sh
The current vagrant build (provision? whatever you'd call it) was broken for me due to a bazel update, this fixed it. Specifically, I get something like 
```
==> default: ERROR: /home/vagrant/livegrep/src/proto/BUILD:6:1: Traceback (most recent call last):
==> default: 	File "/home/vagrant/livegrep/src/proto/BUILD", line 6
==> default: 		go_proto_library(name = "go_proto", protos = ["live..."], ...)
==> default: 	File "/root/.cache/bazel/_bazel_root/afac32cc4b4378a2a7ed263118fd7a0e/external/org_pubref_rules_protobuf/go/rules.bzl", line 69, in go_proto_library
==> default: 		go_proto_deps += GRPC_COMPILE_DEPS
==> default: trying to mutate a frozen object
```
When building codesearch. https://github.com/bazelbuild/bazel/releases/tag/0.8.0 says they took out the …
=> Explicitly use bazel 0.7.0 for building

js-analyze.js
guardedHandlers was removed in bug 1228841.
=> Remove obsolete guardedHandlers code.

tests/searchfox/find-repo-files, tests/tests/find-repo-files
Developing mozsearch locally on a Windows host doesn't work well because
the repository contains symlinks and the Windows checkout of the symlinks
may not work properly (at least by default). Since all the symlinks
point to the same script, we can just put that script in the scripts/ folder
and use it from there. The script is also updated to incorporate changes
from the mozsearch-mozilla repo, as this script will now be used to process
all trees.
=> Remove symlinks as they don't work well on a Windows host

infrastructure/indexer-provision.sh, infrastructure/web-server-provision.sh, scripts/indexer-setup.py, scripts/mkindex.sh, scripts/rust-analyze.sh, tests/tests/build, tests/tests/files/Cargo.lock, tests/tests/files/Cargo.toml, tests/tests/files/simple.rs, tests/tests/files/test_rust_dependency/Cargo.toml, tests/tests/files/test_rust_dependency/src/lib.rs, tools/Cargo.lock, tools/Cargo.toml, tools/src/bin/rust-indexer.rs
Don't run it yet by default, since I haven't tested it on mozilla-central.
=> Basic rust indexing support.

tools/src/bin/rust-indexer.rs
This allows finding all the trait implementations from a trait function with a
single click.
Before this, in the test code, for example, for the "fn do_bar" line in
"impl MyTrait for Loader" we get the following symbol:
```
simple<Loader as test_rust_dependency::MyTrait>::do_bar
```
This is fine, but we also want to get:
```
test_rust_dependency::MyTrait::do_bar
```
So we can relate all the impls of the same function for the trait.
=> rust-indexer: Handle better trait function impls. 

clang-plugin/MozsearchIndexer.cpp, tests/tests/files/simple.cpp, tests/tests/files/simple.rs, tools/src/bin/rust-indexer.rs
(By returning the unmangled name in both cases)
This fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1428841.
=>  Make rust and C agree on symbols for extern functions

static/js/context-menu.js
This patch allows you to click on an identifier and then select "Sticky highlight" from the context menu. The context menu disappears and the identifier stays highlighted until you click somewhere. This is nice to find all the uses of a local variable in a large function.
=> Add sticky highlight support

static/js/context-menu.js
Without this, once sticky hover is enabled, the user has to click on empty
space, AND move the mouse for the sticky hover to be cleared. Instead the
click alone should do it.
Follow-up to #58.
=> Immediately clear sticky hover when clicking away from things

infrastructure/indexer-setup.sh
When indexing mozilla-central, blowing away the working dir is
painful because it has to redownload the world which takes forever.
This allows devs (who know what they are doing) to run indexer-setup
with KEEP_WORKING=1 to keep the working directory instead of
blowing it away. The default behaviour is unchanged.
=> Allow preserving the old working dir when setting up the indexer

infrastructure/indexer-run.sh, infrastructure/indexer-setup.sh, infrastructure/indexer-upload.sh, scripts/build.sh, scripts/crossref.sh, scripts/idl-analyze.sh, scripts/ipdl-analyze.sh, scripts/js-analyze.sh, scripts/load-vars.sh, scripts/mkindex.sh, scripts/output.sh, scripts/rust-analyze.sh
Each sub-script that does a particular step of the index building
runs the load-vars script as though it can be run in a standalone
manner. But it can't. There are hidden dependencies on other
variables (most notably the $WORKING variable which is only set
in the indexer-* scripts but used as part of various config
variables like $OBJDIR). So this standalone mode is not a real
thing and we should stop pretending that it is.
This patch does a bunch of cleanup on the load-vars.sh script
and places that use it.
As a bonus it also removes the FILTER variable from some scripts
which seems to be similarly unused and broken.
=> Remove spurious load-vars.sh goop and FILTER variable

scripts/mkindex.sh, scripts/rust-analyze.sh, tests/tests/files/Cargo.toml, tests/tests/files/build.rs, tests/tests/files/simple.rs, tools/src/bin/rust-indexer.rs
This will allow the indexer on Servo to actually be useful.
=> rust-indexer: Handle properly generated files.

tools/src/bin/rust-indexer.rs
=> rust-indexer: Make the inputs optional.

router/codesearch.py, scripts/build-codesearch.py
The livegrep indexing is git-aware, and works on a per-repo basis for git repos.
When we switched c-c from using a hg repo to a git repo, we also started going
down the "git repo" codepath in build-codesearch.py, which ignored the mozilla/
subfolder since it wasn't part of the repo. This patch adds the mozilla/
subfolder as another repo to the livegrep config, and ensures it gets searched
along with comm-central. Some fiddling is needed to make sure we adjust the paths
properly to account for the mozilla/ subfolder.
Perhaps in the future we can find a way to reuse the top-level gecko-dev repo
here to save building the livegrep index twice, but that seems more involved and
this gets the job done for now.
=> Bug 1451373 - Ensure we index the mozilla subrepo inside c-c as well.

Vagrantfile, infrastructure/indexer-provision.sh, infrastructure/web-server-provision.sh
Right now provisioning a new vagrant machine is broken because pip installs a newer version of pygit2 than the libgit that gets installed. This fixes that and also (unrelatedly) also fixes the provisioning to better match what happens in production.
=> Provisioning fixes

tools/src/format.rs
If you generate two index dirs with different versions of the mozsearch code,
doing a recursive diff on the two file/ directories turns up a lot of spew
because of the changed timestamp. With this patch you can set the
MOZSEARCH_DIFFABLE=1 envvar while running indexer-run.sh to omit the timestamp
and get a cleaner diff. This makes it easier to test changes.
=> Allow using an envvar to make the output files diff easily

scripts/nginx-setup.py
Firefox(/browsers) cache 301 results which makes them hard for users to
deal with since the normal "refresh" mechanism is no good once you've been
redirected to the target location.  The 301 redirect mechanism is used by
the REPO/define?q=TERM mechanism served by router.py.
In order to reduce users experiencing stale redirects and needing to
disable/purge their cache, we set the expiration time to 10 minutes.
Although the redirects are generated in router.py, the actual cache
lifetime comes from the nginx config, so we alter it there using nginx's
map module, documented at
https://nginx.org/en/docs/http/ngx_http_map_module.html
In the process of implementing and testing this, I realized that we
were actually only providing expiration directives for REPO/source and
"/".  All the …
=> Bug 1478639 - Use consistent caching, have 301's expire after 10min rather than 1 day.

infrastructure/aws/trigger_indexer.py
This makes it easier to see which stopped instances were triggered by who/where
=> Tag indexers with some useful info

infrastructure/aws/trigger-provision.py
Same idea as #125, but tagging for provisioning instances used to generate new AMIs.
=> Tag provisioning instances to make them easier to identify

docs/aws.md, infrastructure/aws/trigger-provision.py
This makes it easier to tell when the provisioning is complete. Running `ps` is not as good because there appears to be a bazel daemon that keeps running and sometimes it's not obvious when the provisioning itself is done.
=> Log AWS provisioning script output to a file

infrastructure/indexer-provision.sh, infrastructure/web-server-provision.sh, scripts/build-codesearch.py
This will require rebuilding the indexer and web-server AMIs.
Current dev instance is running with this.
=> Bug 1466402 - Bump livegrep version to fork from latest master

infrastructure/web-server-setup.sh
Looks to be a simple typo that's been around forever.
=> Fix incorrect bash syntax

infrastructure/indexer-provision.sh
I added this build dependency in https://bugzilla.mozilla.org/show_bug.cgi?id=1478813.
Perhaps we should run `./mach bootstrap` somehow...
=> Install cbindgen for m-c

scripts/mkindex.sh
rustc is run during the build step and generates a lot of info-level
output which we don't care about. It bloats the log files by hundreds
of megabytes unneccessarily.
=> Follow-up to #137: don't log rustc invocations at info level

scripts/js-analyze.js
This fixes the current indexing failure, so I'm going to go ahead and merge it.
=> Don't throw an exception when encountering a CallImport statement

infrastructure/indexer-provision.sh
Depends on https://github.com/mozsearch/mozsearch-mozilla/pull/17
=> Bug 1490160 - Don't install cbindgen directly; let bootstrap do it

infrastructure/aws/trigger-web-server.py, infrastructure/aws/trigger_indexer.py, infrastructure/indexer-provision.sh, infrastructure/web-server-provision.sh
Previously we were installing rust using static.rust-lang.org which
installs rustc into /usr/local/bin and doesn't install rustup. However,
in order to get the rust stdlib source, it's better to use the more
traditional rustup installation mechanism, which installs it into the
user home folder and also installs rustup. This patch does that and
then uses `rustup update` to update rust as needed, instead of rerunning
the installer in update.sh
This also means we need to run the update.sh script as the ubuntu user,
instead of root, so that rustup is on the $PATH. This is desirable anyway
because running things as root sucks, and the update.sh scripts already
use sudo for individual commands that need root, so in this case running
the script as root is completely avoidable.
=> Ensure we provision rustup.

tools/src/bin/rust-indexer.rs
The pretty name in target records is used to build the identifiers table,
and should not contain spaces. The source record, however, can contain
spaces and be more human-readable. This patch corrects the code from #78
which made both source and target records human-readable instead of just
the source records.
=> Bug 1474434 - Fix 'pretty' property for rust target records.

static/css/icons.css, static/js/panel.js, tools/src/output.rs
It doesn't play well with some features like typeahead find, so
people may want to disable it. This also adds a small cookie
library to save the user's choice.
=> Bug 1494348 - Add a toggle to disable keyboard shortcuts.

router/router.py, scripts/js-analyze.js, scripts/output-help.js, scripts/output.sh, scripts/rust-analyze.sh
I convinced some Igalia folks to try maintaining their own searchfox instance with an up-to-date WebKit index (which would be very useful for us as well, since grepping WebKit is a bit of a pain).
This were some fixes that I needed to set something very simple up.
=> Some small tweaks to make mozsearch a bit less Gecko-specific.

tools/src/file_format/analysis.rs, tools/src/lib.rs
We'll still get notified via a warning email but at least we'll finish indexing, minus the analysis data that couldn't be parsed.
=> Downgrade a panic to a warning so we handle it more gracefully

tools/src/config.rs, tools/src/format.rs
Need this for Servo and WebKit.
=> config: Don't hardcode gecko-dev commit links.

clang-plugin/MozsearchIndexer.cpp
Will merge after https://treeherder.mozilla.org/#/jobs?repo=try&revision=09b89c1684c660cf9496e5765ca6ef0ebdd97429&searchStr=searchfox is green. I verified these changes build in the vagrant machine. (But we should really update to a newer clang in the provisioning code)
=> Resync MozsearchIndexer.cpp after changes in bug 1501821

tools/Cargo.lock, tools/Cargo.toml, tools/src/blame.rs, tools/src/config.rs, tools/src/format.rs
I haven't yet had the time to actually build this locally, so it's very very likely that there are build errors in it. I don't currently have docker set up & my system openssl is 0.0.1 versions too new for the openssl-sys crate.
The main place here where I'm expecting a compilation error needs to be fixed are in `lookup`, where I call `realname.as_ref().unwrap_or(name)`. The type of `realname` is `&Option<String>` while the type of `name` is `&str`, so a `.map(|&x| &x[..])` may need to be added before the `unwrap_or` to make the deref explicit. 
I whipped this together because it seems like `libgit2` is pretty slow to ship new releases, so while @emilio and landed mailmap support upstream a while ago, it's not available in any release yet. For mozsearch we don't need quite as robust …
=> Add mailmap support

tests/tests/files/simple.cpp, tests/tests/files/simple.rs, tests/tests/files/test_rust_dependency/src/lib.rs, tools/Cargo.lock, tools/src/bin/rust-indexer.rs
This allows to jump from the rust call-site to the C++ definition, for example.
=> rust-indexer: Improve handling for extern functions implemented in C++.

static/css/main.css, static/css/mozsearch.css, static/js/context-menu.js, tools/src/format.rs
This fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1510318 and
https://bugzilla.mozilla.org/show_bug.cgi?id=1430112.
There's a chance that this highlights too much for C++, but from my testing it
looks ok, and we can always filter symbols / add more heuristics if needed.
I removed some unused [data-kind] rules while I was at it.
=> highlighter: Add support for multiple symbols per identifier.

static/js/context-menu.js
The findReferences code returns any tokens anywhere on the patch that
share at least one symbol with the target token. This can sometimes
result in a superset of what we actually want, because "hidden" symbols
(ones that the user doesn't necessarily care about but that get
attributed to tokens) can result in spurious matches.
This patch augments the filtering to ensure only tokens with the same
user-visible string get matched. This is not a perfect fix since it's
still possible to have tokens with the same user-visible strings and
symbols in separate scopes (e.g. different functions) that will get
co-highlighted. But it helps with some cases.
=> Bug 1498024 - Further filter the matching tokens by textContent.

static/js/blame.js, tools/src/bin/output-file.rs, tools/src/blame.rs, tools/src/config.rs, tools/src/format.rs, tools/src/git_ops.rs, tools/src/lib.rs
Add code to "skip over" changesets listed in a .git-blame-ignore-revs file. The skipped changesets are still sent to the frontend, but are hidden by default. The user can expand to show them if desired.
=> Bug 1507923 - Add "hyperblame" functionality

clang-plugin/MozsearchIndexer.cpp
I'm not sure whether we're interested in supporting this, but we probably
shouldn't be.
=> indexer: Remove code for clang <6.

clang-plugin/MozsearchIndexer.cpp
CLANG_VERSION_FULL is a macro that lives in mozilla-central, so it doesn't exist
while building the indexer. Just use the macro clang provides.
=> indexer: Fix the build with trunk clang and with assertions enabled.

static/js/panel.js
This patch binds the result of `$('#panel-accel-enable')[0];` to a variable panelAccelEnable
and only adds an event listener if the variable is truthy.
I'm also changing further uses of the jQuery function to the newly bound variable.
https://bugzilla.mozilla.org/show_bug.cgi?id=1514170
=> Bug 1514170 - dont addEventlistener to undefined

Makefile, scripts/output-dir.js, tests/tests/files/simple.rs, tools/src/bin/rust-indexer.rs, tools/src/format.rs
The commas cause problems, see https://bugzilla.mozilla.org/show_bug.cgi?id=1512044
This also adds some Makefile goop to be able to test changes more easily. I ran the patch on the test repo locally and it fixed the issue with the testcase. I kicked off a push on the `kats` channel which I'll verify in the morning.
=> Normalize away commas from rust symbols

tools/src/format.rs
This seems to be a silly error where we don't advance cur_datum properly.
We advance it to the correct line but fail to advance it over to the
correct column. So in some cases we don't find the analysis data for the
token, even though it is present in the dataset.
We have scenarios in simple.rs that are fixed by this patch, and I've pushed a test run to the `kats` channel to verify it fixes bug 1515107.
=> Bug 1515107 - Advance the cur_datum across columns as well

router/router.py
I suspect the redundant checks are optimizations, but I'm submitting the PR just in case.
=> Remove redundant checks

tools/src/languages.rs
Some GV's tests and mobile projects use Kotlin, so we should format Kotlin's source files.
Kotlin lang's keyword list is the following URL.
- http://kotlinlang.org/docs/reference/keyword-reference.html
=> Add Kotlin support

infrastructure/indexer-provision.sh, infrastructure/web-server-provision.sh, router/codesearch.py, scripts/build-codesearch.py
This is currently deployed to kats.searchfox.org. Note that this requires reprovisioning the AMIs.
=> Update livegrep for native submodule support

infrastructure/indexer-provision.sh
`vagrant up` fails without this reordering because `add-apt-repository` is
attempted to be used before it's installed as part of the
`software-properties-common` package.
=> Bug 1545956 - Reorder apt install order so add-apt-repository is available. r=kats

clang-plugin/Makefile, infrastructure/indexer-provision.sh
Upgrades to clang-8.  There have been some packaging name changes, with
places where "6.0" was previously used now just being "8".  I added a variable
for the version, but if the naming scheme changes again, that doesn't really
save any effort.  I bumped the alternatives priority so that if someone runs
this on an already-provisioned vagrant, they should get the right thing.
The `add-apt-repository ppa:git-core/ppa` was prompting me when I manually
ran the provisioner script, so I added a `-y`.  (Presumably when run
non-interactively without a pty the prompt wasn't happening, or the fact that
I was running this on an already-provisioned vagrant.)
I also forced the clang-plugin Makefile to use "clang++" since my vagrant
instance was defaulting to g++ (which was really g++, not clang++) if …
=> Bug 1550236 - Upgrade clang in vagrant build to clang 8. r=kats

.gitignore, docs/a11y.md, static/css/mozsearch.css, static/js/blame.js, static/js/code-highlighter.js, tests/config.json, tests/searchfox/setup, tools/src/format.rs, tools/src/output.rs
This also includes elements to fix bug 1557139.
This patch encompasses these changes (which can be split out):
- Have the test 'searchfox' repo generate and use blame information.  It's a
bit difficult to iterate on blame and diff display without blame and the
ability to thereby derive diff links.  I've modified the test searchfox
setup script to run blame generation for the self-same searchfox repo when
indexer setup is run.  The major downside to this is that if you have any
local changes to the searchfox codebase that haven't been integrated into
the blame data, then output-file may panic when the line counts aren't the
same.  This means an iteration loop looks like:
- outside the vagrant VM
- `git commit -a --amend --reset-author`
- inside the vagrant VM
- …
=> Bug 1511275 - Unify line numbers and source code listings in DOM. r=kats

static/js/dxr.js
So this is just the hack I made on the web-server today to stop the dxr scrollIntoView logic from interfering with the code-highlighter.js logic on load.  In theory there might be some regressions for this for people who use the line highlighting mechanism and forward/backward on the browser somehow.  But since most "go to define" traversals result in separate windows/documents, I'm not sure if that's actually anyone.
Feel free to merge if you think having the hack permanently in place for now is better than not.
=> Bug 1558616 - Temporary hack fix from IRC. r=kats

static/css/mozsearch.css
Test case: https://searchfox.org/mozilla-central/rev/227f5329f75bd8b16c6b146a7414598a420260cb/toolkit/locales/en-US/toolkit/about/aboutAddons.ftl#141
Before patch: Line is shifted to the left.
After patch: Line is at its normal place. The line number is happily reunited with the column of other line numbers.
=> Bug 1558970 - Ensure that the number before a long line is not shrunk

docs/a11y.md, static/css/mozsearch.css, static/js/code-highlighter.js, tools/src/format.rs
I've tested with NVDA on Windows Firefox release and copy-and-paste worked as expected as did NVDA.  (Although Firefox locked up for a long time producing the accessibility data on just MozsearchIndexer.cpp... :frowning_face: )
=> Bug 1558942 - Stop using generated content for line numbers in favor of user-select: none/-moz-user-select:none. r=kats

static/js/code-highlighter.js
I failed to include this in my commit that I just landed due to hg/git muscle
memory confusion.
=> Bug 1558942 - review fix to use textContent. r=kats

static/css/mozsearch.css, static/js/code-highlighter.js, static/js/dxr.js
- Restores the .line-number containing block necessary for scrollIntoView to
work.
- Documents the position: relative/absolute instances in the CSS that I
currently understand enough to document, possibly because I recently
regressed them.
- Improve the documentation on scrollIntoView.
- Update the .goto padding to be based on our current position: sticky sizing.
The math works out to -156 so this is actually a reduction right now.
- Remove the redundant manual JS scrolling that happens on startup.
=> Bug 1558616 - Fix scrolling logic. r=kats

tools/Cargo.lock, tools/Cargo.toml
The fix actually showed up in getopts 0.2.17 but it seems equally as reasonable to take 0.2.19.  Feel free to push a change that just does 0.2.17 if needed, etc.
=> Bug 1571295 - update getops to fix mutable borrow breakage. r=emilio

scripts/js-analyze.js, tests/tests/files/some_javascript.js
Bug 1499448 added support for the new ES class field syntax.  It also included
some provisional support for private fields which were largely disabled in
bug 1559269.
See https://github.com/tc39/proposal-class-fields for info on the spec.
This patch:
- Corrects ClassMethod processing to also generate "class#method" in addition to
just "#method".  While figuring out how to implement ClassField I realized
that we already did this for ObjectExpression/ObjectPattern, but not
ClassMethod.  Our context would be right, but we'd be missing cross-reference
symbols for the qualified name.
- Makes us process ClassField nodes similarly to how we process ObjectPattern.
We emit an unqualified and qualified name (similar to the corrected
ClassMethod), and we process the "init" (compare with prop's …
=> Bug 1577060 - Support ClassField nodes. r=kats,emilio

scripts/read-json.py
This worked out okay in try runs, and I think it's beneficial for us to be able to control indexing ordering via the JSON config file.
Note that I'd initially missed the need to handle OrderedDict in the second hunk, which gave rise to the realization that our Exception raising code was not legit.
=> Bug 1579428 - Update read-json.py to maintain object/dictionary ordering. r=kats

infrastructure/aws/trigger_indexer.py
As discussed at https://bugzilla.mozilla.org/show_bug.cgi?id=1567724#c19 it
appears that the indexing process is somewhat RAM limited.  While the machine
type is slightly more expensive ($0.452/hr vs. $0.384/hr is $0.068/hr), there
is at least a 40-minute runtime savings on output.sh which provides for 4.5
hours of the fancier machine type directly.  Additionally, we've been
thinking about adding the "ash" branch which would likely do even worse under
the existing c5d scheme if added to the mozilla-releases.json.
More significantly, I think we're pretty close to OOM's in the
mozilla-releases.json run and the human opportunity costs to re-triggering
those runs exceed the price differential by several orders of magnitude.
This will need the lambda functions to be regenerated to actually …
=> Bug 1579428 - Switch to m5d.2xlarge machines due to RAM contention. r=kats

infrastructure/web-server-setup.sh, tests/config.json
I think I did the shell stuff right.  It at least did the right thing locally, but please do sanity-check.  http://tldp.org/LDP/abs/html/comparison-ops.html says that "-o" does not short-circuit versus `||` which really doesn't matter either way in this case, but I never know whether it's better to avoid bash-isms if possible or what.
=> Bug 1580266 - explicitly specify the default tree for help.html purposes. r=kats

scripts/nginx-setup.py
nginx is able to provide us with etags and last-modified times for our static
source files which allows for efficient revalidation, but everything else we
serve is dynamic and currently isn't etag aware.  Because of this, we need
some time-based expiration for at least dynamic stuff.  I've arbitrarily
chosen 2 minutes, but this is motivated primarily by the development cycle.
That said, it's unlikely this will pose a major problem.
=> Bug 1558589 - better nginx caching directives. r=kats

tools/Cargo.lock
This is just from running "cargo update".  Indexing worked locally in vagrant after doing this.
=> Bug 1585277 - Update Cargo.lock for rustc 1.40. r=emilio

infrastructure/aws/build-lambda-indexer-start.sh, infrastructure/indexer-run.sh, infrastructure/indexer-setup.sh, infrastructure/web-server-run.sh, infrastructure/web-server-setup.sh, scripts/generate-config.sh
When you're in a worktree, the `.git` thing that gets to `/vagrant` is not the
repo itself but a reference like:
> gitdir: /home/emilio/src/moz/mozsearch/.git/worktrees/mozsearch-ubuntu-up
Which is obviously _not_ in the /vagrant directory, and thus git operations fail
from inside the virtual machine.
=> Make some scripts work when ran from the VM in a git worktree.

scripts/rust-analyze.sh
This patch combined with the mozsearch-mozilla patch causes us to process the rust save-analysis data into the per-platform analysis directories, and then merge the results.
With these changes, I got a config.json run to seem to complete happily where:
- https://asuth.searchfox.org/mozilla-central/source/servo/components/style/values/specified/text.rs is no longer broken.  (Note that I've just triggered a mozilla-releases.json indexer run, so while the webserver for mozilla-central will stay up, the load balancer config will end up shifting away and the URL will become a 503 or whatever.  Feel free to inspect via ssh or reconfigure the load balancers if desired.)
- We end up with an analysis file in the expected place that looks right.
- Because our scripts still delete the per-platform …
=> Bug 1583031 - Have rust analysis run (optionally) per-platform

README.md, infrastructure/indexer-provision.sh, infrastructure/vagrant/indexer-provision.sh
Since trunk is broken, I'm going to speculatively land this and the other mozsearch-mozilla fix and then attempt try runs directly from lambda.  I'll ask for after-the-fact review on this and any additional fix-ups I need to perform.
=> Bug 1595492 - switch over to new taskcluster CI.

README.md, Vagrantfile, docs/aws.md, infrastructure/aws/index.sh, infrastructure/aws/trigger-provision.py, infrastructure/aws/trigger-web-server.py, infrastructure/aws/trigger_indexer.py, infrastructure/aws/web-serve.sh, infrastructure/aws/web-server-provision.sh, infrastructure/indexer-provision.sh, infrastructure/web-server-provision.sh
This is Emilio's WIP commit (the commit summary slightly changed) from https://github.com/mozsearch/mozsearch/pull/248 plus an additional commit with:
- Updated documentation.  I probably missed some things, but I think I got at least some of the obvious ones!
- Enhancements to the NVME logic.  My hardcoded paths broke immediately.  Thankfully on 18.04 the nvme commands can dump JSON output and `jq` can let us filter it to get the information we need.  We no longer need to do `lsblk` because it's basically the same as the `nvme` calls.
- We are able to match based on volume id and just the type of volume (instance disk versus EBS).
- In theory we could also match by the pre-NVME device/mountpoint where the EBS attach would have happened from the "vs" vendor extended info data, but I …
=> Bug 1601451 - Move to Ubuntu 18.04 LTS.

infrastructure/indexer-provision.sh, infrastructure/indexer-update.sh, infrastructure/web-server-provision.sh, infrastructure/web-server-update.sh
Move from having high-churn dependency updates (rust/spidermonkey) and build
steps being permanently baked into the provisioning-generated `update.sh` and
instead have them live in the mozsearch repo.  This makes it easier for
branches to try things without needing to re-provision.
=> Bug 1603193 - Move bulk of VM update steps into extensible scripts. r=kats

infrastructure/indexer-provision.sh, infrastructure/web-server-provision.sh
Running pip install with an unconstrainted pygit2 installed pygit2 1.0.0
which needed a more recent version of libgit2 and which also was incompatible
with Python2.7 (but only said the former, not the latter).
This change:
- Forces us to specifically install the last release of pygit2 prior to 1.0.0.
- Upgrades our libgit2 version to the most recent version.  I don't think this
is strictly necessary with pygit2 at an older version, but I already had done
the script changes necessary and things built correctly.  (And there doesn't
seem to be an advantage to staying on an older version, especially given that
when we do upgrade to pygit2 1.0.0 we will need an 0.28.x series release of
libgit2 anyways.
=> Bug 1603193 - pygit2 bustage fix. a=bustage

tools/src/bin/output-file.rs
=> Bug 1605386 - Add 'l' prefix to HG Web fragment for line numbers

blame/transform-repo.py, infrastructure/indexer-provision.sh, router/crossrefs.py, router/identifiers.py, tools/src/file_format/identifiers.rs
With these patches I'm able to index an hg-only repo (read: `mozilla-build`) using git-cinnabar instead of needing a full-blown git mirror.
=> Add some basic git-cinnabar support.

tools/src/tokenize.rs
Changes in bug 1588908 surfaced an existing logic problem in regexp scanning
that assumes the text to be tokenized is sufficiently well-formed so that
scanning will end before we run out of string.  This corrects that issue.
I've tested this locally on the indexer and this corrects the problem, with `RUST_LOG=debug` reporting 3 separate invalid regexp literals for the "mozilla-mobile" "focus-android/app/src/androidTest/assets/ad.html" file.
I'm going to land this as a bustage-fix with after-the-fact review because it's a weekend at the end of a long holiday period and I think I've properly identified what's going on, but there's probably more to do, if only to add some more comments to the source.
=> Bug 1607031 - Make regexp scanning stop at end of string. a=bustage-fix

infrastructure/indexer-provision.sh
There isn't actually a rush to land this.  I'd probably wait until the end of the week to land and re-provision because this seems like the kind of thing that inevitably will cause breakage.  But I need it for the fancy branch, so I thought I'd prepare it.
=> Bug 1607109 - Upgrade searchfox indexer to LLVM 9/clang 9. r=emilio

static/js/blame.js
The height here is not used at all.
This shows up in the profiles from bug 1611729.
=> blame: Avoid silly forced layout.

infrastructure/indexer-provision.sh
Provisioning failed on the checkout because it was in the wrong dir.
=> reorder git-cinnabar `pushd` to be correct

Vagrantfile
Although our intent when adding libvirt was to add the NFS mount only in the
case of libvirt and not for virtualbox, we did not, so it was also being
added for virtualbox on OS X which did not work.  This corrects the syntax to
only enable NFS on libvirt.
This also has a ride-along of updating to the most recent released image
version, primarily because I tried this as part of my troubleshooting before
realizing what was going on, but it seems like an advantageous change.
=> Make NFS settings libvirt-specific

Vagrantfile
This causes the VirtualBox UI on OS X to say "Shared Folders: 1" instead of "Shared Folders: 0", which was the case without this change.  (It also was the case for removing the libvirt directives from the file.)  This shouldn't technically be necessary based on the docs, but it's not clear what's up.
Provisioning is still ongoing, but doing `vagrant ssh` while provisioning is ongoing allowed me to see that `/vagrant` was mounted and visible, so I'm going to insta-merge this.
=> explicitly specify shared folder for virtualbox

tools/Cargo.lock, tools/Cargo.toml, tools/malloc_size_of/Cargo.toml, tools/malloc_size_of/LICENSE-APACHE, tools/malloc_size_of/LICENSE-MIT, tools/malloc_size_of/lib.rs, tools/src/bin/web-server.rs, tools/src/config.rs, tools/src/lib.rs
This is where I got the numbers at https://bugzilla.mozilla.org/show_bug.cgi?id=1464297#c14 from.  In general, it seems useful for us to be able to understand where our runtime memory usage lives, so I think this is probably worth landing.  Note that I treat the git2 internals other than the Oids as 0 memory usage.  That's obviously not accurate.  I think jemalloc can tell us the total aggregate allocated memory, so we could certainly try and do some math to note what we explicitly can track versus the overall allocation size.  (And we can also sample the heap sizes at different points while the program is still single-threaded.)  I'm not really wedded to landing this, I just don't want to have to implement it again in the future ;)
There's some more info in the commit messages but the …
=> Baby steps for web-server.rs knowing its memory usage

README.md, infrastructure/indexer-setup.sh
Although the KEEP_WORKING variable is meant to be used to preserve the current working directory, an user may rerun "indexer-setup.sh" without defining this variable, causing the removal of all contents inside the WORKING directory (repository checkout, blame information, etc).
This patch asks users to confirm whether they would like to remove the contents of WORKING directory, when KEEP_WORKING is not defined.
=> Show up message about KEEP_WORKING variable

static/css/mozsearch.css, static/js/code-highlighter.js
This is sad, but needed to work around https://bugs.chromium.org/p/chromium/issues/detail?id=850685
I limited the condition to non-Firefox for now, but if you prefer, I can invert the check, to specifically target Chrome, and maybe even specifically Linux.
=> Bug 1616104 - Move line numbers out of X selection on Chrome

infrastructure/aws/index.sh, infrastructure/aws/main.sh, infrastructure/aws/make-crontab.py
This set of patches fixes an error in make-crontab.py and also ensures that similar regressions get properly caught in the future.
=> Robustify index.sh/main.sh

infrastructure/web-server-setup.sh, scripts/nginx-setup.py
Expose the analysis files as "raw-analysis" and the "repo-files" and
"objdir-files" under "file-lists".  This is intended to make debugging
investigations easier as well as to enable extraction of per-file and
per-directory information without having to scrape the HTML output of
output-file.
=> Bug 1627339 - Expose raw analysis files and {repo,objdir}-files. r=kats

README.md, Vagrantfile, docs/newrepo.md
The remaining places that mention port 8001 in the codebase are:
- Places related to web-server.rs which continues to bind to local port 8001,
specifically:
- `tools/src/bin/web-server.rs`: The web server itself.
- `scripts/nginx-setup.py`: Establishing the nginx mapping to the web server.
- The un-maintained awesomebar webextension that looks like it was pointing
directly at web-server.rs for searchfox run locally outside of the VM.  (Or
for a browser run inside the VM.)
=> Bug 1627129 - Switch from port 8001 to 16995 for vagrant port forwarding. r=kats

scripts/mkdirs.sh, tests/tests/build, tests/tests/setup
- Remove a totally useless rm -f command that deletes a dir that is never created
- Ensure the compiler env vars that are written don't accumulate on rebuilds
- Delete dirs that contain data generated per indexing run, so that we don't have
leftover stale data mingling with new data on rebuilds.
=> Bug 1627814 - Make rebuilding repos more idempotent

static/css/mozsearch.css, static/js/blame.js, tools/src/format.rs
With the goal of making it faster.
Right now the blame popup causes pretty expensive reflows, because it's
hosted inside the line strip.
This is completely unnecessary though, so this patch saves us some
per-line markup and makes it a top-level absolutely-positioned element,
and positions it dynamically.
This also uses aria-owns so that the accessibility semantics are the
same as before.
=> Rewrite and simplify blame popup.

static/js/blame.js
I live-edited the dev web-server to test this, so the patch is applied there and you can try it out if you want.
Also note that if you test in Fenix you may run into https://github.com/mozilla-mobile/fenix/issues/8779 which reopens the blame popup after scrolling. Doesn't happen in Fennec, and I intend to track down and fix the bug in Fenix soonish.
=> Bug 1619751 - Pin blame popup on click, dismiss on scroll or click elsewhere.

tools/Cargo.lock, tools/Cargo.toml, tools/src/bin/build-blame.rs
This is better than setting the env var on every call site
=> Bug 1627532 - Turn on info logging by default in build-blame

scripts/idl-analyze.py
This is kinda hacky but should be ok for the forseeable future.
I'm running a test of this now.
=> Make idl-analyze.sh work with both old and new versions of xpidl.py

router/router.py
`text=True` can only be used in python3.7 and up, but we're on 3.6. So we should
use the equivalent `universal_newlines=True` argument instead. Also, when catching
errors thrown from subprocess.check_output, let unexpected errors propagate
so we get a stack in the log and generally more obvious failure. Keep catching
the "expected" failure (non-zero return code from process).
=> Bug 1639631 - Fix calls to subprocess.check_output.

static/js/context-menu.js
If we're on a text node that ends on a newline, we'd incorrectly move
the start towards the left and keep the end at the newline position.
=> Bug 1639747 - Fix context-menu to not detect words at the end of lines.

infrastructure/aws/attach-index-volume.py, infrastructure/aws/terminate-indexer.py, infrastructure/aws/trigger_indexer.py
If we have an existing "running" indexer for a channel and we're spawning a new one for that channel, the old one shouldn't be needed any more, so we can terminate it. This makes it nicer from a dev point of view, if e.g. you uncover a mistake just after kicking off an indexer, because you can just start a new one and the old one will get terminated automatically.
It also takes care of the case where release indexers fail to shut down because of an error early during the update script (see bug 1471993). In this scenario, the next day's lambda job will terminate the running indexer as a failsafe, and so the indexer should not be kicking around for more than 24 hours at the outside.
As a bonus, this sets the TerminateOnDeletion flag for index volumes so manual deletion of those is …
=> Delete old running indexers when spawning new ones

tools/src/bin/rust-indexer.rs
The r=kats is from the primary review where this comment change was
suggested.  I failed to save all buffers when preparing the patch fixes.
=> Bug 1593833 - comment fix that accidentally didn't get landed. r=kats

Vagrantfile, scripts/mkindex.sh, scripts/rust-analyze.sh, tools/src/bin/rust-indexer.rs
Note that there's also a commit in here for https://bugzilla.mozilla.org/show_bug.cgi?id=1607376 to fix the NFS mount.  I can land that separately but it was necessary for testing and I didn't want to risk making a foolish git mistake.
This eliminates the need to think of the rustlib source as a separate directory tree.  The mozsearch-mozilla patch puts the source under `generated-$platform/__RUST__` to begin with which eliminates the need for any extra mapping and enables the normal collapsing process to do its thing.
The full config.json run is up on https://asuth.searchfox.org/ with the check being for https://asuth.searchfox.org/mozilla-central/source/__GENERATED__/__RUST__/liballoc/collections/btree/map.rs noting that I guess we only get analysis for things that get used, as one can …
=> Bug 1641079 - Make `__GENERATED__/__RUST__` work.

infrastructure/aws/trigger-web-server.py
The only time there should be unattached index volumes are (a) immediately
after creation and before attaching to the indexer, and (b) while detaching
from the indexer and reattaching to the web-server. These are both very short
periods of time, so if we find stray index volumes after deleting old web-servers
that's likely a problem. Report these as warnings for further investigation.
=> Bug 1640915 - Report stray index volumes.

scripts/js-analyze.js
This has absolutely not been tested but it's a very small change.
=> Bug 1641845 - js-analyze.js: Rename Symbol constructor to SymbolTable.Symbol.

infrastructure/aws/make-crontab.py
The releases indexer is now doing beta, release, esr68, and esr78, all
of which are massive and so it takes more than 6 hours to do it all.
=> Bug 1646118 - Increase crontab time

tools/Cargo.lock, tools/Cargo.toml, tools/src/bin/build-blame.rs
This series of patches separates the work that build-blame does into "compute" and "writing to repo". The compute step is then parallelized across n-1 threads, leaving 1 thread for the "writing to repo". If n=2 the bottleneck is the compute side, but on the indexer we generally run with n=8 which makes the writing to repo part the bottleneck. So some additional patches then reduce the amount of time spent in the get_path function which was showing up as expensive in profiles. There's still more that can/should be done to optimize the writing thread, but I need to go do other things now.
Note that I initially parallelized using rayon, but it turns out that creating and destroying the `git2::Repository` objects is quite expensive (and they can't be shared across threads) so I wanted each …
=> Optimize the build-blame tool

tools/Cargo.lock, tools/Cargo.toml, tools/src/bin/build-blame.rs
Instead of writing the blame commits into the blame repo as loose objects,
which take up a lot of disk space, they now get written into a mempack backend
first. The mempack backend is an in-memory store that can be flushed directly
into a packfile which is much more space-efficient, specially during initial
blame repo creation.
=> Bug 1653245 - Use mempack to write packfiles instead of loose objects.

router/router.py, static/js/dxr.js, tests/tests/files/third_party/a_file
Replaces #358 since I can't push to that branch. This is the same patch (and retains authorship) but tweaks the order of sections in the results page, changes a pair of " quotes to ' quotes for consistency, and adds a third_party/ folder to the test repo for testing purposes.
=> Add some support for classifying third-party code.

Vagrantfile, infrastructure/vagrant/indexer-provision.sh
This also provides the hash at which provisioning last happened so people can manually diff the provisioning scripts and apply changes if they want to.
=> Fail early on reprovisioning attempts

static/js/dxr.js
This prevents URLs from overriding the user's saved default behaviour,
and also fixes the reported bug where the checkbox state doesn't match
the actual results.
=> Bug 1656009 - Refine the case-sensitivity checkbox behaviour

scripts/lib.py
Based on the code later in this function, it seems clear that the intent
is to capture stderr into the `stderr` variable. However that's not
actually happening. This patch corrects that and makes it happen.
A beneficial side-effect is that the codesearch warnings about ignoring
too-big files now don't end up in the indexer log and so won't trigger
warning emails.
=> Bug 1671640 - Ensure stderr is properly captured

infrastructure/aws/trigger-web-server.py
I forgot that we have the release channel hard-coded in one more spot,
where we decide to terminate the old web-server. We have code to
special-case the release (now release1) channel so that we can roll
back to a day-old web server for m-c in case of emergency. This patch
updates the channel name there so we preserve the old behaviour.
=> Bug 1670314 - Followup for release channel rename

scripts/compress-outputs.sh
The /raw-analysis/ URLs also use try_files, and therefore need the zero-length
non-gzip'd files to exist.
=> Bug 1674616 - Fix raw-analysis URL endpoint.

static/css/mozsearch.css, static/js/blame.js
Instead of using the touch-generated mouse events to control the blame popup,
add touch event listeners to manage it directly. This patch allows the user
to drag their finger around on the blame strip, and have the blame popup update
to whatever is under the cursor. The touch-action CSS property is used to
disable browser-based panning while the finger is being dragged in such a
manner. This UX makes it somewhat easier to trigger the blame popup for a
given line using touch, where the finger is less precise of a pointer than
a mouse cursor. When triggered via touch, the blame popup remains visible
until it is dismissed by scrolling or "clicking" (i.e. tapping) elsewhere.
=> Bug 1674601 - Make the blame/coverage strips a bit more touch friendly

infrastructure/indexer-provision.sh, infrastructure/web-server-provision.sh
snaps are evil because they auto-update all by themselves, potentially
breaking downstream users.
=> Bug 1684371 - Update provisioner to get yq from pip instead of the snap

infrastructure/indexer-provision.sh, infrastructure/web-server-provision.sh
The ambiguity can arise if there is a file/folder in the config
repo with the same name as the branch we're trying to check out. Adding
the double-dash resolves the ambiguity.
=> Bug 1684471 - Make checkout command unambiguous in some cases.

tools/Cargo.lock, tools/Cargo.toml, tools/malloc_size_of/Cargo.toml, tools/src/bin/build-blame.rs
This switches the build-blame tool to write to a git-fast-import stream instead of using the libgit2 API. This improves performance and dramatically reduces temporary disk usage requirements.
=> Switch build-blame to using git-fast-import

static/js/context-menu.js
Curiously enough this works both in current-ish Firefoxes and Chrome, but is it really legal JS?
=> Small context menu event handling fix

infrastructure/aws/index.sh
updatedb can end up tying up the indexing partition in a bad way, so disable
it and all the other daily and weekly cron jobs that we weren't actually
running until we just recently started trying to run jobs for the 22:00 UTC
mozilla-central nightly.
=> Bug 1687185 - Disable daily cron jobs. r=kats

scripts/nginx-setup.py, tools/src/bin/web-server.rs
This also adds $request_time to the nginx HTTP log output which indicates how
long the request took in seconds with a millisecond resolution.
I checked locally that I can see the extra logging and that the web-server process goes from 4 threads to 6 threads.  I'm assuming the other threads are interesting support threads that don't feel the name to give themselves interesting names.
=> Bug 1693352 - Increase web-server.rs thread count to 4.

Vagrantfile, infrastructure/aws/trigger-provision.py, infrastructure/indexer-provision.sh, infrastructure/web-server-provision.sh
The primary motivation is to get a newer version of curl with relevant
bugfixes.  The secondary motivation is that our lives are made simpler
by staying up to date with releases.
The only necessary change for the Vagrant VM was to remove the GNU
parallel citation workaround, see
https://bugzilla.mozilla.org/show_bug.cgi?id=1694210#c1
Other notes not part of the commit message:
- I've only run this locally on Vagrant libvirt so far.  I would ideally like to merge this and then do the provisioning so I can provision from master rather than on my own branch.
- I did look at switching to official Ubuntu images for vagrant, but if you run the search https://app.vagrantup.com/boxes/search?utf8=%E2%9C%93&sort=downloads&provider=&q=ubuntu+20.04 you'll find that the official "ubuntu/focal64" only …
=> Bug 1694210 - Update VMs to Ubuntu 20.04 LTS

docs/aws.md, infrastructure/aws/indexer-provision.sh, infrastructure/aws/trigger-web-server.py, infrastructure/aws/trigger_indexer.py
The VM triggering scripts need to know the revised AMI name that we're
going to use.  Also, during provisioning, the awslogs-agent-setup.py
script failed to execute properly because the embedded hash-bang was
for "python", so we now explicitly run it with python2 because our
python3 is too new.
After this I'll also regenerate the lambda jobs.
=> Bug 1694210 - Update AMI image name refs, use python2 for logs

docs/aws.md, infrastructure/aws/build-lambda-indexer-start.sh
On my machine, the current virtualenv steps resulted in certifi
version 2019.11.28 being installed into the virtualenv as created by
the lambda.zip creation process.  The resulting lambda jobs failed to
authenticate the AWS server.
This patch is a hack in the sense that I want the lambda jobs to be
happy again (and they now are, with the changes in this patch), but I'm
not sure it's the right answer.  My thoughts here were:
1. Validating certificates seems good, why not.
2. Upgrading certifi makes the lambda job work.
By default, virtualenv uses a seeding mechanism to install things beyond
just python / python3 / python 3.N links into the env/bin directory.
This is documented at
https://virtualenv.pypa.io/en/latest/user_guide.html but I haven't
fully processed it in detail.
The short …
=> Bug 1694210 - Explicitly use up-to-date version of certifi

static/js/code-highlighter.js
The nesting container is rooted at the stuck line's original offset, so
scrolling up by the difference between the two correctly jumps to the line
number that was clicked.
=> Bug 1637010 - Fix how the scroll position is computed for position:sticky line clicks

static/css/mozsearch.css
16px is not guaranteed to fill the line (and it fact it does not if you use a big font-size, like webkit-search.igalia.com, or if you're zoomed in in some platforms).
=> Bug 1695242 - Don't hard-code blame strip box heights

static/js/code-highlighter.js
Otherwise rounding error accumulates and random stuff happens.
=> code-hightlighter: Ensure we account for float height when computing whether something is stuck.

infrastructure/indexer-provision.sh, tests/tests/build
I tested this with `vagrant destroy` followed by `vagrant up` followed by (in the VM via `vagrant ssh`) `cd /vagrant; make build-test-repo`.  Note that I did experience weirdness with a missing symbol on the ItaniumMangleContext during clang analysis which I believe ended up being due to the "make" in /vagrant/clang-plugin deciding not to actually rebuild things under clang 11 because we didn't express a dependency on the compiler and those object files/the binary existing outside of the VM itself because we don't use a bindir.  So if you're testing and not using a fresh checkout, you may need to first do a "make clean" in /vagrant/clang-plugin.
I'll plan to re-provision the indexer once this lands even though it hopefully doesn't matter.
=> Bug 1698236 - Use clang 11 and build c++17-style

static/js/search.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1558691 is a follow-up to https://bugzilla.mozilla.org/show_bug.cgi?id=1511279 and its https://github.com/mozsearch/mozsearch/pull/185 
I added some extra comments in the loop as I was getting the lay of the land because I don't find our "pathkind" and "qkind" terms self-explanatory.  For hand-waving purposes, my rationale for going with the span proposal over a proper h3 is that I expect we might overhaul this all in the near future.
=> Bug 1558691 - Make the search result headers headings

scripts/weblog-analyze.sh
Example of output can be found in the bug.
This depends on https://github.com/rcoh/angle-grinder which can be installed
via `cargo install ag`.  My current assumption is that this is being run
locally, not in a VM, by someone who has already done this.
I'm not sure I have a longer term strategy for this, I just wanted to archive
the results of my investigation in a way that's slightly better than searching
for a bugzilla comment and then copying and pasting from that.
=> Bug 1701848 - Add script to aid in analyzing searchfox web-server dynamic query performance

router/codesearch.py, router/router.py, static/css/mozsearch.css, static/js/search.js
This implements an undocumented "context:N" search directive understood by
the parser (if it precedes the search query proper, as-is required by the
implementation of parse_search) that we propagate to livegrep which in turn
generously returns the context for us.
I'm calling this secret because I don't think the UX as provided by this
patch is appropriate for a supported feature, but I think this could be
useful for experimentation and iteration.  In particular, in this patch:
- Typing out context:N at the start of the search but having things not work
if you put it at the end as an afterthought isn't great.
- I don't think adding a separate form input for lines of context is a great
initial choice either.
- This doesn't work with any of the semantic responses, and doing so is both …
=> Bug 1414954 - Add secret codesearch support for getting lines of context.

router/codesearch.py
:kats noticed that the context_before lines are reversed (thank you!)
Also, the livegrep server assumes a default context_lines of 3 and cannot be
convinced to provide 0 lines of context if that default is non-zero, so we
now also explicitly provide a directive of 0 lines of context when spawning.
=> Bug 1414954 - fix context reversal and override default livegrep context_lines

tools/Cargo.lock, tools/Cargo.toml, tools/src/abstract_server/local_index.rs, tools/src/abstract_server/mod.rs, tools/src/abstract_server/remote_server.rs, tools/src/abstract_server/server_interface.rs, tools/src/bin/searchfox-tool.rs, tools/src/cmd_pipeline/builder.rs, tools/src/cmd_pipeline/cmd_filter_analysis.rs, tools/src/cmd_pipeline/cmd_show_html.rs, tools/src/cmd_pipeline/interface.rs, tools/src/cmd_pipeline/mod.rs, tools/src/cmd_pipeline/parser.rs, tools/src/config.rs, tools/src/format.rs, tools/src/lib.rs
This implements "searchfox-tool" a new binary, as proposed in https://bugzilla.mozilla.org/show_bug.cgi?id=1707282 but does not yet do the "insta" snapshot testing or otherwise replace the check-helper.sh mechanism yet, but I think it's quite possibly ready to do so.
Given that this is already a sizable PR and the searchfox-tool thing is already a MVP and I won't be able to get to the testing stuff until the next weekend, I'm putting this up for review now.
Here we see us filtering the contents of the (raw) analysis files to "source" (via record type) records that are a "def" (via kind) for a specific identifier "outerNS::Thing::Thing" via both local index from disk and localhost server:
```
> cargo run --bin searchfox-tool -- '--server http://localhost/ --tree tests filter-analysis …
```
=> Bug 1707282 - Implement searchfox-tool command line tool.

tools/Cargo.lock, tools/Cargo.toml, tools/malloc_size_of/Cargo.toml
Versions newer that than are affected by https://github.com//rust-lang/rust/issues/85574
which is a regression in rustc nightly. That's being reverted but for now
let's roll back a bit. We were using 0.13.15 until very recently so 0.13.17
should be safe enough.
=> Downgrade git2 to 0.13.17

tools/Cargo.lock, tools/Cargo.toml, tools/malloc_size_of/Cargo.toml, tools/src/bin/build-blame.rs
There isn't a new git2-rs release yet with the changes, so for now I'm just using the master branch head revision. Once there's a new release I'll update the Cargo.* files to use that instead.
=> Bug 1683563 - Tweak diff similarity options

scripts/crossref.sh, scripts/output.sh
We have some logic that directly references /tmp that assumes it will have
bountiful storage available, but the reality is that it does not.  In
particular, `crossref.sh` was directly sorting the ~1.6G into the /tmp dir
which is very close to the amount of free space on our `/` EBS image.
This is not meant to be the end state fix for this, so I've just corrected
the shell scripts where it's trivial to evaluate an environment variable
and failover.  I have not touched the following other files under /scripts
that have the same problem but involve python/JS:
- output-dir.js
- idl-analyze.py
- idl-analyze.sh (because of the above)
- build-codesearch.py
The simplest solution in terms of avoiding using the wrong tmp dir would
be to just make sure that the /tmp dir is actually backed by the …
=> Bug 1712578 - Use TMPDIR if defined over /tmp in shell scripts. a=bustage

infrastructure/indexer-provision.sh, infrastructure/web-server-provision.sh
We actually want this for 2 situations:
- Bug 1687016 - hg2git/git2hg hang fixes
- Bug 1716167 - to see if the cinnabar fsck becomes happier
=> Bug 1687016 - Bump cinnabar in provisioning scripts to current tip.

infrastructure/aws/indexer-provision.sh, infrastructure/aws/trigger-provision.py, infrastructure/aws/web-server-provision.sh, infrastructure/indexer-provision.sh, infrastructure/indexer-update.sh, infrastructure/web-server-provision.sh, infrastructure/web-server-update.sh
The following changes are made:
- Provisioning is given an IAM role so that the `aws` command can use it.
No role = no way to run `aws` without manually providing credentials.
- It's the same IAM role we use for indexers!
- Indexer and web server AWS provisioning resizes their root partition up
to 12 gigs from 8.  This depends on the IAM role to work.
- The indexer and web server scripts run their update scripts for side
effect of caching crates but also validating the installs.
- This happens in the core non-AWS scripts primarily so that we notice
any mistakes in changes to the provisioning process sooner when
rebuilding the VM locally.
- The update scripts and their helper scripts have been updated to handle
being run multiple times, once at provisioning, and once at spawning.
- …
=> Bug 1720037 - Run the update step when provisioning to cache crates.

infrastructure/aws/shell-setup.sh, infrastructure/aws/trigger_blame_rebuild.py, infrastructure/aws/trigger_common.py, infrastructure/aws/trigger_shell.py
This patch adds a new `trigger_shell.py` command and extracts the duplicated
logic that existed between `trigger_indexer.py` and `trigger_blame_rebuild.py`
up into `trigger_common.py` which now uses argparse as an argument parser.
The primary motivation of the cleanup because optional arguments like `setenv`
seem useful across all indexer types.  This would also be the case for things
like allowing a command-line to override.
As hinted above, we also add arguments for:
- `--setenv` intended to be used like
`--setenv TRYPUSH_REV=<40-char-rev-hash>`.
- This specific try use-case is potentially a candidate for a custom arugment
type perhaps with extra smarts.
=> Bug 1716167 - Add a way to launch an indexer shell

router/router.py
The fancy branch UI work all built on the "sorch" search endpoint which broke
with the change to python3 but I didn't notice it when rebasing because the
intent was not to surface any of the fancy UI and so it didn't get tested
(and there currently is not test coverage for router.py).
These changes are to account for changes to urlparse that were made by six
and the minor method change introducing `generateJson`.
With these fixes it should now be possible to run (outside of the VM) on a
machine with the VM running the following and see something almost useful:
```
curl -H "Accept: application/json" 'http://localhost:16995/tests/sorch?q=superhero&path=' | jq .
```
=> Bug 1641372 - router.py python3 drift fixes

clang-plugin/MozsearchIndexer.cpp, router/crossrefs.py, router/router.py, static/css/mozsearch.css, static/js/search.js, tests/tests/checks/inputs/cpp__big_cpp_cpp__structured_abstractart_beart__json, tests/tests/checks/inputs/cpp__big_cpp_cpp__structured_practicalart_beart__json, tests/tests/checks/snapshots/check_glob@cpp__big_cpp_cpp__structured_abstractart_beart__json.snap, tests/tests/checks/snapshots/check_glob@cpp__big_cpp_cpp__structured_practicalart_beart__json.snap, tests/tests/files/big_cpp.cpp
Here's a candidate fix for the regression in being able to see overridden
methods.
=> Bug 1728376 - Show related symbols in search results with search upsell

tests/tests/checks/snapshots/check_glob@cpp__atom_list_h__structured_yo_atoms_foo_string_json.snap, tests/tests/checks/snapshots/check_glob@cpp__big_cpp_cpp__def_thing__json.snap, tests/tests/checks/snapshots/check_glob@cpp__big_cpp_cpp__include_big_header__json.snap, tests/tests/checks/snapshots/check_glob@cpp__big_cpp_cpp__structured_abstractart_beart__json.snap, tests/tests/checks/snapshots/check_glob@cpp__big_cpp_cpp__structured_globalcontext__json.snap, tests/tests/checks/snapshots/check_glob@cpp__big_cpp_cpp__structured_human__json.snap, tests/tests/checks/snapshots/check_glob@cpp__big_cpp_cpp__structured_lessglobalcontext__json.snap, tests/tests/checks/snapshots/check_glob@cpp__big_cpp_cpp__structured_lessglobalcontext_decidewhethertodecide__json.snap, tests/tests/checks/snapshots/check_glob@cpp__big_cpp_cpp__structured_outercat__json.snap, tests/tests/checks/snapshots/check_glob@cpp__big_cpp_cpp__structured_practicalart_beart__json.snap, tests/tests/checks/snapshots/check_glob@cpp__big_cpp_cpp__structured_superhero__json.snap, tests/tests/checks/snapshots/check_glob@cpp__big_cpp_cpp__structured_superhero_takedamage__json.snap, tests/tests/checks/snapshots/check_glob@cpp__big_cpp_cpp__structured_thing__json.snap, tests/tests/checks/snapshots/check_glob@cpp__big_cpp_cpp__structured_thing_takedamage__json.snap, tests/tests/checks/snapshots/check_glob@cpp__big_header__def_big_header__json.snap, tests/tests/checks/snapshots/check_glob@rust__dependency__MyType__json.snap, tests/tests/checks/snapshots/check_glob@rust__generated__GeneratedType__json.snap, tests/tests/checks/snapshots/check_glob@rust__simple_rs__simple_Loader_new__json.snap, tools/Cargo.lock, tools/Cargo.toml
By default serde-json re-orders objects alphabetically because it uses a
BTreeMap under the hood.  By enabling "preserve_order" an IndexMap is
used instead which maintains the ordering.
This commit enables preserve_order because router.py emits an explicitly
ordered object dictionary and so we need that order reflected in testing.
This results in changes to all the test snapshots, so this commit only
makes this change and commits those changes.
This will have a corresponding change in mozsearch-mozilla very shortly.
=> Bug 1729178 - Enable serde_json preserve_order feature

README.md, docs/manual-indexing.md, docs/testing-checks.md
While writing the testing docs I realized there was a gap for the release
versus non-release variations, so I put an XXX in the document and want
to both address that and then update the docs once it's addressed.  I
think I may have some stashed changes to dig out that may contain the
fix needed.
I'm landing this now because I'm unlikely to have time to directly work
on this during the work week and want this information to be available
in case someone else can dig into any enhancements.
=> Bug 1728000 - Update try build and testing docs.

docs/aws.md, infrastructure/aws/channel-tool.py, infrastructure/indexer-provision.sh, infrastructure/web-server-provision.sh
Added channel-tool.py, a tool that adds the ability to:
- "list" known channels, including what pieces are set up, plus display
the instances associated with them in a pretty UI.
- "inspect" a specific known channel to see its underlying AWS
settings.
- "add" a new channel.  Under the hood this is called "ensure" because
I've tried to make it be idempotent, but "ensure" is not a command
name people would expect
- "remove" an existing channel.  Note that an unfortunate limitation is
that because of how de-registering an instance from a target group
takes time, this will error out if an instance is still in the process
of being de-registered.  At least, this happened to me when using
"move-server" (below).  Maybe if the instance is terminated, the
mechanism can handle a more prompt …
=> Bug 1730294 - channel-tool: load balancer helper

infrastructure/aws/channel-tool.py
The provisioners currently don't get marked with channel tags which made the
channel-tool.py script sad.  This makes it treat them as having a channel of
"None" which will bring joy to everyone as they assume the `None` value is
being coerced into be a `"None"` string when in fact it's just the exact
string value I chose... mainly due to VSCode automagically wrapping things in
paired quotes when you type the first quote.
=> Bug 1721037 - channel-tool should not get mad at channel-less provisioners

infrastructure/aws/indexer-provision.sh, infrastructure/aws/web-server-provision.sh
It turns out the partitioning logic needed the AWS client which needed
pip3, and the use of jq needed jq.  Also, cloudwatch needed python2,
which didn't get an alternative set up yet.
Note that we're likely to remove the CloudWatch hookup in Bug 1733733.
=> Bug 1721037 - Provisioning reordering needed more deps pre-installed.

static/css/mozsearch.css
So that they contrast better with comments and so.
=> Bug 1742820 - Dark mode: Use darker colors for highlights.

static/css/mozsearch.css
The box-shadow for stuck lines makes it hard to read the directly linked lines.
This patch adds an additional line of scroll padding so that the box-shadow can't possibly
interfere with the line.
The one caveat to this fix is that when directly linking to the first level of nesting, like
`namespace mozilla {`, we will add an extra line of padding.  This is because we are
choosing to favor the case where there's 2 stuck lines (like a nested namespace) and
avoid adding another selector or crazy math.  If only calc supported a
[signum function](https://en.wikipedia.org/wiki/Sign_function)!
=> Bug 1744153 - stuck line box-shadow wants padding

static/css/mozsearch.css
To choose the colors, I used the light mode colors, saturated them, then
made them semi-transparent until they looked the same with 0.17 alpha
(somewhat arbitrary), and applied them to the dark background.
=> Bug 1746071 - Add dark mode backgrounds for diff view.

docs/aws.md, infrastructure/aws/send-provision-email.py, infrastructure/aws/trigger-provision.py, tools/Cargo.lock, tools/Cargo.toml
As mentioned in https://bugzilla.mozilla.org/show_bug.cgi?id=1747289#c2 I am going to land and rapidly iterate on finishing up the provisioning automation.  Note that these changes do not change the VM triggering process at this moment, so the existing AMIs will continue to operate without regression (but will have new cargo deps to download).  See the individual commits for more details.
=> Bug 1747289 - Automate provisioning and update deps

static/css/mozsearch.css, static/js/context-menu.js
This patch prevents context menus from overflowing the viewport by
making them scrollable, and also positioning them towards the top if you
click down enough the page.
This could be improved in the future, but seems like a trivial
improvement to me.
=> context-menu: Improve giant context menus / context menus towards the bottom of the page.

scripts/indexer-logs-analyze.sh
To allow `indexer-logs-analyze.sh` to properly perceive java analysis
which bug 1633260 implements, it's necessary to add it for arity
processing.
=> Bug 1633260 - Java support: be aware of java-analyze.sh timestamps

README.md
I originally hadn't added the link when adding the doc because the doc
was still a WIP, but I missed adding it when I had expanded them.
=> Add a link to the testing docs from the root README.

tests/tests/checks/snapshots/check_glob@id__big_cpp__thing__json.snap, tests/tests/checks/snapshots/check_glob@xref__big_cpp__thing__json.snap
A current limitation of the test infrastructure is that it's very easy to accidentally
only add a single new test snapshot at a time because `make build-test-repo` stops at
the first failure.
Here are the new missing test snapshot values.
=> Bug 1749176 - Add missing test snapshots.

tests/tests/checks/inputs/traverse_callees__big_cpp__outercat_meet__json, tests/tests/checks/snapshots/check_glob@traverse_callees__big_cpp__outercat_meet__json.snap, tools/Cargo.lock, tools/Cargo.toml, tools/src/abstract_server/server_interface.rs, tools/src/bin/searchfox-tool.rs, tools/src/cmd_pipeline/builder.rs, tools/src/cmd_pipeline/cmd_graph.rs, tools/src/cmd_pipeline/cmd_traverse.rs, tools/src/cmd_pipeline/interface.rs, tools/src/cmd_pipeline/mod.rs, tools/src/cmd_pipeline/parser.rs, tools/src/cmd_pipeline/symbol_graph.rs, tools/src/file_format/crossref_lookup.rs, tools/tests/test_check_insta.rs
Note that all new functionality in this patch is not exposed to the
web and because RemoteServer::crossref_lookup is a no-op, the
functionality can only be used against a local index.
This implements:
- A basic graph abstraction in `symbol_graph.rs`.  petgraph is fairly
low level and is not geared towards storing heavy-weight metadata
with nodes or edges so we add some decidedly non-clever wrappers
but which should largely be type-safe.
- This includes serialization of the graph to JSON in a rep that
tries to sort everything so that the test output and human
inspection will be largely sane.  I did not optimize for
performance/memory here; I used BTreeMap and BTreeSet and called
it a day.
- A core "traverse" command which only implements "callees" right now.
- A single check that provides …
=> Bug 1749232 - Implement "traverse" command with graph support infra

infrastructure/aws/trigger_common.py
Previously the environment variables were only added to the little
script but not propagated into the sudo invocation because sudo was not
being told to propagate any env vars.  For the sake of clarity and to
avoid any weird precedence issues, we now explicitly list the env vars
on each sudo invocation.
=> Bug 1760832 - Propagate env vars to sudo invocations directly.

tools/Cargo.lock, tools/Cargo.toml, tools/src/bin/searchfox-tool.rs, tools/src/cmd_pipeline/builder.rs, tools/src/cmd_pipeline/cmd_crossref_lookup.rs, tools/src/cmd_pipeline/cmd_filter_analysis.rs, tools/src/cmd_pipeline/cmd_graph.rs, tools/src/cmd_pipeline/cmd_merge_analyses.rs, tools/src/cmd_pipeline/cmd_prod_filter.rs, tools/src/cmd_pipeline/cmd_search.rs, tools/src/cmd_pipeline/cmd_search_identifiers.rs, tools/src/cmd_pipeline/cmd_show_html.rs, tools/src/cmd_pipeline/cmd_traverse.rs, tools/src/cmd_pipeline/interface.rs, tools/src/cmd_pipeline/symbol_graph.rs, tools/src/lib.rs, tools/src/templating/builder.rs, tools/src/templating/liquid_exts.rs, tools/src/templating/mod.rs, tools/tests/test_check_insta.rs
This provides the backbone of the pipeline explanation mechanism, but
the templates in use right now just output the subscriber::fmt JSON
output for each logged event right now.  A few additional steps are
required to make this useful.
This patch can and will generate explanations parallel to the inputs
and checks sub-trees, but I haven't checked them in yet because they
are bad and include timestamps which means they would be a churn
nightmare.
Those next expected steps are:
- Add more tracing events, in particular for the server API calls.
- Have the events have some kind of semantic tag that helps the
template figure out how to present things.
- Make the template use that semantic tag!
- Make sure the explanation markdown files are stable across
multiple runs (no timestamps!).
In terms …
=> Bug 1763005 - generate markdown explanations of test pipelines

router/router.py
Nika ran into an odd gap in `nsIAsyncInputStream::Available` results which turned out to be due to this limit.
I believe my general concerns previously were:
- router.py should not OOM / take forever if someone searches for nsISupports
- Adding more than 50 symbols potentially grows the result set too much.
Unfortunately, when we decide not to merge, we don't currently emit a marker that says "hey, there were some other potential results here, but we didn't show them" which means that this limit is a real hard cliff in terms of user experience.  I'd been hoping to do more follow-ups shortly after this, but ended up running out of professional time to work on this, and my personal efforts have more been on foundational rust-based work.  So I'm doubling the limit for now and will plan to …
=> Bug 1728376 - Late-follow up heuristic limit change

infrastructure/indexer-provision.sh, infrastructure/web-server-provision.sh
In 747998194e3526085c7def0e986479b9c8dd36a2 I added a clone at the top
of both provisioner scripts but didn't deal with the reality that we
run both scripts for VM provisioning and that `git clone` will error if
you try and clone into an existing dir, even if the result would be the
same.  So we do a dir-check first.  (Also note that I think the update
steps at the bottom of each script would have created mozsearch too, so
it's really the lack of a check that's the problem.)
xref https://github.com/mozsearch/mozsearch/pull/501 which landed that
commit.
=> Bug 1764957 - idempotently check out mozsearch for email purposes

infrastructure/indexer-provision.sh
Now that our indexer checks run with the livegrep server running as
started by codesearch.py, we need to replicate the steps to build the
python livegrep gRPC bindings.  This was missed in local testing
because the VM runs both provisioner scripts.
This is a fixup to https://github.com/mozsearch/mozsearch/pull/505
=> The indexer now needs livegrep gRPC built too.

infrastructure/indexer-provision.sh, infrastructure/web-server-provision.sh
Since now both provisioning scripts will try to install the python
gRPC, it needs to live in the directory-guarded check so we don't
try and do it twice.  This has been tested locally and ideally won't
break the server provisioning!
=> Make livegrep grpc build idempotent for VM.

static/css/mozsearch.css, tests/help.html
This makes links behave appropriately by default, and overrides where
needed, rather than what we were doing which is a bit footgunny.
=> Better default link styling.

infrastructure/indexer-provision.sh, infrastructure/web-server-provision.sh
We've been experiencing intermittent "update" cargo build failures
which seem due to prost-build wanting to build `protoc` because we
don't already have it installed and something non-deterministic is
happening there.
It is recommended to already have `protoc` available and it seems
like that this does bypass the build process for protobuf, which will
ideally sidestep the build failures and will definitely improve build
time.  I'm not 100% clear on whether this means we can drop the cmake
dep, but we'll keep it for now.
=> Explicitly install protoc to decrease prost-build failures.

clang-plugin/MozsearchIndexer.cpp
(This is :asuth propagating the mozilla-central patch from
https://phabricator.services.mozilla.com/D146151 into mozsearch.)
=> Bug 1768996 - Support clang v15 in indexer.

static/css/icons.css, static/css/mozsearch.css, static/js/code-highlighter.js, static/js/panel.js, tools/src/bin/output-file.rs, tools/src/format.rs, tools/src/languages.rs, tools/src/output.rs
This adds "Copy as Markdown" section and 3 items, per [bug 1769936](https://bugzilla.mozilla.org/show_bug.cgi?id=1769936) comments,
between "Revision control" section and "Other Tools" section.
Here's the example text for each:
"Filename Link"
```
[Promise.cpp](https://searchfox.org/mozilla-central/source/js/src/builtin/Promise.cpp#443,448,451-453)
```
"Symbol Link"
```
[PromiseDebugInfo::id](https://searchfox.org/mozilla-central/source/js/src/builtin/Promise.cpp#443,448,451-453)
```
"Code Block"
````
https://searchfox.org/mozilla-central/source/js/src/builtin/Promise.cpp#443,448,451-453
```cpp
static uint64_t id(PromiseObject* promise) {
...
} else if (idVal.isObject()) {
...
if (idVal.isUndefined()) {
idVal.setDouble(++gIDGenerator);
debugInfo->setFixedSlot(Slot_Id, idVal);
```
```` …
=> Bug 1769936 - Add Copy as Markdown shortcuts.

static/js/panel.js, tools/src/bin/output-file.rs, tools/src/format.rs
Given the panel for non-latest page is generated in `format_path` in `tools/src/format.rs`, not in `main` in `tools/src/bin/output-file.rs`, the "Copy as Markdown" panel section needs to be added to both of them.
I've factored out the PanelSection creation into `create_markdown_panel_section` and let both of them call it.
=> Bug 1770501 - Show Copy as Markdown also on not-latest page.

tools/src/abstract_server/local_index.rs, tools/src/bin/crossref.rs, tools/src/bin/derive-per-file-info.rs, tools/src/bin/output-file.rs, tools/src/bin/print-identifiers.rs, tools/src/bin/web-server.rs, tools/src/config.rs, tools/src/format.rs
It can be quite expensive to load each tree in the config file,
especially when `need_indexes` is true, like in `output-file.rs`, to
the tune of an extra 82 seconds of loading time.  This change makes
us only load the desired tree for commands that only operate on a
single tree at a time.  The notable exception is `web-server.rs`
which inherently operates on all trees.
=> Bug 1567724 - Only load the desired tree for perf reasons.

infrastructure/aws/main.sh
- Removes the moot logic to move GNU parallel files from /tmp because
we now put them in INDEX_ROOT/diags/output.
- Add a call to lsof that grep filters to try and identify anything
that might have caused a failure to unmount.  I'm not running this
under sudo, but in theory that could make sense.  (But everything
we notionally run is same-user...)
=> Bug 1567724 - Clean up moot parallel handle_error logic, use lsof

docs/index-directory-contents.md, scripts/find-objdir-files.sh, scripts/indexer-logs-analyze.sh, scripts/mkindex.sh, scripts/output.sh, tools/src/bin/output-file.rs
We can eliminate a massive amount of process startup overhead by having
output-file receive the list of files to process over stdin.  With
these changes we basically run one output-file instance per core.  The
main trade-off is that because we distribute the list of files up front
and don't do any dynamic scheduling, there's a potential for unequal
distribution of work.
Should this end up being a meaningful problem, we can:
- Randomize the contents of `all-files` to avoid clustering of larger
files or ramifications of different path-lengths in the tree (since
divvying is based on bytes, not lines).
- Ditch parallel in favor of just having output-file internally be
multi-threaded and use a work-queue mechanism that can be aware of
how much work each thread still has to do / does …
=> Bug 1771620 - Pass paths to output-file over stdin

Vagrantfile, infrastructure/aws/trigger-provision.py, infrastructure/indexer-provision.sh, infrastructure/vagrant/indexer-provision.sh, infrastructure/web-server-provision.sh, tests/tests/checks/snapshots/crossref/merge/check_glob@merge__big_cpp.snap
Likely appropriate steps for people to do locally:
- On linux, make sure you have a recent version of `vagrant-libvirt`.  Things
work for me with `vagrant-libvirt` 0.7.0 on Ubuntu 22.04 as a host.
- Run `vagrant destroy`
- Run `vagrant up --no-destroy-on-error`.  If you experience any errors,
check the logs which you can access via `vagrant ssh`.
- It will likely be necessary to manually `make clean` in `clang-plugin`
before running `make build-test-repo` in `/vagrant` in the VM.
=> Bug 1771805 - Upgrade to 22.04 from 20.04.

infrastructure/aws/indexer-provision.sh, infrastructure/aws/web-server-provision.sh
All of the indexers failed to pivot their web-servers into place as
they ended up hung waiting to be able to load `status.txt`.  This
revealed that trigger-web-server.py's prints don't seem to be getting
into the `index-log` which is not what I was expecting and led me to
initially assume this was something else.
This was the same thing I saw inside the vagrant VM before but I'd
assumed that was only a change in the vagrant based VM.  Whoops!
Very humbling.
=> Bug 1771805 - make sure the home directory can be accessed via nginx

static/js/panel.js
This fixes the case that the first line has no whitespace.
the current code ignores that line and always deindent removing the first line's characters
=> panel: Fix deindent with leading line with no whitespace.

tools/src/cmd_pipeline/cmd_search_identifiers.rs
identifier-search would result in OOM termination without this as discovered via an interesting query-parser edge-case interacting with a typo.
=> Bug 1772720 - Add minimum limits for identifier search.

docs/aws.md, infrastructure/aws/build-lambda-indexer-start.sh, infrastructure/common-provision-pre.sh
Even though a lot of local provisioning-related tasks operate off local
repo state, I like to run these after landing things to minimize
potential problems with reproduction, including then running things
from a second repo.  The downside is this usually involves extra
landings when things eventually pick up on breakage.
It turns out our Ubuntu upgrade either stopped including virtualenv or
the lambda update jobs had depended on a locally-installed virtualenv.
I've now updated the common provisioning script to include this.
Strictly speaking only the VM needs the virtualenv, but this seems
likely to be useful to have everywhere.
I also updated the docs related to the lambda job creation because I
had missed the need to update the timeout, so I re-structured things
to use bullet points and …
=> Bug 1766925 - VM needs virtualenv for lambda, doc updates

scripts/tc-coverage-timestamps.sh
The coverage ingestion task can be retried because of infrastructure issues,
we should not assume there can only be one run and instead get the latest run
artifacts information.
=> Bug 1759071 - Don't assume the coverage ingestion task had only one run

router/codesearch.py, scripts/output.js, tools/src/output.rs, tools/templates/header_query.liquid, tools/templates/header_search.liquid
codesearch has stats we can log as well, noting that the repr will elide
zero values.
Potentially more notably, we inhibit the default submit behavior of the
search field in favor of our magic AJAX logic.  It would potentially be
better to explicitly handle the user pressing enter as an acceleration
of `startSearchSoon` via `startSearch` since startSearchSoon has a
300ms delay, but I'm going to have that be an enhancement since this
minimal fix is easier and an overall win for the user and the server.
=> Bug 1779672 - log codesearch stats, prevent default submit

docs/aws.md, infrastructure/aws/build-lambda-indexer-start.sh, infrastructure/common-provision-pre.sh
Glean indexing run builds on config4 have been failing with:
```
Compiling sample v0.1.0 (/mnt/index-scratch/glean/git/samples/rust)
Checking ordered-float v3.0.0
Checking url v2.2.2
Checking lmdb-rkv v0.14.0
error: failed to run custom build command for `sample v0.1.0 (/mnt/index-scratch/glean/git/samples/rust)`
Caused by:
process didn't exit successfully: `/mnt/index-scratch/glean/objdir/debug/build/sample-46862ee66fd1b733/build-script-build` (exit status: 101)
--- stdout
Python 3.10.4
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.
apt install python3.10-venv
You may need to use sudo with that command.  After installing the python3-venv
package, …
```
=> Move from using virtualenv to venv, motivated by glean builds failing.

infrastructure/common-provision-pre.sh
This is a breakage mitigation and we should un-pin when feasible.
=> Bug 1779939 - pin git-cinnabar at 0.5.8 for now

infrastructure/common-provision-post.sh, infrastructure/indexer-provision.sh, infrastructure/web-server-provision.sh
I'd moved the invocations of the update script into common provisioning
logic, but that is no longer appropriate now that the update scripts
differ in how they specify revisions.
=> Bug 1703115 - address divergence in update functions in provisioning

tools/src/bin/output-file.rs
I wanted to run rustfmt on things but this would bit-rot WIPs for the
move from ANALYSIS_DATA to SYM_INFO.
=> Bug 1782421 - output-file should accept and log Result `Err` returns from formatting logic instead of unwrapping them

infrastructure/indexer-upload.sh, scripts/load-vars.sh
The additional conditional in the upgrade logic was using `[` instead
of `[[` which is required.  This resulted in a nicely interesting
cascade failure for config4 when config1 failed to update (as inspected
via logs for the ongoing config4).
=> Bug 1782375 - Upload fix, `handle_tree_error` gets a better message

tests/tests/checks/inputs/fancy/diagram/traverse/big_cpp.cpp/callees__outercat_meet__dot, tools/Cargo.lock, tools/Cargo.toml, tools/src/bin/rust-indexer.rs, tools/src/cmd_pipeline/builder.rs, tools/src/cmd_pipeline/cmd_augment_results.rs, tools/src/cmd_pipeline/cmd_batch_render.rs, tools/src/cmd_pipeline/cmd_cat_html.rs, tools/src/cmd_pipeline/cmd_compile_results.rs, tools/src/cmd_pipeline/cmd_crossref_expand.rs, tools/src/cmd_pipeline/cmd_crossref_lookup.rs, tools/src/cmd_pipeline/cmd_filter_analysis.rs, tools/src/cmd_pipeline/cmd_graph.rs, tools/src/cmd_pipeline/cmd_merge_analyses.rs, tools/src/cmd_pipeline/cmd_prod_filter.rs, tools/src/cmd_pipeline/cmd_query.rs, tools/src/cmd_pipeline/cmd_search.rs, tools/src/cmd_pipeline/cmd_search_files.rs, tools/src/cmd_pipeline/cmd_search_identifiers.rs, tools/src/cmd_pipeline/cmd_search_text.rs, tools/src/cmd_pipeline/cmd_show_html.rs, tools/src/cmd_pipeline/cmd_traverse.rs, tools/src/cmd_pipeline/interface.rs, tools/src/cmd_pipeline/mod.rs, tools/src/cmd_pipeline/parser.rs, tools/src/lib.rs
We were slow enough in this upgrade that the migration ended up being
slightly more involved to make the deprecation warnings go away.  This
mainly entailed adding "value_parser" to everything.
This requires a re-provisioning because of our cargo deps policy that
we want the VM to already have cached the crates locally.
=> Bug 1783761 - Upgrade to clap v3 from clap v2/structopt

scripts/nginx-setup.py
The permalink optimization may actually have been broken even longer
than expected as by fixing the route, I revealed that we hadn't
compensated for the gzip optimization I'd done a long, long, long time
ago and so we were serving the 0-length files.  This implies the
format string might actually have had the same behavior for the byte
string and that this was broken since the change to python3.
=> Bug 1786216 - Further fix permalink current revision opt

tools/src/bin/build-blame.rs
This is @staktrace's proposed fix of using ok() with the added type consistency change of converting `map` to `and_then` since the type for the closure on `map` is `T -> U` but the type on [and_then](https://doc.rust-lang.org/nightly/core/option/enum.Option.html#method.and_then) is `T -> Option<U>` and we don't want `Option<Option<Object>>`.
This successfully ran on the dev channel.
=> Bug 1787667 - Avoid getting confused by removed submodules that are now dirs

scripts/js-analyze.js
Use the .mjs extension to opt in to module parsing.
=> Process mjs files as modules

scripts/js-analyze.js
Reverts mozsearch/mozsearch#568
js-analzye was not prepared for the additional new AST nodes it found in there:
```
/home/ubuntu/mozsearch/scripts/js-analyze.js:326:12 uncaught exception: Unexpected statement: ExportDeclaration
```
=> Revert "Process mjs files as modules"

tools/.cargo/config.toml
As noted in the extensive comment, I don't think we entirely want to give up on lld, but I want to read the docs a bit more on how rust-analyzer's actions outside the VM/container happen and the potential for problems if lld is being used inside the VM/container.
=> Bug 1612525 - Remove lld cargo build dep but keep it provisioned.

scripts/idl-analyze.py, scripts/js-analyze.js, tests/tests/checks/inputs/analysis/js/imported-module.mjs/def_ModuleClass__json, tests/tests/checks/inputs/analysis/js/imported-module.mjs/def_moduleConst__json, tests/tests/checks/inputs/analysis/js/imported-module.mjs/def_moduleFunc__json, tests/tests/checks/inputs/analysis/js/root-module.mjs/def_rootModuleConst__json, tests/tests/checks/inputs/analysis/js/secret-madjewel.js/def_secretMadjewelConst__json, tests/tests/checks/snapshots/analysis/js/imported-module.mjs/check_glob@def_ModuleClass__json.snap, tests/tests/checks/snapshots/analysis/js/imported-module.mjs/check_glob@def_moduleConst__json.snap, tests/tests/checks/snapshots/analysis/js/imported-module.mjs/check_glob@def_moduleFunc__json.snap, tests/tests/checks/snapshots/analysis/js/root-module.mjs/check_glob@def_rootModuleConst__json.snap, tests/tests/checks/snapshots/analysis/js/secret-madjewel.js/check_glob@def_secretMadjewelConst__json.snap, tests/tests/checks/snapshots/web/dirs/check_glob@root_listing__html.snap, tests/tests/files/imported-module.mjs, tests/tests/files/root-module.mjs, tests/tests/files/secret-madjewel.js
For JS parsing:
- If the file ends in ".mjs" we treat it as a module only.
- If the file ends in ".js" we try parsing it as a script and fall back to also trying it as a module if it doesn't parse as a script because imports/exports are illegal.
For the analysis:
- We process ExportDeclaration nodes by recursively processing the declaration it wraps.
- We otherwise ignore everything having to do with modules because our SCIP support should let us do clever things soon so it's a bit of a waste to try and do something smart since it will all just get thrown away.
I add some very basic definition checks to ensure that we've parsed the modules and the export declarations.  I don't add any other pre-existing JS checks at this time.  This is largely because we haven't really seen regressions …
=> Bug 1789329 - Add explicit mjs parsing, fallback module parsing, tests.

scripts/js-analyze.js, tests/tests/checks/snapshots/analysis/js/root-module.mjs/check_glob@def_rootModuleConst__json.snap, tests/tests/checks/snapshots/web/dirs/check_glob@root_listing__html.snap, tests/tests/files/root-module.mjs
This includes a bunch of mitigations, most of which are discussed on the bug.  In general the strategy is to downgrade things to INFO from WARN if it's complaining about:
- something that's explicitly intended to be an error in source code, like a syntax error test
- something that we cannot make searchfox handle on its own in the existing JS analyzer, like JSX or import assertions 
- something that do not want to make the existing JS analyzer support because it would be a ton of work that would be obsoleted by moving to scip-typescript.
=> Warning fixes

scripts/js-analyze.js
See individual commits for additional details including discussion of how in general we just want to be processing `.eslintignore`.
=> More warning reduction

tools/Cargo.lock, tools/Cargo.toml
We're using the mechanism documented at
https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html to reference destructure_traitobject when its Cargo.toml still claimed to be traitobject.
=> Bug 1797153 - patch traitobject to use destructure_traitobject

scripts/js-analyze.js
For kaios we're seeing:
```
WARN when parsing as 'module': Unable to parse JS file /mnt/index-scratch/kaios/git/dom/push/PushServiceWebSocket.sys.mjs:1 because SyntaxError: redeclaration of import XPCOMUtils: /mnt/index-scratch/kaios/git/dom/push/PushServiceWebSocket.sys.mjs:7
```
This is just buggy code we're processing, not a buggy searchfox understanding.
=> Downgrade buggy kaios code warning:

tests/tests/checks/inputs/analysis/js/some_javascript.js/all__priv_field_num__html, tests/tests/checks/inputs/analysis/js/some_javascript.js/all__priv_field_num__json, tests/tests/checks/snapshots/analysis/js/some_javascript.js/check_glob@all__priv_field_num__html.snap, tests/tests/checks/snapshots/analysis/js/some_javascript.js/check_glob@all__priv_field_num__json.snap, tests/tests/checks/snapshots/web/dirs/check_glob@root_listing__html.snap, tests/tests/files/some_javascript.js, tools/src/languages.rs, tools/src/tokenize.rs
We were analyzing private symbols acceptably, but the tokenizer did not recognize them as valid identifier symbols, which meant we would just output them as plain text.
=> Bug 1801960 - Tokenize JS private symbols, add checks.

static/js/context-menu.js
As :saschanaz pointed out, the context-menu's "search for the substring" option is excluding the leading "#" for private symbols still, which is weird.
This fix naively just widens the regex.  I imagine there could be regressions for this and it could make sense for this JS to instead understand the difference between:
- The user clicking on a symbol for which we can know the exact symbol string to use.
- The user clicking on random text which is not marked up as a symbol and for which we should use a regex heuristic.
- The user selecting a region of text and then clicking on it with the intent to potentially provide our context menu to search for that string, but where we will currently erase the user's own selection.
=> Bug 1801960 - Widen the context-menu word regexp to include #.

clang-plugin/MozsearchIndexer.cpp
This is a manual import of https://phabricator.services.mozilla.com/D165266 as landed at https://hg.mozilla.org/mozilla-central/rev/1931d3d21dc9 applied via patch -p4 directly against the file.
=> Bug 1806771 - Adjust searchfox plugin to clang upstream changes.

infrastructure/web-server-setup.sh, scripts/nginx-setup.py, scripts/output.sh, static/css/icons.css, static/css/mozsearch.css, static/js/blame.js, static/js/code-highlighter.js, static/js/context-menu.js, static/js/panel.js, static/js/search.js, static/js/settings.js, tests/tests/checks/snapshots/web/dirs/check_glob@generated_listing__html.snap, tests/tests/checks/snapshots/web/dirs/check_glob@root_listing__html.snap, tests/tests/checks/snapshots/web/files/nav-panel/check_glob@wpt__some_cross_global_test__navpanel__html.snap, tests/tests/checks/snapshots/web/files/nav-panel/check_glob@wpt__test_ima_weird_meta_wpt__navpanel__html.snap, tests/tests/checks/snapshots/web/templates/check_glob@help_file__html.snap, tests/tests/checks/snapshots/web/templates/check_glob@search_template__html.snap, tools/src/abstract_server/local_index.rs, tools/src/abstract_server/server_interface.rs, tools/src/cmd_pipeline/cmd_render.rs, tools/src/format.rs, tools/src/output.rs, tools/src/templating/builder.rs, tools/templates/scroll_footer.liquid, tools/templates/settings.liquid
There was a little hiccup in bug 1809987 where it turns out the context menu actually thought it was displaying icons, and with the CSS class changes, the layout of the context menu regressed.  I hadn't realized icons went there because back in 2021 we deleted the CSS glue that used to always display search icons in the context menu.  (And I mean always!  DXR used icons to differentiate between different classes of options but in searchfox it seems we've only ever used the search icon.  There is more work to do on this moving forward.)
=> Bug 1703656 - Implement a settings page, minor context menu regression fix

static/js/settings.js, tools/templates/settings.liquid
I had missed a final cleanup pass on the settings page text, leaving a number of fragments of text that were obsoleted by the bullet structuring.  This should now be addressed (hopefully)!  But there's still conversations to have around the text which could lead to future iteration.
I also realized the quality levels of features was not being reflected into the page, so I added a mechanism for that by using identifiers of the form "quality--group-name--key-name" where the "group-name--key-name" following "quality--" is the same identifier we expect to see when performing form binding.
=> Bug 1703656 - Remove settings page text detritus, bind feature qualities.

router/codesearch.py, router/router.py, static/js/search.js, tests/tests/checks/snapshots/web/search/big_cpp.cpp/check_glob@abstractart__json.snap, tests/tests/checks/snapshots/web/search/big_cpp.cpp/check_glob@abstractart_beart__json.snap, tests/tests/checks/snapshots/web/search/big_cpp.cpp/check_glob@human__json.snap, tests/tests/checks/snapshots/web/search/big_cpp.cpp/check_glob@practicalart__json.snap, tests/tests/checks/snapshots/web/search/big_cpp.cpp/check_glob@practicalart_beart__json.snap, tests/tests/checks/snapshots/web/search/overs.cpp/check_glob@doublePure__json.snap, tests/tests/checks/snapshots/web/search/overs.cpp/check_glob@triplePure__json.snap
While we can ideally do a lot of clever things in the future with the "query" endpoint, this patch:
- Quadruples the result limit to 4000 from 1000.
- Applies a limit of 32000 to search_files because search_files is not aware of test file categorization/etc. and so applying the same limit here as we do for results demonstrably can be confusing and unhelpful!
- The scaling factor here is 4 and I have un-helpfully put this behind a new constant, `EXTREME_FACTOR`.  In general I try and avoid optimizing code for my enjoyment over maintainability, but since router.py is explicitly not slated for any meaningful feature enhancements, I shall allow myself this novelty.  (But I also have no problem if someone wants to rename it something less fun.)
- Adds explicit signaling if we hit a quantity …
=> Bug 1459188 - Relax router.py result limits, especially file result limits.

static/js/search.js
The multi-pass approach to calling populateResults would render the limits hit on the first-pass through while also destroying the data, so the second render pass would clear them.  Now we just ignore those keys.
=> Bug 1459188 - Ignore "*" prefix pathkind keys rather than deleting them.

docs/bash-scripting-cheatsheet.md, scripts/weblog-elb-analyze.sh, scripts/weblog-elb-fetch.sh
This differs from weblog-analyze.sh which parses our custom nginx log setup which lives behind the ELB ALB and is able to provide useful context about cache hits/misses, but whose logs currently need to be manually pulled off an indexer via ssh.
=> Implement ELB ALB log processing with fetcher script.

clang-plugin/MozsearchIndexer.cpp, tests/tests/checks/inputs/analysis/cpp/bug1781178.cpp/Foo_Project, tests/tests/checks/snapshots/analysis/cpp/bug1781178.cpp/check_glob@Foo_Project.snap, tests/tests/checks/snapshots/web/dirs/check_glob@root_listing__html.snap, tests/tests/files/bug1781178.cpp
Posting a WIP patch for [bug 1799579](https://bugzilla.mozilla.org/show_bug.cgi?id=1799579).
The patch partially fixes the bug, in that the call to `Project` is now clickable and offers the menu item "Search for function `Foo::Project`", but it does not yet offer the menu item "Go to definition of `Foo::Project`", which we'd like as well.
I will continue investigating why it doesn't offer that second menu item, but in the meantime I wanted to post what I have.
---
Also, a note on why I didn't use the `AutoTemplateContext` machinery:
While `OverloadExpr` is (usually, and in this testcase in particular) dependent, it's a bit different from `CXXDependentScopeMemberExpr` in that candidate declarations being referenced are available, and it's only the selection among the candidates that's …
=> Bug 1799579 - Handle OverloadExpr in MozSearchIndexer

tools/src/file_format/crossref_converter.rs
It appears that sometimes lines has a length of zero, and so the lines.remove(0) crashes. This updates the guard to protect against that case too. I have no idea what this code is doing though so maybe there's a better fix, but this should hopefully at least unblock the indexer.
=> Bug 1829273 - Fix crash when processing NSS

static/js/code-highlighter.js, static/js/panel.js
There is a relatively new web platform API with the name "Highlight", whose existence [1] breaks the line highlighting feature of Searchfox on Chromium-based browsers where this feature is implemented [2]. Rename Highlight to Highlighter to avoid this name collision.
References:
[1]: https://developer.mozilla.org/en-US/docs/Web/API/Highlight
[2]: https://chromestatus.com/feature/5436441440026624
Latest Chrome (112) gives the following error without this fix:
> Uncaught TypeError: Cannot read properties of undefined (reading 'size')
at isEnabled (panel.js:41:42)
at Panel.updateMarkdownState (panel.js:302:11)
at Panel.onSelectedSymbolChanged (panel.js:317:10)
at DocumentTitler.processLineSelection (code-highlighter.js:243:11)
at Highlight.updateHash (code-highlighter.js:566:20)
at …
=> Rename Highlight to Highlighter to avoid collision

scripts/rust-analyze.sh
With the latest mozilla-config and scip changes, this gives me a working mozilla-central index.
There are some regressions that I noticed that might be worth addressing first:
* No stdlib symbols: If you have `use std::io::Write;`, clicking `Write` won't find all references to it. Not super-surprising given we have a bunch of extra code to deal with the rust stdlib in save analysis, but maybe we can do something about it.
* No module definitions: If you have `mod foo;`, clicking `foo` won't show the "Go to definition" button to get you to the file.
* #[no_mangle] functions keep the rust-module-namespaced symbol names. I'm not sure how easy to address is this without upstream fixes, we'll see.
Other than that, it seems to be working, and maybe we can even enable it by default if those …
=> rust: Prefer scip index if available.

tools/src/bin/rust-indexer.rs
This is useful for debugging but not so much otherwise.
=> rust: Avoid warning spew.

clang-plugin/MozsearchIndexer.cpp, tests/tests/checks/inputs/analysis/cpp/bug1781178.cpp/Point_IsThereOne, tests/tests/checks/snapshots/analysis/cpp/bug1781178.cpp/check_glob@Foo_Project.snap, tests/tests/checks/snapshots/analysis/cpp/bug1781178.cpp/check_glob@Point_IsThereOne.snap, tests/tests/checks/snapshots/web/dirs/check_glob@root_listing__html.snap, tests/tests/files/bug1781178.cpp
Posting a draft fix for bug 1828223 for feedback.
I would appreciate feedback on two points in particular:
1. Currently, in `IndexConsumer::VisitCXXDependentScopeMemberExpr()`, I both (1) produce a heuristic result (that's what's new in this patch), **and** (2) record the location for possibly producing concrete results when visiting instantiations (if we have any) during the `AnalyzeDependent` phase (what the code was doing before).
I'm wondering, should we add some logic to **only** produce the heuristic result if we didn't end up producing concrete results from the `AnalyzeDependent` phase?
I feel like I could go either way on this. On the one hand, the indexer might only know about a subset of the instantiations actually occurring in the project, and the concrete results might …
=> Bug 1828223 - Implement heuristic resolution of CXXDependentScopeMemberExpr

tools/Cargo.lock
This makes the nightly build work again.
=> Bug 1841356 - Update proc-macro2 to latest

infrastructure/indexer-update.sh
Some repos want this installed, and it seems like it's not installed by default any more.
=> Bug 1841556 - Add rust-analyzer component

sax/README, sax/sax.js, sax/sax.patch
It appears our local copy of sax-js had an (undocumented) modification from the original. This restores the modification and records the change more explicitly.
=> Bug 1848995 - Restore local modifications to sax-js

docs/aws.md, infrastructure/indexer-provision.sh
This also includes a doc fix where I got the markdown syntax backwards before (whoops!).
=> Bug 1852405 - Provision ninja to support LLVM semantic indexing.

tools/src/languages.rs
Assume "inc" files are C++ files because we frequently have C++ analysis records for them, whereas we never have analysis records for any other "inc" file extension, and we need to tokenize the file as C++ to use that analysis information.
=> Bug 1852419 - "inc" files are probably C++ files.

.gitignore, Makefile, README.md, build-docker.sh, docs/old-vagrant-setup.md, infrastructure/indexer-provision.sh, run-docker.sh, tree-configs/README.md, trees/README.md
This is slightly more of my hobby-stack touching the docker scripts than I was expecting when I said what I was going to do in https://github.com/mozsearch/mozsearch/pull/653 but I think this is probably a reasonable subset and gets all the re-provisioning out of the way at once.  I have locally re-provisioned with `./build-docker.sh` with these changes and it just ran fine.  I will perform automated re-provisioning of the AMIs if/when this PR gets r+'ed to land and I land it.
The most helpful change to the docker scripts is that it defines a persistent volume that gets mounted at the "vagrant" user's home directory.  Without this change, anything that happens in the docker container is entirely ephemeral and evaporates when the canonical run-docker.sh session exists.  This didn't matter …
=> Document use of docker, add support for "trees" repo, provision scip-typescript and scip-python

Makefile, scripts/mkdirs.sh, scripts/output.sh
Three small changes here:
- Use `just-mc.json` to build mozilla-central, not all of config1.json.
- Clean up more things from repeated invocations of `make build-mozilla-repo` (under `/vagrant`).  I think blame will still be inefficiently recalculated, though.
- Limit output-file to 8 threads because for m-c because the downside of docker exposing all cores/hyperthreads is that memory intensive tasks like output-file (needs ~2GiB per thread/instance for m-c) it can be brutal on the host system.  Especially with proactive OOM-killers, it can wipe out a bunch of important processes.
I'm going to land these directly as I'm landing these as part of doing the first bunch of review for scip-indexer from my asuth-hobby-stack and I think these are a distraction, but am happy to follow-up on any …
=> Various improvements to using `make build-mozilla-repo` under docker

infrastructure/common-provision-pre.sh
`scip print` is extremely useful for debugging / understanding what's going on with SCIP indices.  Note that it can take some time to run on large indices and the output will be voluminous, so you'll always want to pipe to a pager.
Originally we were updating to 0.2.3 but 0.3.0 makes the print command also support JSON output via `--json` which seems potentially useful.
=> Provision scip CLI 0.3.0 to get `scip print`

scripts/idl-analyze.sh, scripts/update-fonts.sh
When running `make build-mozilla-repo` from a persistent VM volume, it's necessary to be ready to delete the XPIDL libs and re-extract them to avoid being inconsistent with the tree.
=> Avoid using stale XPIDL libs.

scripts/ipdl-analyze.sh, tools/src/bin/ipdl-analyze.rs
This updates us to use https://github.com/mozsearch/ipdl_parser/pull/12 so we can parse PContent, and with the remainder of the changes here, correctly do the C++ semantic linkage as well.
Previously we used a predicted path, but this doesn't work for preprocessed files which can't be unified by the platform merge step for trees like mozilla-central.
=> Bug 1417586 - Handle preproced IPDL, determine C++ locations from objdir-files lookup.

infrastructure/common-provision-pre.sh, tools/Cargo.lock, tools/Cargo.toml, tools/src/bin/rust-indexer.rs
Note that a number of new fields were added in v0.3.0 that we should potentially process in scip-indexer.rs.
=> Bug 1862092 - Update to SCIP v0.3.1

.envrc, .gitignore, README.md, build-docker.sh, docs/aws.md, flake.lock, flake.nix, infrastructure/docker-provision.sh, run-docker.sh, scripts/indexer-logs-analyze.sh, scripts/indexer-logs-fetch.sh, scripts/tc-coverage-timestamps.sh, scripts/weblog-analyze.sh, scripts/weblog-elb-analyze.sh, scripts/weblog-elb-fetch.sh
As requested by @asutherland in https://bugzilla.mozilla.org/show_bug.cgi?id=1490144#c7 I'm sharing here my Podman/Nix-based setup:
> For your stack, it's great that you're adding podman and nix support! For nix, I'm not really familiar with nix, although I understand it's popular and something I should be more familiar with! It would be great to split those out into their own pull request(s), and in particular since I'm not familiar with nix, it would be great if you could make sure to[1]:
> 
> - Provide brief context about what the .envrc file is in the commit message. (In particular, since it's a fairly generic dotfile name, it'd be good for the history for the file to help provide that context.)
> - Add some additional context to the docs about what nix is and when people would want …
=> Podman support and Nix flake

scripts/js-analyze.js
Added dedicate path for `SpreadExpression` inside `ObjectExpression` and `ObjectPattern`, to handle `({...foo})` syntax in JS
=> Bug 1818027 - Handle spread inside object in JS.

clang-plugin/MozsearchIndexer.cpp, docs/analysis.md, scripts/idl-analyze.py, tests/tests/checks/inputs/crossref/java/JavaLibrary.java/multiple_implements__json, tests/tests/checks/snapshots/analysis/cpp/big_cpp.cpp/check_glob@structured_human__json.snap, tests/tests/checks/snapshots/analysis/cpp/big_cpp.cpp/check_glob@structured_outercat__json.snap, tests/tests/checks/snapshots/analysis/cpp/big_cpp.cpp/check_glob@structured_practicalart_beart__json.snap, tests/tests/checks/snapshots/analysis/cpp/big_cpp.cpp/check_glob@structured_superhero__json.snap, tests/tests/checks/snapshots/analysis/cpp/big_cpp.cpp/check_glob@structured_superhero_takedamage__json.snap, tests/tests/checks/snapshots/analysis/java/InlineObject.kt/check_glob@method__json.snap, tests/tests/checks/snapshots/analysis/java/InlineObject.kt/check_glob@method_with_return_type__json.snap, tests/tests/checks/snapshots/crossref/expand/big_cpp.cpp/check_glob@outercat__json.snap, tests/tests/checks/snapshots/crossref/java/JavaLibrary.java/check_glob@multiple_implements__json.snap, tests/tests/checks/snapshots/crossref/java/JavaLibrary.java/check_glob@no_inverse_relationships__json.snap, tests/tests/checks/snapshots/crossref/merge/check_glob@merge__big_cpp.snap, tests/tests/checks/snapshots/fancy/diagram/traverse/big_cpp.cpp/check_glob@callees__outercat_meet__json.snap, tests/tests/checks/snapshots/jumpref/jumpref/big_cpp.cpp/check_glob@practicalart__beart__lookup__json.snap, tests/tests/files/src/main/java/sample/JavaLibrary.java, tools/src/bin/scip-indexer.rs, tools/src/file_format/analysis.rs
Extra fixes to the SCIP ingestion as discussed in /pull/667.
=> Fixes to SCIP ingestion: multiple inheritance & ignoring declaration order when parsing relationships

flake.lock, flake.nix
This enables building the Rust project in tools and the clang-plugin and adds rust-analyzer and clangd to have LSP support in the Nix devShell.
Also updated flake.lock.
=> Add tools and clang-plugin dependencies to Flake

flake.nix, infrastructure/common-provision-pre.sh, tests/tests/checks/snapshots/analysis/cpp/template_shapes.cpp/check_glob@Foo_Project-2.snap, tests/tests/checks/snapshots/analysis/js/imported-module.mjs/check_glob@def_ModuleClass__json.snap, tests/tests/checks/snapshots/analysis/js/imported-module.mjs/check_glob@def_ModuleClass_error__json.snap, tests/tests/checks/snapshots/analysis/js/imported-module.mjs/check_glob@def_moduleConst__json.snap, tests/tests/checks/snapshots/analysis/js/imported-module.mjs/check_glob@def_moduleFunc__json.snap, tests/tests/checks/snapshots/analysis/js/root-module.mjs/check_glob@def_rootModuleConst__json.snap, tests/tests/checks/snapshots/analysis/js/secret-madjewel.js/check_glob@def_secretMadjewelConst__json.snap, tests/tests/checks/snapshots/analysis/js/some_javascript.js/check_glob@all__priv_field_num__html.snap, tests/tests/checks/snapshots/analysis/js/some_javascript.js/check_glob@all__priv_field_num__json.snap, tests/tests/checks/snapshots/analysis/rust/simple.rs/check_glob@simple_Loader_new__json.snap, tests/tests/checks/snapshots/crossref/merge/check_glob@merge__big_cpp.snap
Attempt at fixing the wubkat index, and making the clang version we use closer to the one the Firefox build uses.
nixpkgs doesn't have llvmPackages_17 yet, so updating to 16 there for the time being.
=> Update to clang 17

static/css/mozsearch.css, static/js/panel.js, tools/src/bin/output-file.rs
This changes:
* Add "Remove the Permalink" link to the Navigation box for the latest revision
* This is a link to the same thing as "Go to latest version" in older revision
* This is disabled when the URL is not permalink
* This is enabled when the URL is permalink
* The enabled/disabled status is dynamically updated when clicking "Permalink" and "Remove the Permalink"
(left: navigation box for non-permalink, right: navigation box for permalink)
The "Permalink" item isn't disabled, because it has "copy" button, and I think the button should be available regardless of the current URL.
=> Bug 1621788 - Add "Remove the Permalink" button for the latest revision.

scripts/js-analyze.js, tests/tests/checks/snapshots/analysis/js/imported-module.mjs/check_glob@def_ModuleClass__json.snap, tests/tests/checks/snapshots/analysis/js/imported-module.mjs/check_glob@def_ModuleClass_error__json.snap, tests/tests/checks/snapshots/analysis/js/imported-module.mjs/check_glob@def_moduleConst__json.snap, tests/tests/checks/snapshots/analysis/js/imported-module.mjs/check_glob@def_moduleFunc__json.snap, tests/tests/checks/snapshots/analysis/js/root-module.mjs/check_glob@def_rootModuleConst__json.snap, tests/tests/checks/snapshots/analysis/js/secret-madjewel.js/check_glob@def_secretMadjewelConst__json.snap, tests/tests/checks/snapshots/analysis/js/some_javascript.js/check_glob@all__priv_field_num__html.snap, tests/tests/checks/snapshots/analysis/js/some_javascript.js/check_glob@all__priv_field_num__json.snap
The checks here are the inverse of the changes in
https://github.com/mozsearch/mozsearch/pull/677 as expected.
This also slips in a change to quiet this warning we're seeing in config1 emails:
```
WARN when parsing as 'module': Unable to parse JS file /mnt/index-scratch/comm-central/git/mozilla/testing/web-platform/tests/wasm/webapi/esm-integration/resources/worker-source-phase.js:1 because SyntaxError: missing keyword 'from' after import clause: /mnt/index-scratch/comm-central/git/mozilla/testing/web-platform/tests/wasm/webapi/esm-integration/resources/worker-source-phase.js:1
```
=> Bug 1868235 - Adapt to SpiderMonkey's new 1-based columns.

config_defaults/ontology-mapping.toml
A smoke test on graphviz didn't find this, but after the last merge I did a check of the test repo and it caught the dupe.  Presumably the check process was necessary, although I'm a little surprised.
=> Remove duplicate ontology entry.

tests/tests/checks/snapshots/web/dirs/check_glob@root_listing__html.snap, tools/Cargo.lock, tools/Cargo.toml
The test change seems to suggest the snapshot mechanism was eating newlines.  I am not entirely sure why that changed, it's possible something weird is going on.  (Specifically, the insta changelog at https://github.com/mitsuhiko/insta/blob/master/CHANGELOG.md does not seem to identify any changes in our change from 1.28 to 1.34.)
=> Bug 1878936 - Update cargo deps to address ahash breakage

infrastructure/indexer-provision.sh
Tested with full local re-provisioning via `build-docker.sh` followed by `make build-test-repo` in the resulting docker image, will use this to re-provision the indexer after landing.
=> Bug 1878936 - update rtx runtime tool to its new name, mise

scripts/indexer-logs-analyze.sh, scripts/weblog-elb-fetch.sh
I was worried about the config1 indexer time so I ran the logs and noticed it didn't understand scip-analyze, so I fixed that.
I also was wondering if anyone had done any novel python queries and taught the log fetcher human date constraint about "today".
=> Teach indexer log analysis about scip, add "today" for ELB log analysis.

config_defaults/ontology-mapping.toml, infrastructure/web-server-run.sh, tests/tests/checks/inputs/fancy/diagram/traverse/big_cpp.cpp/callees__colorize__outercat_meet__dot, tests/tests/checks/inputs/fancy/diagram/traverse/big_cpp.cpp/callees__colorize__outercat_meet__svg, tools/src/cmd_pipeline/cmd_traverse.rs, tools/src/cmd_pipeline/symbol_graph.rs
- Adds a virtual memory ulimit on the pipeline-server that works in docker at least.
- Overhauls the path-propagation logic to directly process the list of discovered paths instead of buffering them first.
- Limits the all-paths petgraph algorithm invocation to have a max depth of the depth traversal we set for the graph.  This was likely a major factor in performance problems, as adding this made a huge difference.  This makes sense because in many cases there's a ton of internal control flow.
=> Bug 1884591 - Harden pipeline-server, improve diagramming efficiency

config_defaults/ontology-mapping.toml, tests/tests/checks/snapshots/web/query/parsing/simple/big_cpp.cpp/check_glob@query__parse__calls_to__colorize__takeDamage__json.snap, tests/tests/checks/snapshots/web/query/parsing/simple/big_cpp.cpp/check_glob@query__parse__calls_to__takeDamage__json.snap, tests/tests/checks/snapshots/web/query/parsing/simple/big_cpp.cpp/check_glob@query__parse_calls_to__graoh_format__takeDamage__json.snap, tests/tests/checks/snapshots/web/query/parsing/simple/lots_of_calls.cpp/check_glob@query__parse__calls_between__four_left_one_right__svg.snap, tests/tests/checks/snapshots/web/query/parsing/simple/lots_of_calls.cpp/check_glob@query__parse__calls_to__four_left_and_right__svg.snap, tools/src/bin/pipeline-server.rs, tools/src/cmd_pipeline/cmd_crossref_lookup.rs, tools/src/cmd_pipeline/cmd_traverse.rs, tools/src/cmd_pipeline/interface.rs, tools/src/file_format/identifiers.rs, tools/src/file_format/ontology_mapping.rs, tools/src/query/query_core.toml
- Change identifiers lookup to report the identifier from the lookup row rather than demangling.  I believe the demangling decision to be obsolete in the era of structured records, but made sense in the router.py-consumed python implementation (and which still works that way).
- Change diagram crossref-lookup to require an absolute pretty rather than a pretty suffix.
- This depends on the above change to identifiers; identifier search can avoid doing a prefix match, but because we emit all suffix variations, we need to apply a constraint in crossref-lookup to filter out false matches.
- This allows, for example, diagramming on "abort" without getting "foo::abort".
- The pipeline-server now only instantiates the logged span if we are planning to consume the result.  This was done for …
=> Bug 1884591 - Diagramming improvements / hardening.

static/css/mozsearch.css
Added `prefers-contrast` media to provide borders for blame controls and improve the system color palette for High Contrast Modes for bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1883948
=> Update mozsearch.css to support HCM for blame and input fields

infrastructure/common-provision-pre.sh
With the android repo merge into mozilla-central, git fetch on central was throwing.  This may potentially have been a transient issue with the server, but since there wasn't a reason to be on an old version of cinnabar, I updated us to the most recent release before checking if things were now okay.
I'm leaving us using a specific release for reproducability reasons, but honestly if I'd thought to check if there was a "release" branch (there is, it's up-to-date), I probably would have used that.  That might be the next thing to do if things ever break again.
=> Bug 1779939 - update git-cinnabar to 0.6.3

static/css/mozsearch.css
1. Moving most of the `prefers-contrast` queries to `forced-colors` to ensure the HCM only applies to WinOS. This would ensure the Increase Contrast mode on macOS is appearing as expected. 
2. Correcting the input field on `forced-colors` to use `Field`/`FieldText` color combination with `ButtonText` border, as recommended by @MReschenberg [in the comments to the original patch](https://github.com/mozsearch/mozsearch/pull/697#discussion_r1526755458)
3. I'm retaining the border for the blame dialog to be added on `prefers-contrast` modes across OSes to ensure the dialog is visually clearly discernible from the underlying page content.
=> Update mozsearch.css to correct HCM/IC colors on Windows and Mac

tools/Cargo.lock, tools/src/file_format/identifiers.rs, tools/src/lib.rs
There were still a few lingering warnings after the most recent landings, so I ran `cargo fix --lib -p tools` like it wanted me to, and it wanted me to commit changes to Cargo.lock first, so I did.
This makes `cargo build --release` build clean.
=> Update Cargo.lock for ipdl_parser landings maybe, cargo fix pass

tools/src/cmd_pipeline/cmd_fuse_crossrefs.rs, tools/src/cmd_pipeline/cmd_prod_filter.rs, tools/src/cmd_pipeline/cmd_show_html.rs
I realized I hadn't re-provisioned or run `rustup update` recently in the docker VM; these also existed but were very easy to make go away for a net time savings in terms of searchfox emails.
=> Warning cleanup: allow dead_code for command args

tools/src/cmd_pipeline/symbol_graph.rs
In a graphviz forum post it was mentioned that neato has a hier mode (see https://graphviz.org/docs/attrs/mode/) which attempts a top-down layout.  A notable piece of feedback for the neato/sfdp layouts versus the default dot layout was that they were much more stressful to look at, even if they provided potentially more useful density.  This was trivial to quickly hack in and A/B test thanks to previous efforts in this space.
In particular, this mode seems quite nice for larger inheritance diagrams, but one notable thing was self-edges for XPCOM interfaces where the pretty identifier for the XPCOM interface are the same for the C++ class overlapping adjacent nodes.  To this end, I also increased the "sep" margin (https://graphviz.org/docs/attrs/sep/).
=> Use mode=hier for neato per graphviz forum suggestion

clang-plugin/BindingOperations.cpp, clang-plugin/MozsearchIndexer.cpp
(This is :asuth propagating the patch from
https://phabricator.services.mozilla.com/D208723 into mozsearch.)
=> Bug 1873574 - Update mozsearch clang plugin to support clang-18

tests/tests/checks/snapshots/web/dirs/check_glob@root_listing__html.snap, tools/src/file_format/repo_data_ingestion.rs
for https://bugzilla.mozilla.org/show_bug.cgi?id=1894632
=> Bug 1894632 - Calculate the non-UTF-8 file size correctly.

clang-plugin/MozsearchIndexer.cpp
(This is :asuth propagating the patch from
https://phabricator.services.mozilla.com/D209325 into mozsearch.)
=> Bug 1894860 - clang 19 clang-indexer updates

static/js/code-highlighter.js
for https://bugzilla.mozilla.org/show_bug.cgi?id=1895160
This allows "Symbol Link" in the following case:
* forward declaration  (e.g. `BoxNonStrictThis` line in https://searchfox.org/mozilla-central/source/js/src/vm/Interpreter.h#30 )
* single-line function definition (e.g. `Breakpoint::nextInDebugger()` line in https://searchfox.org/mozilla-central/source/js/src/debugger/Debugger.cpp#474 )
* a selection in nesting container with depth == 0 (e.g. lines in `js::BoxNonStrictThis` in https://searchfox.org/mozilla-central/source/js/src/vm/Interpreter.cpp#107)
=> Bug 1895160 - Reflect the forward declaration and the single-line function definition to the selected symbol

scripts/indexer-logs-analyze.sh
macOS's grep doesn't have -P option.
GNU grep is available via homebrew, as ggrep.
=> Use GNU grep on macOS in indexer-logs-analyze.sh

scripts/indexer-logs-fetch.sh
macOS's date command doesn't support `--date` option, but it has `-v` option to adjust the date
=> Use -v option for the date command on macOS in indexer-logs-fetch.sh

scripts/js-analyze.js, scripts/js-analyze.sh, scripts/mkindex.sh, scripts/process-chrome-map.py
for https://bugzilla.mozilla.org/show_bug.cgi?id=1895316
depends on https://github.com/mozsearch/mozsearch-mozilla/pull/232
1. process the `chrome-map.json` into "URL to file path" map, and save it as `url-map.json`
2. in `js-analyze.js`:
1. add the link target at the top of the file, with the file path
2. for each string literal with `chrome://` or `resource://`
1. lazily load `url-map.json`, and lookup the file path for the URL
2. add the link source for the string literal, with the target file path
with the today's m-c, the `chrome-map.json` is 1,685,516 bytes, and the processed `url-map.json` becomes 1,977,829 bytes.
So, for each JS file with `chrome://` or `resource://` string literal, the `js-analyze.js` loads and parses ~2MB JSON file.  If this is too …
=> Bug 1895316 - Linkify string literal with chrome:// and resource:// in JS files

Makefile
missing `config_repo` in the copied config results in the following error while running `TRYPUSH_REV=... make trypush`
```
+ /vagrant/tools/target/release/scip-indexer /home/vagrant/trypush-index/config.json mozilla-central --subtree-root . --platform ios objdir-ios/rust.scip
thread 'main' panicked at src/file_format/config.rs:237:59:
called `Result::unwrap()` on an `Err` value: Error("missing field `config_repo`", line: 28, column: 1)
stack backtrace:
0: rust_begin_unwind
at /rustc/c987ad527540e8f1565f57c31204bde33f63df76/library/std/src/panicking.rs:652:5
1: core::panicking::panic_fmt
at /rustc/c987ad527540e8f1565f57c31204bde33f63df76/library/core/src/panicking.rs:72:14
2: core::result::unwrap_failed
at /rustc/c987ad527540e8f1565f57c31204bde33f63df76/library/core/src/result.rs:1654:5
3: …
```
=> Copy config_repo to trypush and nss temporary config

scripts/js-analyze.js, scripts/mkindex.sh, scripts/process-chrome-map.py
depends on https://bugzilla.mozilla.org/show_bug.cgi?id=1895989 and https://github.com/mozsearch/mozsearch-mozilla/pull/234
bug 1895989 will add `chrome-map.json` to the artifact of searchfox(idx) job, for each OS.
This combines all `chrome-map.json` info into single `url-map.json`, with using array of strings instead of string for each mapping, so that single URL can be mapped to multiple files if it's conditional on OS.
e.g. `resource://passwordmgr/passwordstorage.sys.mjs` maps to `toolkit/components/passwordmgr/storage-desktop.sys.mjs` on desktop and `toolkit/components/passwordmgr/storage-geckoview.sys.mjs` on android.
The `js-analyze.js` is modified to use the array and generate source/target for each.
=> Bug 1896165 - Use chrome-map.json files from searchfox jobs

docs/index-directory-contents.md
Depends on https://phabricator.services.mozilla.com/D210841 and https://github.com/mozsearch/mozsearch-mozilla/pull/236
=> Bug 1795177 - Add macosx64-aarch64 to document.

tools/Cargo.lock
As noted on the thread for the indexer failure, we failed to update because the new rustc nightly does not time 0.3.34.  So I did a `cargo update` and then did a fixup for tree-sitter-rust which had performed a divergent upgrade to 0.22.x which I manually downgraded to 0.20.9 to match everything else.
=> Build fix: `cargo update` run to get time 0.3.36 update to fix nightly build failure.

scripts/indexer-logs-analyze.sh
For https://github.com/mozsearch/mozsearch/pull/733 I wanted to get the run times from the server run since the server will generally be less performant than dev machines as currently provisioned and it didn't seem like there had been a dev channel run at the time so I presumed the times were from local runs only.
=> Update indexer-logs-analyze for the new HTML and CSS analyze scripts

scripts/html-analyze.sh, scripts/js-analyze.js, scripts/js-analyze.sh
JS shell has `os.file.redirect` which can redirect the `print`/`console.log` call to specified file.
https://searchfox.org/mozilla-central/rev/9508d23ab6de8b0734be2c95303515b08da1ce28/js/src/shell/OSObject.cpp#837-841
```cpp
JS_FN_HELP("redirect", osfile_redirectOutput, 1, 0,
"redirect([path-or-object])",
"  Redirect print() output to the named file.\n"
"   Return an opaque object representing the previous destination, which\n"
"   may be passed into redirect() later to restore the output."),
```
Also JS shell has `readline` which can read from stdin.
https://searchfox.org/mozilla-central/rev/9508d23ab6de8b0734be2c95303515b08da1ce28/js/src/shell/js.cpp#9266-9268
```cpp
JS_FN_HELP("readline", ReadLine, 0, 0,
"readline()",
"  Read a single line from stdin."),
```
This patch does the …
=> Perform batch processing in js-analyze.js.

tools/Cargo.toml, tools/src/css_analyzer.rs, tools/src/file_format/analysis.rs, tools/src/file_format/merger.rs, tools/src/file_format/mod.rs, tools/src/file_format/ontology_mapping.rs, tools/src/file_format/ontology_pointer_kind.rs, tools/src/lib.rs
* Make analysis structs and impl generic over string type (`StrT`), which can be `Ustr` or `String`
* Make `css_analyzer` use `String` variant of analysis types
* Move `OntologyPointerKind` into its own file, to avoid annotating `ontology_mapping.rs` much
* Remove unnecessary dependencies from `Cargo.toml`, `lib.rs`, and `mod.rs`
This reduces the size of `wasm_css_analyzer.wasm` from 106kB to 88kB.
=> Make analysis types generic over Ustr/String and use String variant from css_analyzer.

scripts/indexer-setup.py, scripts/ld-wrapper
for https://bugzilla.mozilla.org/show_bug.cgi?id=1899642
The issue here is already explained in 
https://github.com/mozsearch/mozsearch-mozilla/blob/5fdf3904e04c39ad6957f42aeb918d19d742939d/graphviz/build#L12-L15
where libtool passes `-load` and `...*libclang-index-plugin.so` to linker command.
This patch does:
* Add a wrapper command for ld, which filters these parameters out
graphviz config is going to use this.
=> Bug 1899642 - Add ld wrapper to mitigate libtool issue in graphviz

scripts/js-analyze.js, scripts/replace-aliases.py, tests/tests/checks/inputs/analysis/css/embed_css.html/url__json, tests/tests/checks/inputs/analysis/css/test.css/url__json, tests/tests/checks/inputs/analysis/urlmap/chrome1.mjs/no_stray_relpath__json, tests/tests/checks/inputs/analysis/urlmap/chrome1.mjs/url_use_with_relative__json, tests/tests/checks/inputs/analysis/urlmap/resource1.mjs/url_use_with_relative__json, tests/tests/checks/inputs/analysis/urlmap/root.js/no_stray_url__json, tests/tests/checks/inputs/analysis/urlmap/subdir/sub.mjs/url_use_with_relative_parent__json, tests/tests/checks/snapshots/analysis/css/embed_css.html/check_glob@url__json.snap, tests/tests/checks/snapshots/analysis/css/test.css/check_glob@url__json-2.snap, tests/tests/checks/snapshots/analysis/urlmap/chrome1.mjs/check_glob@no_stray_relpath__json.snap, tests/tests/checks/snapshots/analysis/urlmap/chrome1.mjs/check_glob@url_use_with_relative__json.snap, tests/tests/checks/snapshots/analysis/urlmap/resource1.mjs/check_glob@url_use_with_relative__json-2.snap, tests/tests/checks/snapshots/analysis/urlmap/root.js/check_glob@no_stray_url__json.snap, tests/tests/checks/snapshots/analysis/urlmap/root.js/check_glob@url_use_in_script__json.snap, tests/tests/checks/snapshots/analysis/urlmap/subdir/sub.mjs/check_glob@url_use_with_relative_parent__json.snap, tests/tests/checks/snapshots/search-files/check_glob@anchored_doublestar_html__json.snap, tests/tests/files/css/embed_css.html, tests/tests/files/css/test.css, tests/tests/files/urlmap/chrome1.mjs, tests/tests/files/urlmap/resource1.mjs, tests/tests/files/urlmap/root.js, tests/tests/files/urlmap/subdir/sub.mjs, tests/tests/metadata/test.chrome-map.json
for https://bugzilla.mozilla.org/show_bug.cgi?id=1895653
* Add support for dynamic `import()`
* Use "file " prefix instead of "type " prefix for URL in `js-analysis.js` (this is going to be rewritten by `replace-aliases.py` tho
* Make `replace-aliases.py` remove any unknown `URL_*` records, given the record is not going to be used by crossref, and it consumes unnecessary RAM
* Add relative path support, by:
* Make `js-analysis.js` generate a record with `sym: "RELPATH"` and `pretty` being the relative path
* Calculate the reverse map of `url-map.json`, that is, file path to urls , in replace-aliases.py
* Replace `RELPATH` records with corresponding `FILE_*` records, or remove it if there's no any file
I use `RELPATH` symbol instead of `RELPATH_*`, because the …
=> Bug 1895653 - Linkify relative path of import/export declaration

static/css/mozsearch.css, static/js/code-highlighter.js, static/js/context-menu.js, static/js/panel.js
for https://bugzilla.mozilla.org/show_bug.cgi?id=1900120
This does the following, behind the "Fancy Bar" setting (the "Alpha" gate):
* Add "Symbol" section inside the navigation bar, above the "Copy as Markdown" section [1]
* this section shows the currently-selected symbol, which is used by the "Symbol Link" [2]
* if no symbol is selected (no symbol inside selected line), this section shows "(no symbol clicked)" text
* this section has copy button, which copies the raw text of the symbol's qualified name (the text part of the current "Symbol Link")
* the selected symbol's namespace part (including class name etc) and the local name part are shown in separate line, in order to make sure the local name is visible
* the symbol section has fixed-width (240px), in order to avoid changing the …
=> Bug 1900120 - Add Symbol section with symbol selection mechanism, behind Fancy Bar setting.

scripts/mkindex.sh, scripts/output.sh, scripts/process-chrome-map.py, static/js/context-menu.js, tests/tests/checks/inputs/web/files/urlmap/links_in_comment__html, tests/tests/checks/snapshots/web/files/urlmap/check_glob@links_in_comment__html.snap, tests/tests/files/urlmap/root.cpp, tests/tests/metadata/test.chrome-map.json, tools/Cargo.toml, tools/src/bin/output-file.rs, tools/src/file_format/mod.rs, tools/src/file_format/url_map.rs, tools/src/lib.rs, tools/src/links.rs, tools/src/url_map_handler.rs
for https://bugzilla.mozilla.org/show_bug.cgi?id=1900823
* Fix the chrome-map handling (basically this reverts https://github.com/arai-a/mozsearch/commit/98654da28d200dd7dbf106c76d29602b3fc5033b .  the code was correct but the test data was wrong)
* Make the output step to generate a `FILE_` symbols span for `chrome://` and `resource://` URLs inside comments, without reflecting it to `SYM_INFO`
* Make the context menu handling to generate pseudo symbol info for unknown `FILE_` symbols
This linkifies URLs in `jar.mn` , and it discovered the chrome-map handling bug.
=> Bug 1900823 - Linkify resource:// and chrome:// URLs in textual occurrences

static/css/mozsearch.css
for https://bugzilla.mozilla.org/show_bug.cgi?id=1901146
This adds spacing (margin) before 2nd+ tables for field layout view.
=> Bug 1901146 - Add space between tables in field layout view for each class hierarchy

tests/tests/checks/inputs/fancy/format-symbol/field-layout/non-struct.cpp/field_layout__non_struct__json, tests/tests/checks/snapshots/fancy/format-symbol/field-layout/non-struct.cpp/check_glob@field_layout__non_struct__json.snap, tests/tests/files/field-layout/non-struct.cpp, tools/src/cmd_pipeline/cmd_format_symbols.rs
For https://bugzilla.mozilla.org/show_bug.cgi?id=1901279
* While traversing, filter out structured record that doesn't correspond to struct-ish data (https://clang.llvm.org/doxygen/namespaceclang.html#a9237bdb3cf715b9bff8bcb3172635548 suggests there can be some more than struct/class)
* Do not add a table if the table is empty (the table is non-empty even if the struct has no field, because the table has the class name row)
=> Bug 1901279 - Show only classes/structs in field layout view

config_defaults/ontology-mapping.toml, tests/tests/checks/inputs/fancy/format-symbol/field-layout/field-type.cpp/field_layout__field_type__json, tests/tests/checks/snapshots/fancy/format-symbol/field-layout/big_cpp.cpp/check_glob@field_layout__outercat__json.snap, tests/tests/checks/snapshots/fancy/format-symbol/field-layout/bitfields.cpp/check_glob@field_layout__bitfields__json.snap, tests/tests/checks/snapshots/fancy/format-symbol/field-layout/empty.cpp/check_glob@field_layout__empty__json.snap, tests/tests/checks/snapshots/fancy/format-symbol/field-layout/field-type.cpp/check_glob@field_layout__field_type__json.snap, tests/tests/checks/snapshots/fancy/format-symbol/field-layout/holes.cpp/check_glob@field_layout__holes__json.snap, tests/tests/checks/snapshots/fancy/format-symbol/field-layout/multiple_inheritance.cpp/check_glob@field_layout__multiple_inheritance__json.snap, tests/tests/checks/snapshots/fancy/format-symbol/field-layout/non-struct.cpp/check_glob@field_layout__non_struct__json.snap, tests/tests/checks/snapshots/fancy/format-symbol/field-layout/platform_specific_field.cpp/check_glob@field_layout__platform_specific_field_1__json.snap, tests/tests/checks/snapshots/fancy/format-symbol/field-layout/platform_specific_field.cpp/check_glob@field_layout__platform_specific_field_2__json.snap, tests/tests/checks/snapshots/fancy/format-symbol/field-layout/platform_specific_size.cpp/check_glob@field_layout__platform_specific_size__json.snap, tests/tests/checks/snapshots/fancy/format-symbol/field-layout/vtable.cpp/check_glob@field_layout__vtable__json.snap, tests/tests/checks/snapshots/web/query/execution/field-layout/check_glob@query__field_layout__outercat__json.snap, tests/tests/files/field-layout/field-type.cpp, tools/src/cmd_pipeline/cmd_format_symbols.rs, tools/src/cmd_pipeline/interface.rs, tools/templates/query_results/basic_markup_array.liquid, tools/templates/query_results/symbol_tree_table_node.liquid
for https://bugzilla.mozilla.org/show_bug.cgi?id=1900830
* Refactor the symbol tree table:
* Add `BasicMarkup` variants for text/heading with `data-symbols`
* Convert the field name cell into general `SymbolTreeTableCell`
* Make each field type into span with `data-symbols`, for the field type and `pointerInfo` types
* given we don't have tokenization for the pretty string, the entire pretty string is marked with `span` with `data-symbols`, for all types appears inside it
* Add more JS types to ontology mapping, to make them available in field layout table
Single type:
Wrapped type:
=> Add symbol info to field types in field layout table

clang-plugin/MozsearchIndexer.cpp
Imports the change from https://bugzilla.mozilla.org/show_bug.cgi?id=1902891
=> Bug 1902891 - Do not use written template args for canonical field type

infrastructure/web-server-run.sh
Initially we used a hard-coded ulimit of 24G based on observed values on config1 out of a combination of erring on the side of safety and because I worried the shell scripting would be a headache and likely to break.  But it turns out the arithmetic context offered by bash via `$(( $a + $b ))` is easy to use in a way I honestly did not expect.
This patch translates the original rationale for arriving at 24G to be done based on invocations of du.  This works as expected on config4 (where I ran an updated version of the script) as well as config1 (where I ran the shell scripts manually).
=> Bug 1904373 - pipeline-server ulimit should be aware of mmap data sizes

run-docker.sh
Now that the image is built as linux/amd64 running it without a platform argument emits a warning on aarch64 hosts. This silences the warning
=> Bug 1904474 - Explicitly specify platform when running image

tests/tests/checks/snapshots/crossref/crossref/xpctest_attributes.idl/check_glob@booleanProperty_getter__json.snap, tests/tests/checks/snapshots/crossref/crossref/xpctest_attributes.idl/check_glob@booleanProperty_setter__json.snap, tests/tests/checks/snapshots/crossref/crossref/xpctest_params.idl/check_glob@testOctet__json.snap, tests/tests/checks/snapshots/crossref/java/JavaLibrary.java/check_glob@links_to_java_library_constructor__json.snap, tests/tests/checks/snapshots/crossref/java/JavaLibrary.java/check_glob@multiple_implements__json.snap, tests/tests/checks/snapshots/crossref/java/JavaLibrary.java/check_glob@no_inverse_relationships__json.snap
I just did a full local reprovision which included purging all docker containers and images as part of trying to make sure our Cargo.lock is up-to-date, and I ended up with these test changes which I'm going to merge.
I'm not quite sure how the xpctest attributes weren't up-to-date, but I think the changes make sense and could involve the difficulty of dealing with/juggling large patch-stacks with our snapshot mechanism and our current lack of CI.  When I was landing my hobby stack, I ended up basically doing an `edit` during a rebase for every single patch and re-running all tests to make sure the snapshots were updated at the right point.  I think this would be more painful now that we have Java build-steps that are (almost?) always re-run.
I believe the change in java is because a new …
=> Test result changes experienced on full reprovision.

scripts/build-codesearch.py
If /tmp/dummy already exists, the script fails otherwise.  For hygiene / simplicity reasons I add a call to `shutil.rmtree` to clear out the dir before recreating it anew.  While we do include the tree name in all the paths we generate (except /tmp/livegrep.json), the invocations of `ln -s` will error if the link file already exist, so it is necessary to remove those.
Idiomatically, we use the `run` command to remove the tree at the end of the file, so that also could have made sense, but since we were using `os.mkdir` in the same location to make the directory, I went with using the relevant python command.
=> Bug 1904890 - Make build-codesearch.py resilient to previous failures.

router/router.py, scripts/nginx-setup.py
Now that these scripts are fully on python3 there's no need to use the migration shims from the `six` package
=> Bug 1904474 - Drop usage of six in favor of python3 native

scripts/build-codesearch.py
So I should have passed `ignore_errors=True` in the prior patch but I think, on balance, just doing the shell thing that most contributors will have awareness of is probably best after all.
=> Bug 1904890 - Whoops, shutil.rmtree complains, just use rm -rf.

tools/src/bin/scip-indexer.rs
I got an error like:
```
thread 'main' panicked at src/bin/scip-indexer.rs:1123:81:
called `Result::unwrap()` on an `Err` value: InvalidLocalSymbol("local izedMessage.")
```
I need to investigate the root cause (seems like bad scip data) but in the meantime it would be great if this didn't completely abort the indexer.
=> Bug 1905328 - Robustify against symbol parsing errors

scripts/nginx-setup.py, tests/tests/files/webtest/CopyAsMarkdown.cpp, tests/webtest/head.js, tests/webtest/test_CopyAsMarkdown.js, tests/webtest/test_FieldLayoutContextMenu.js, tests/webtest/test_SymbolSectionInPanel.js, tools/src/cmd_pipeline/cmd_webtest.rs
for https://bugzilla.mozilla.org/show_bug.cgi?id=1905491
* Use DEBUG type for logging for TestUtils internal and make it less appealing than other INFO
* Add no-cache header to webtest files
* Apply color to logging in web console [1], this helps debugging tests on browser
* Add tests for Copy as Markdown menu items and accel keys
* Add tests for Symbol section
[1] colored messages, compatible with both light and dark theme
=> Bug 1905491 - Add webtest for Symbol and Copy as Markdown in panel

Makefile, docs/newrepo.md, tests/tests/build, tests/tests/files/Cargo.toml, tests/tests/files/build.rs, tests/tests/files/simple.rs
Try run for config1.json with trees is up on asuth.searchfox.org :
- https://asuth.searchfox.org/mozsearch/source/
- https://asuth.searchfox.org/mozsearch-tests/source/
- https://asuth.searchfox.org/mozsearch-mozilla/source/
The commit to quiet the test repo warnings works locally but the try run still generated the warnings because it was checking out the current status of the master branch which did not include the fixes, of course.
=> Bug 1858453 - Index mozsearch and mozsearch-mozilla

clang-plugin/MozsearchIndexer.cpp, tests/tests/checks/snapshots/fancy/format-symbol/field-layout/field-type.cpp/check_glob@field_layout__field_type__json.snap, tests/tests/checks/snapshots/fancy/format-symbol/field-layout/field-type.cpp/check_glob@field_show_hide__name__json.snap
This is a first attempt at emitting structured information for a new type of C++ entity, enumerations.
It's currently causing the below difference in the output of an existing test (as well as a similar one in the same directory), which I haven't accepted yet because I'm not sure yet if everything in this change is ok.
The appearance of the new `"meta"` field is expected (that's the point of the patch), but the following are open questions in my mind:
1. Why is the value of the `"pretty"` key next to `"meta"` changing from `"T_field_layout::field_type::Enum1"` to `"field_layout::field_type::Enum1"`?
2. In terms of the contents of the structured record, the patch is currently only filling out the `"kind"`, because that's the only thing needed by the semantic highlighting code that I'm …
=> Emit structured info for EnumDecl

static/js/context-menu.js
for https://bugzilla.mozilla.org/show_bug.cgi?id=1909096
This does:
* fix the selector syntax to be standard compliant
=> Bug 1909096 - Fix selector for tree switcher

static/css/mozsearch.css
for https://bugzilla.mozilla.org/show_bug.cgi?id=1906580
Instead of applying wider padding for non-source-listing cases, add padding/margin for items inside it when necessary, so that the breadcrumbs is positioned in the same place across pages.
Spacing for the following are kept by adding extra padding/margin:
* directory listing table
* field layout table
Spacing for the top page and the settings page are reduced, but they should already have sufficient padding:
Spacing for other queries (call graph, use graph) are also reduced, but they have spacing in its own.
=> Bug 1906580 - Use consistent padding for .content box

static/js/context-menu.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1908197
This does:
* Add `role=group` for `ul` for each group in Tree Switcher  (Firefox, Thunderbird)
* Add `role=menuitem` for `a` for each item
* Add `role=none` for `li` for each item
=> Bug 1908197 - Add role for items inside tree switcher menu

static/js/context-menu.js, tests/webtest/test_ContextMenuKeys.js
for https://bugzilla.mozilla.org/show_bug.cgi?id=1908125
depends on https://github.com/mozsearch/mozsearch/pull/789
This does:
* Add role for context menu
* Move the keyboard navigation from `TreeSwitcherMenu` to `ContextMenuBase`
* Add keyboard navigation for context menu (up/down/pageup/pagedown/home/end/esc)
Compared to the tree switcher, the context menu focuses the menu itself when opened,
and on macOS, hitting down focuses the first item, and hitting up focuses the last item,
this patch follows the behavior.
=> Bug 1908125 - Add keyboard navigation to context menu

flake.lock, flake.nix
This simply updates the Nix Flake from LLVM 16 to LLVM 18 and updates the Flake inputs.
I'm probably still the only user of this.
=> Update Nix Flake

static/css/mozsearch.css, static/js/search.js
Addresses the issue mentioned in https://github.com/mozsearch/mozsearch/pull/790#issuecomment-2245693054
* Add `div.search-result-header` box for the number of result and warning message etc, with padding
* Add margin to the search result table
=> Bug 1906580 - followuo: Add the padding back to the search results.

static/js/settings.js
Fixes regression from #679 (67335ce18ff6a7e34e9203973a4009cf1e40ba25), reported at https://bugzilla.mozilla.org/show_bug.cgi?id=1910069
=> Bug 1910069 - Bump SETTINGS_VERSION to account for Settings.expansions

static/js/context-menu.js, tests/tests/files/field-layout/empty-subclass.cpp, tests/webtest/test_FieldLayoutContextMenu.js
for https://bugzilla.mozilla.org/show_bug.cgi?id=1906144
This does:
* Show "Show class layout of" menu item for class which has superclasses
* this is shown regardless of the number of superclass fields for simplicity
=> Bug 1906144 - Show class layout menu item for empty subclass.

static/js/blame.js
for https://bugzilla.mozilla.org/show_bug.cgi?id=1910230
This does:
* skip blame info popup handling when there's no blame info
* minor style fix
=> Bug 1910230 - Do not try to access blame data when no blame info is provided.

scripts/find-repo-files.py
for https://bugzilla.mozilla.org/show_bug.cgi?id=1910266
Most of the indexer scripts and server scripts don't actually expect non-ASCII (especially JS indexer), and each of them needs to be tweaked to properly support non-ASCII.
This makes the indexer simply ignore files with non-ASCII filename, to suppress warnings, as a first step.
=> Bug 1910266 - Do not index files with non-ASCII characters in filename

tests/tests/build, tests/tests/checks/snapshots/web/dirs/check_glob@generated_listing__html.snap, tests/webtest/test_FieldLayoutForGenerated.js, tools/src/abstract_server/local_index.rs, tools/src/cmd_pipeline/cmd_format_symbols.rs
for https://bugzilla.mozilla.org/show_bug.cgi?id=1910254
The issue is caused by accessing missing file while fetching the source lines, due to mis-handling `__GENERATED__/*` path.
This patch stack does:
* Ignore missing file in field layout table, so that similar case results in empty line cell, instead of error page
* Support fetching generated files
=> Bug 1910254 - Support generated files in fetch_raw_source

scripts/js-analyze.js, tests/tests/files/js/with space.js, tests/webtest/test_SpaceInFilename.js
for https://bugzilla.mozilla.org/show_bug.cgi?id=1910277
This does:
* in JS indexer, properly split the lines passed from `parallel` command, so that all characters after the first space becomes the filename.
=> Bug 1910277 - Support spaces in filename for JS files

scripts/idl-analyze.sh, scripts/load-vars.sh, scripts/webidl-analyze.py, tests/config.json, tests/tests/checks/snapshots/analysis/webidl/interface-mixin.webidl/check_glob@webidl_interface_mixin__json.snap, tests/tests/files/webidl/BindingTest.webidl, tests/tests/files/webidl/BindingTestMixed1.webidl, tests/tests/files/webidl/BindingTestMixed2.webidl, tests/tests/files/webidl/BindingTestMixin.webidl, tests/tests/files/webidl/bindings/include/BindingTestBinding.h, tests/tests/files/webidl/bindings/include/BindingTestMixed1Binding.h, tests/tests/files/webidl/bindings/include/BindingTestMixed2Binding.h, tests/tests/files/webidl/bindings/src/BindingTest.h, tests/tests/files/webidl/bindings/src/BindingTestBinding.cpp, tests/tests/files/webidl/bindings/src/BindingTestMixed1.h, tests/tests/files/webidl/bindings/src/BindingTestMixed1Binding.cpp, tests/tests/files/webidl/bindings/src/BindingTestMixed2.h, tests/tests/files/webidl/bindings/src/BindingTestMixed2Binding.cpp, tests/webtest-config.json, tests/webtest/test_WebIDLBindings.js
For https://bugzilla.mozilla.org/show_bug.cgi?id=1904320
This does:
* Add testcase for existing WebIDL bindings, with pseudo binding code
* Add testing-only config entry `webidl_binding_local_path` to override the webidl binding path, to simplify the automated tests
* Support indexing interface mixins, with associating to the binding code for the interfaces that include the mixin
=> Bug 1904320 - Support interface mixin

scripts/find-repo-files.py, scripts/html-analyze.sh, scripts/js-analyze.js, scripts/js-analyze.sh, tests/tests/files/js/with-UTF8-ファイル.js, tests/webtest/test_UTF8InFilename.js
for https://bugzilla.mozilla.org/show_bug.cgi?id=1910279
This does:
* Handle non-ASCII filenames in `js-analyze.js`:
* input: decode the raw bytecode sequence from `readline()`
* output: set `LC_TYPE` environment variable to make `std::wcsrtombs` called inside `os.file.redirect` work
* Put raw non-ASCII paths into `*-files` files
* things required escape/quote are re-enabled (they're skipped by [bug 1910279](https://bugzilla.mozilla.org/show_bug.cgi?id=1910279))
* paths with special characters are still skipped
=> Bug 1910279 - Properly handle non-ASCII filenames in JS indexer

infrastructure/aws/trigger_indexer.py, scripts/indexer-logs-analyze.sh
I will regenerate the lambda tarball for config4 and upload it, as I believe that's necessary for us to see this change actually take effect in production.  As noted in the bug, we could do more to make this something that's specified by the config file.  Although there's always a trade-off in fail-safes like this where the more complexity you add, the more possible it is to fail in a way that the fail-safe never gets put in place.
=> Update log analyzer script for replace-aliases.sh, extend indexer runtime limit to 12 hours from 10 hours

static/js/blame.js
The BlamePopup was living outside `<body>`, as pointed out in https://github.com/mozsearch/mozsearch/pull/679#issuecomment-2245545358 this caused surprising behaviour, like test in the BlamePopup not being selected on Ctrl+A.
=> Bug 1911062 - Move BlamePopup from `<html>` to `<body>`.

tests/tests/build, tests/tests/checks/snapshots/web/dirs/check_glob@root_listing__html.snap, tests/tests/files/templates6.cpp, tests/tests/files/templates6.h, tests/webtest/test_OverloadInTemplate.js, tools/src/format.rs
When populating SYM_INFO, only the first symbol of merged symbols was output to HTML. This led to missing “Go to definition” entries in some cases involving macros or templates.
For templates, see the new test files templates6.h/templates6.cpp and the corresponding webtest.
For macros this is especially visible in the atom_list.h use-case, except in our test repo because atom_list.h doesn't go through the merge-analyses step.
=> Bug 1911131 - Forward all relevant jumpref data to SYM_INFO.

scripts/replace-aliases.py, tests/tests/checks/inputs/analysis/cpp/URL_sym.cpp/URL_sym__json, tests/tests/checks/snapshots/analysis/cpp/URL_sym.cpp/check_glob@URL_sym__json.snap, tests/tests/files/cpp/URL_sym.cpp
for https://bugzilla.mozilla.org/show_bug.cgi?id=1911051
`replace-aliases.py` tries to replace records with `URL_*` symbols and `RELPATH` symbols,
but I forgot to actually test the symbol after a preliminary test to avoid JSON parse.
This patch does:
* Add the test for the symbol to actually filter out non-target
=> Bug 1911051 - Fix replace-aliases.py not to filter out all records with URL_ substring match

infrastructure/aws/index.sh, infrastructure/aws/mkscratch.sh, infrastructure/aws/rebuild-blame.sh, infrastructure/aws/shell-setup.sh, infrastructure/aws/trigger-provision.py, infrastructure/aws/trigger_common.py, infrastructure/common-provision-pre.sh
I think the basic situation is that the macro expansion magic is interacting badly with webkit in a way that causes the processes memory usage to bloat to really extreme levels.  This stack provides swap space, and the webkit indexing job had consumed about 190G of swap before I terminated the index.  The swapping was pretty bad, I think, to the extent that basically of the 16 cores, we only ended up with about 1 core's worth of progress moving forward.
The analysis files on disk did not seem to be large; only 222 MiB was written when I shut things down.
I'm landing this stack primarily because I think we do want all these changes[1] and because the IMDS change will break future indexing runs without the last patch in this stack (because the new AMIs got opted in to IMDSv2 with required …
=> Bug 1912078 - Failed attempts to make config5 / wubkat happy

infrastructure/aws/mkscratch.sh
for https://bugzilla.mozilla.org/show_bug.cgi?id=1912460
the `nth()` doesn't print empty string on out-of-range on version 1.6, which is used in the indexer instance,
but it prints the last item, which can be the first item, which is used by `INSTANCE_STORAGE_DEV`.
This patch adds quick workaround to avoid using the same device.
Ultimately, we should bump jq to 1.7+
=> Bug 1912460 - Support jq 1.6 behavior in device listing

static/js/search.js, tests/webtest/test_SearchSection.js
for https://bugzilla.mozilla.org/show_bug.cgi?id=1913921
This does:
* search for the "expando" buttons in the `table` node instead of `document`, given the table is not yet added to the document at the point
=> Bug 1913921 - Attach event listeners before search result table is added to the document

static/css/mozsearch.css
for https://bugzilla.mozilla.org/show_bug.cgi?id=1915563
This fixes the invalid syntax introduced by bug 1906146.
=> Bug 1915563 - Fix intro/settings page size syntax.

tools/src/abstract_server/local_index.rs, tools/src/abstract_server/remote_server.rs, tools/src/abstract_server/server_interface.rs, tools/src/cmd_pipeline/symbol_graph.rs
for https://bugzilla.mozilla.org/show_bug.cgi?id=1916972
This adds lifetime annotation to avoid the warnings introduced in rust nightly compiler.
=> Bug 1916972 - Fix lifetime annotations to avoid warnings

clang-plugin/MozsearchIndexer.cpp
Searchfox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1912078
=> Bug 1912078 - Avoid huge memory usage by setting clang-format ColumnLimit to 0.

config_defaults/ontology-mapping.toml, scripts/web-analyze/wasm-css-analyzer/Cargo.lock, tests/tests/checks/snapshots/crossref/java/check_glob@package__json.snap, tools/Cargo.lock, tools/Cargo.toml, tools/src/bin/crossref.rs, tools/src/bin/scip-indexer.rs, tools/src/file_format/ontology_mapping.rs, tools/src/tree_sitter_support/cst_tokenizer.rs
Note this also includes https://github.com/mozsearch/mozsearch/pull/816
The canon example is [the searchfox.org query of calls-to:'org::mozilla::fenix::utils::NotificationBaseKt::createBaseNotification' depth:10](https://searchfox.org/mozilla-central/query/default?q=calls-to%3A%27org%3A%3Amozilla%3A%3Afenix%3A%3Autils%3A%3ANotificationBaseKt%3A%3AcreateBaseNotification%27+depth%3A10) versus the [same thing with this patch applied on asuth.searchfox.org](https://asuth.searchfox.org/mozilla-central/query/default?q=calls-to%3A%27org%3A%3Amozilla%3A%3Afenix%3A%3Autils%3A%3ANotificationBaseKt%3A%3AcreateBaseNotification%27+depth%3A10) where we understand "androidx::work::Worker::doWork" as a runnable idiom.
Most of the work here (beyond the work in …
=> Understand some android runnable idioms by better understanding external SCIP symbols

tools/src/abstract_server/local_index.rs, tools/src/bin/crossref.rs, tools/src/bin/output-file.rs, tools/src/bin/scip-indexer.rs, tools/src/bin/web-server.rs, tools/src/file_format/config.rs, tools/src/file_format/url_map.rs, tools/src/format.rs, tools/src/links.rs, tools/src/url_map_handler.rs
for https://bugzilla.mozilla.org/show_bug.cgi?id=1920754
* instead of using global variable to keep the url map JSON file path, associate it to `Config` and pass it to `linkify_comment` function
* instead of `lazy_static`, use `OnceLock` to lazily construct the `URLMap` with passed config's url map JSON path
Some places are not passing the config, thus the URLs in comments are not linkified, but that's pre-existing.
=> Bug 1920754 - Stop using global variable and mutable static in url_map_handler.

static/css/mozsearch.css, static/js/context-menu.js, static/js/panel.js, tests/tests/checks/snapshots/web/query/execution/simple/big_cpp.cpp/check_glob@query__calls_to__takeDamage__svg.snap, tests/tests/checks/snapshots/web/query/execution/simple/lots_of_calls.cpp/check_glob@query__calls_between__four_left_one_right__svg.snap, tests/tests/checks/snapshots/web/query/execution/simple/lots_of_calls.cpp/check_glob@query__calls_between__four_one__svg.snap, tests/tests/checks/snapshots/web/query/execution/simple/lots_of_calls.cpp/check_glob@query__calls_to__four_left_and_right__svg.snap, tests/tests/checks/snapshots/web/query/execution/simple/runnables.cpp/check_glob@query__calls_to__common_shoe_related_method__json.snap, tools/src/cmd_pipeline/cmd_traverse.rs, tools/src/cmd_pipeline/symbol_graph.rs
A notable correctness fix is that the `ensure_edge_in_graph` method was using a lookup map to find already extant edges but never actually populating the lookup map.  I believe this may have not affected anything because calls-to/uses diagrams used the traversal suppression to only add the edge once, and calls-from diagrams used callees edges which were pre-aggregated during crossref.
=> Bug 1921635 - Add "Go to use of" for diagram edges.

clang-plugin/MozsearchIndexer.cpp, tests/tests/checks/inputs/analysis/cpp/templates7.cpp/def_InlineShouldHaveContextSym, tests/tests/checks/inputs/analysis/cpp/templates7.cpp/def_InlineTemplateShouldHaveContextSym, tests/tests/checks/inputs/analysis/cpp/templates7.cpp/def_OutOfLineShouldntHaveContextSym, tests/tests/checks/inputs/analysis/cpp/templates7.cpp/def_OutOfLineTemplateShouldntHaveContextSym, tests/tests/checks/snapshots/analysis/cpp/templates7.cpp/check_glob@def_InlineShouldHaveContextSym.snap, tests/tests/checks/snapshots/analysis/cpp/templates7.cpp/check_glob@def_InlineTemplateShouldHaveContextSym.snap, tests/tests/checks/snapshots/analysis/cpp/templates7.cpp/check_glob@def_OutOfLineShouldntHaveContextSym.snap, tests/tests/checks/snapshots/analysis/cpp/templates7.cpp/check_glob@def_OutOfLineTemplateShouldntHaveContextSym.snap, tests/tests/checks/snapshots/web/dirs/check_glob@root_listing__html.snap, tests/tests/files/templates7.cpp
Link to bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1833695
Without this, OutOfLineTemplateShouldntHaveContextSym had two definition target records that disagreed on the contextsym:
1. The first one was generated when traversing the declaration, because it forwards to the definition if out-of-line (see comment in TraverseFunctionDecl). We didn't reset CurDeclContext, so it looked as-if the definition appeared inside the declaration, leading to a bogus contextsym (pointing to the function itself).
2. The second one was generated later on when traversing the definition itself. This one had a correct contextsym (ie. none).
This introduces a ValueRollback helper to make sure we don't forget to rollback CurDeclContext afterwards. (inspired by QScopedValueRollback)
=> Bug 1833695: reset DeclContext stack when analysing out-of-line templated function

clang-plugin/MozsearchIndexer.cpp, tests/tests/checks/inputs/analysis/cpp/lambdas.cpp/Struct0UsedInLambda, tests/tests/checks/inputs/analysis/cpp/lambdas.cpp/Struct1UsedInLambda, tests/tests/checks/snapshots/analysis/cpp/lambdas.cpp/check_glob@Struct0UsedInLambda.snap, tests/tests/checks/snapshots/analysis/cpp/lambdas.cpp/check_glob@Struct1UsedInLambda.snap, tests/tests/checks/snapshots/web/dirs/check_glob@root_listing__html.snap, tests/tests/files/lambdas.cpp
Link to bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1856762
This reuses the AutoSetContext machinery initially implemented for constructors to visit the implicit code generated for lambdas too, giving us the data required to understand the template-dependent code in lambdas.
AutoSetContext is adapted to support AutoSetContext::Decl == nullptr because, contrary to CXXConstructorDecl, LambdaExprs aren't NamedDecls.
=> Bug 1856762 - Visit implicit code inside lambdas

clang-plugin/MozsearchIndexer.cpp, tests/tests/checks/inputs/analysis/cpp/lambdas.cpp/LambdaFields, tests/tests/checks/snapshots/analysis/cpp/lambdas.cpp/check_glob@LambdaFields.snap, tests/tests/checks/snapshots/web/dirs/check_glob@root_listing__html.snap, tests/tests/files/lambdas.cpp
Link to bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1922888
Bug 1856762 added support for traversing the implicit declarations created for lambdas. When traversing a lambda, a new context is pushed to the AutoSetContext stack to set the VisitImplicit flag. This context has Decl == nullptr because the lambda is not a NamedDecl.
I modified IndexConsumer::getContext(Decl *D) to support that case, but forgot to modify getContext(SourceLocation Loc) to support it too. In the added test case, the non-catch-all captures triggered a crash.
=> Bug 1922888 - Fix IndexConsumer::getContext(SourceLocation) when Ctxt->Decl is null.

infrastructure/docker-provision.sh, router/codesearch.py
for https://bugzilla.mozilla.org/show_bug.cgi?id=1923517 and https://bugzilla.mozilla.org/show_bug.cgi?id=1923516
This does:
* delete the default "ubuntu" user while setting up the docker image, to avoid the UID conflict with the host user
* filter out the protobuf's warning, specific to the current version, so that the warning with newer versions will be reported even if we forget to remove the filter
=> Bug 1923517 - Filter out the warning for protobuf.

.gitignore, clang-plugin/Makefile
for https://bugzilla.mozilla.org/show_bug.cgi?id=1912189
This makes the clang-plugin Makefile verify the clang version for the previous build (written into `clang-version.cache` file, which is not version-controlled), and rebuild from scratch if the version mismatch is detected.
I was about to add the `clang-version.cache` file to the dependency of each rule, but that results in putting the file in the compile/link command lines, so I made it to just perform `make clean` to perform full rebuild.
=> Bug 1912189 - Detect clang and clang-plugin version mismatch

Makefile, clang-plugin/Makefile
for the failure in https://github.com/mozsearch/mozsearch/pull/825
This makes the commands used during testing in docker perform the version check, but the command used by server don't
=> Bug 1912189 - Part 2: Use the version check only in docker

infrastructure/aws/indexer-provision.sh, infrastructure/aws/web-server-provision.sh
In some cases the EBS root volume may not be the previously hardcoded `/dev/nvme0n1` so we should extract it via jq.  The idiom we've been using in cases like this is to run the command that gives us a JSON blob once into an INFO var and then use separate jq invocations that use `<<< "$FOO_INFO"` to then pick the relevant data out of there rather than issue multiple commands which might change dynamically.  I've done that here.
This successfully ran on both provisioning jobs I just kicked off, although the hardcoded values would have worked too, but I did consult the logs and we are using the new logic.
=> Bug 1924227 - Extract root block device from nvme list rather than hardcoding it

static/js/blame.js, static/js/search.js, tests/tests/files/js/with space.js, tests/webtest/head.js, tests/webtest/test_SpaceInFilename.js, tools/src/bin/output-file.rs, tools/src/bin/web-server.rs, tools/src/format.rs, tools/src/lib.rs, tools/src/output.rs, tools/src/url_encode_path.rs
For https://bugzilla.mozilla.org/show_bug.cgi?id=1910314
This does:
* URL-encode the `href` attribute when the path contains the files in the target repository
* Decode URL-encoding on the server, for dynamically-generated pages
example:
https://arai.searchfox.org/mozilla-central/source/testing/web-platform/tests/tools/wave/tests/WAVE%20Local.postman_environment.json
Links in the blame popup, the navigation bar, and the breadcrumbs are now URL-encoded, and also the
annotated diff link target shows the correct file (it has been "File not found" error page)
=> Bug 1910314 - URL-encode link path, and support URL-encoded path in the server

tests/searchfox/setup
for https://bugzilla.mozilla.org/show_bug.cgi?id=1924329
This adds a check to the setup process of the searchfox repo (used both by build-searchfox-repo and webtest) to check
uncommitted changes, and show error if any, to avoid errors during the output process caused by the inconsistency between the git history and the working tree.
=> Bug 1924329 - Show error when uncommitted changes found while building the searchfox repo

scripts/build-codesearch.py, scripts/lib.py
for https://bugzilla.mozilla.org/show_bug.cgi?id=1925207
This adds a filter for the `run_showing_output` function, and pass a filter to convert "WARN:" to "INFO:" for the filesize warning.
=> Bug 1925207 - Convert the livegrep warning for the file size to INFO

scripts/find-repo-files.py, scripts/load-vars.sh, scripts/mkindex.sh, scripts/staticprefs-analyze.py, scripts/staticprefs-analyze.sh, static/js/context-menu.js, tests/config.json, tests/tests/checks/inputs/analysis/staticprefs/staticprefs__json, tests/tests/checks/snapshots/analysis/staticprefs/check_glob@staticprefs__json.snap, tests/tests/checks/snapshots/web/dirs/check_glob@root_listing__html.snap, tests/tests/files/staticprefs/StaticPrefList.yaml, tests/tests/files/staticprefs/StaticPrefsConsumer.cpp, tests/tests/files/staticprefs/bindings/StaticPrefList_test.h, tests/tests/files/staticprefs/bindings/StaticPrefList_test2.h, tests/webtest-config.json, tools/src/describe.rs, tools/src/file_format/analysis.rs, tools/src/format.rs, tools/src/languages.rs, tools/src/tokenize.rs
https://bugzilla.mozilla.org/show_bug.cgi?id=1699048
This does:
* Index each item in `StaticPrefList.yaml`, with `PREFS_{id}` symbol
* Create structured record for the `StaticPrefList.yaml` items, adding the C++ binding to the getter binding slot.
* Support tokenizing `StaticPrefList.yaml`, with treating the pref name as identifier, supporting comments and strings
Example in `StaticPrefList.yaml`:
https://arai.searchfox.org/mozilla-central/source/modules/libpref/init/StaticPrefList.yaml#213
Example in the consumer of the binding:
https://arai.searchfox.org/mozilla-central/source/dom/base/FocusModel.h#36
=> Bug 1699048 - Index StaticPrefs.

clang-plugin/MozsearchIndexer.cpp, tests/tests/checks/inputs/crossref/crossref/big_cpp.cpp/thing_mHP__json, tests/tests/checks/snapshots/crossref/crossref/big_cpp.cpp/check_glob@stackartholder__json.snap, tests/tests/checks/snapshots/crossref/crossref/big_cpp.cpp/check_glob@thing__json.snap, tests/tests/checks/snapshots/crossref/crossref/big_cpp.cpp/check_glob@thing_mHP__json.snap, tests/tests/checks/snapshots/crossref/expand/big_cpp.cpp/check_glob@outercat__json.snap, tests/tests/checks/snapshots/crossref/merge/check_glob@merge__big_cpp.snap
(see specific commit messages; commit 1 adds a check that captures our currently wrong logic and commit 2 then lets us see the effects of the fix.)
=> Bug 1931631- C++ indexer should treat constructor member initializer list field uses as having a contextsym of the constructor

clang-plugin/MozsearchIndexer.cpp, tests/tests/checks/inputs/analysis/cpp/bug1781178.cpp/Foo_E, tests/tests/checks/snapshots/analysis/cpp/bug1781178.cpp/check_glob@Foo_E.snap, tests/tests/checks/snapshots/analysis/cpp/bug1781178.cpp/check_glob@Foo_E_Waldo.snap, tests/tests/checks/snapshots/web/dirs/check_glob@root_listing__html.snap, tests/tests/files/bug1781178.cpp
Bugzilla URL: https://bugzilla.mozilla.org/show_bug.cgi?id=1835692
This adds DependentScopeDeclRefExpr locations as well as their dependent nested qualifiers to the DependentLocations set in GatherDependent mode.
=> Bug 1835692 - Mark DependentScopeDeclRefExpr locations to be visited in instantiations.

clang-plugin/MozsearchIndexer.cpp, tests/tests/checks/inputs/analysis/cpp/bug1781178.cpp/WithOverloads_Overloaded, tests/tests/checks/snapshots/analysis/cpp/bug1781178.cpp/check_glob@WithOverloads_Overloaded.snap, tests/tests/checks/snapshots/web/dirs/check_glob@root_listing__html.snap, tests/tests/files/bug1781178.cpp
Bugzilla URL: https://bugzilla.mozilla.org/show_bug.cgi?id=1833555
Now that the context menu allows for differentiating between heuristic and concrete template instantiations, mark OverloadExpr location to be visited in AnalyzeDependent mode to have concrete results.
In the added WithOverloads::Overloaded test case, the float and bool overloads are only found heuristically (and are thus marked with cppTemplateHeuristic) while the int overload is also found by visiting concrete template instantiations.
=> Bug 1833555 - Mark OverloadExpr locations to be visited in instantiations.

clang-plugin/MozsearchIndexer.cpp, tests/tests/checks/inputs/analysis/cpp/template_specialization.cpp/some_function_called_in_partial_specialization, tests/tests/checks/snapshots/analysis/cpp/ForwardingTemplates.cpp/check_glob@TypeDependentNewInMethodReportedAtCallSite.snap, tests/tests/checks/snapshots/analysis/cpp/ForwardingTemplates.cpp/check_glob@TypeDependentNewInTemplateReportedAtCallSite.snap, tests/tests/checks/snapshots/analysis/cpp/ForwardingTemplates.cpp/check_glob@TypeIndependentNewInTemplateReportedInTemplate.snap, tests/tests/checks/snapshots/analysis/cpp/template_specialization.cpp/check_glob@some_function_called_in_partial_specialization.snap, tests/tests/checks/snapshots/web/dirs/check_glob@root_listing__html.snap, tests/tests/files/ForwardingTemplates.cpp, tests/tests/files/template_specialization.cpp
Bugzilla URL: https://bugzilla.mozilla.org/show_bug.cgi?id=1933325
This adds the missing bits to be able to get std::vector::emplace_back<T> appear as constructor calls for T.
=> Bug 1933325 - Link calls to emplace-like functions to the constructors they invoke.

static/js/context-menu.js
Bugzilla URL: https://bugzilla.mozilla.org/show_bug.cgi?id=1933960
When implementing bug 1833552 I assumed we would always have the data-confidences attribute next to the data-symbols attribute. This isn't the case for diagrams at the moment.
When data-confidences is missing, assume everything is concrete.
=> Bug 1933960 - Fallback to concrete confidence when data-confidences is missing.

scripts/js-analyze.js
for https://bugzilla.mozilla.org/show_bug.cgi?id=1934174
=> Bug 1934174 - Ignore devtools test file that can contain experimental syntax.

static/js/panel.js, tests/searchfox-config.json, tools/src/bin/output-file.rs, tools/src/format.rs, tools/src/output.rs
Bugzilla URL: https://bugzilla.mozilla.org/show_bug.cgi?id=1934697
generate_commit_info in format.rs already built link to GitHub for a specific commit.
This re-uses the same data source to build URLs to the GitHub log and GitHub raw content for the navigation pane.
The Raw link is replaced with the GitHub link when available _instead_ of the Mercurial link.
The Mercurial “Log” link is renamed to “Mercurial Log”.
A “Git Log” link is addded to point to GitHub when available.
=> Bug 1934697 - Replace Raw and Log links with GitHub links.

scripts/mkindex.sh, scripts/output.sh, tests/tests/checks/inputs/web/docs/docs_md__html, tests/tests/checks/inputs/web/docs/docs_rst__html, tests/tests/checks/snapshots/web/dirs/check_glob@root_listing__html.snap, tests/tests/checks/snapshots/web/docs/check_glob@docs_md__html.snap, tests/tests/checks/snapshots/web/docs/check_glob@docs_rst__html.snap, tests/tests/files/docs/md_test/index.md, tests/tests/files/docs/rst_test/index.rst, tests/tests/metadata/doc-trees.json, tests/tests/setup, tools/src/abstract_server/local_index.rs, tools/src/bin/crossref.rs, tools/src/bin/output-file.rs, tools/src/bin/scip-indexer.rs, tools/src/bin/web-server.rs, tools/src/doc_trees_handler.rs, tools/src/file_format/config.rs, tools/src/file_format/doc_trees.rs, tools/src/file_format/mod.rs, tools/src/lib.rs
for https://bugzilla.mozilla.org/show_bug.cgi?id=1458882
This is WIP to add "Source Docs" link for `.rst` and `.md` files, next to the current "Rendered view" link.
This expects the `source-test-doc-generate` jobs's `trees.json` artifact is fetched as `doc-trees.json` by the config's setup script,
and the download part needs to be addressed in separate patch.
=> Bug 1458882 - Add link to Firefox Source Docs.

clang-plugin/MozsearchIndexer.cpp, tests/tests/checks/snapshots/analysis/cpp/bug1781178.cpp/check_glob@Foo_E.snap, tests/tests/checks/snapshots/analysis/cpp/bug1781178.cpp/check_glob@Foo_E_Waldo.snap, tests/tests/checks/snapshots/analysis/cpp/bug1781178.cpp/check_glob@Foo_Project.snap, tests/tests/checks/snapshots/analysis/cpp/bug1781178.cpp/check_glob@Point_IsThereOne.snap, tests/tests/checks/snapshots/analysis/cpp/bug1781178.cpp/check_glob@WithOverloads_Overloaded.snap, tests/tests/checks/snapshots/analysis/cpp/bug1781178.cpp/check_glob@internal_Read.snap, tests/tests/checks/snapshots/web/dirs/check_glob@root_listing__html.snap, tests/tests/files/bug1781178.cpp
Bugzilla URL: https://bugzilla.mozilla.org/show_bug.cgi?id=1833548
This implements the first strategy proposed by Botond to filter unresolved overload sets: by arity.
We don't have easy access to the CallExpr from OverloadExpr, so we add tracking for that in TraverseCallExpr.
=> Bug 1833548 - Filter candidate overloads in OverloadExpr by call arity.

infrastructure/aws/web-server-provision.sh, infrastructure/indexer-provision.sh
The primary intent here is to boost the size of the web-server AMI to 16G to address running out of disk space during the self-update of the web-server at the start of its spin-up.
However, when running `./build-docker.sh` locally initially to validate that the provisioning process was likely to complete on the server, I encountered a provisioning failure during the installation of `mise` which is the tool we use to create a sort-of `venv` for node.  mise seems to be very much under development at this time and we definitely don't need any of the new enhancements, so I picked the version that was released on the last successful provisioning run of 2024-Oct-11.
As added to the comment, I'm not sure we really need to be using mise. I believe my original rationale was that nvm was deprecated …
=> Bug 1937445 - increase web-server AMI to 16G, latch mise version

.github/workflows/test.yml, infrastructure/common-provision-pre.sh, infrastructure/indexer-provision.sh, infrastructure/indexer-update.sh, infrastructure/web-server-provision.sh, infrastructure/web-server-update.sh, tests/tests/build
Bugzilla URL: https://bugzilla.mozilla.org/show_bug.cgi?id=1935484
This implements a simple GitHub Actions workflow for pull requests and pushes to master. It runs the existing provisioning scripts then runs the equivalent of `make build-test-repo` and `make webtest`.
It takes ±50 minutes to run, see a successful run here: https://github.com/nicolas-guichard/mozsearch/actions/runs/12690265272.
I had to:
- reduce the output size of the provisioning scripts, see all the “space savings” commits
- change css-analyze a bit to avoid leaking the index location in a symbol
- make sure the provisioning scripts clone the repo and branch that is being tested and not the master branch of https://github.com/mozsearch/mozsearch
The last point that bothers me is that the graphviz-dependent tests have …
=> Bug 1935484 - GitHub Actions CI

infrastructure/common-provision-pre.sh, scripts/find-objdir-files.sh, tests/tests/checks/snapshots/analysis/rust/simple.rs/check_glob@simple_Loader_new__html.snap, tests/tests/checks/snapshots/analysis/rust/simple.rs/check_glob@simple_Loader_new__json.snap, tests/tests/checks/snapshots/analysis/rust/test_rust_dependency/check_glob@MyType__html.snap, tests/tests/checks/snapshots/analysis/rust/test_rust_dependency/check_glob@MyType__json.snap, tests/tests/checks/snapshots/jumpref/jumpref/simple.rs/check_glob@loader__needs_hard_reload__lookup__json.snap, tests/tests/checks/snapshots/web/dirs/check_glob@generated_listing__html.snap, tests/tests/checks/snapshots/web/files/contextual-keyword/check_glob@contextual-keyword_rs__html.snap
This is for https://bugzilla.mozilla.org/show_bug.cgi?id=1943521 and https://bugzilla.mozilla.org/show_bug.cgi?id=1942757
This patch stack does:
* Update the test snapshot to reflect the new rust SCIP symbol syntax  (This is a part of the stack because otherwise the test fails on the latest rust nightly)
* Stop generating the C++ `.o` files in the objdir in the test repo, so that those files are not shown in the output
* Use the list of files in objdir, for the files reflected in __GENERATED__ files.  The newly added files are listed in the bug 1942757 comment 6
Available in https://arai.searchfox.org/
=> Bug 1942757 - Use the actual list of files in the objdir for indexing

infrastructure/aws/trigger_common.py
In 54490508, I updated the indexer's update.sh arguments to match web-server's update.sh, but missed the call in trigger_common.py.
=> Update update.sh call in trigger_common.py

.github/workflows/test.yml, infrastructure/common-provision-pre.sh, infrastructure/indexer-provision.sh, infrastructure/web-server-provision.sh
GitHub merge repos are not available as an actual branch and can't be directly cloned with `git clone -b ... --depth=1`. Instead, perform the manual steps of creating the repo, adding the remote, fetching and switching.
=> CI: Fix cloning repo from pull request

run-docker.sh
Bugzilla URL: https://bugzilla.mozilla.org/show_bug.cgi?id=1943509
This reverts commit 38cd611337adc77be3e6fe1340f8067ddfbade38.
While this worked with Podman, it failed with Docker.
=> Bug 1943509 - Revert "Specify Docker image host to be localhost"

infrastructure/common-provision-pre.sh
Bugzilla URL: https://bugzilla.mozilla.org/show_bug.cgi?id=1944279
The GitHub Actions runner already has rustup and `$HOME/.cargo`, but we still want to upgrade to the nightly channel.
=> Bug 1944279 - Unconditionally upgrade Rust to Nightly.

static/css/mozsearch.css, tools/src/output.rs
for https://bugzilla.mozilla.org/show_bug.cgi?id=1627778
This does:
* Make the SVG preview not float, so that it's displayed before the source, and it doesn't break the layout of the source
* Add more background options (explicit light and dark), given it now has more horizontal space in the control part, and the default background depends on the current theme (light/dark)
available in https://arai.searchfox.org/mozilla-central/source/browser/branding/aurora/content/about-logo.svg
This doesn't have testcase because the preview is available only with hg repository.
=> Bug 1627778 - Do not float the SVG preview.

tools/src/bin/pipeline-server.rs
I verified this by inspection, specifically looking at the response headers of a diagram via devtools locally.  Our automated test infra right now doesn't quite have the capability to add a header check like this.  It's definitely possible to add but it's also very unlikely that we would regress this specific endpoint again; the likely problem would be adding a new endpoint and most test infra we would add would probably not automatically cover that case.
=> Bug 1947618 - pipeline-server.rs should serve Vary header

scripts/js-analyze.js
for https://bugzilla.mozilla.org/show_bug.cgi?id=1948451
This adds one more pattern for the error message around import assertions.
=> Bug 1948451 - Ignore more import assertions errors.

clang-plugin/MozsearchIndexer.cpp
This is asuth propagating :glandium's changes from https://phabricator.services.mozilla.com/D234132
I have set the authorship to the commit author from that patch to accurately reflect authorship.
=> Bug 1941480 - Adjust mozsearch plugin code to recent clang trunk API changes. r=asuth

infrastructure/common-provision-pre.sh
For https://bugzilla.mozilla.org/show_bug.cgi?id=1959328
* Bump the git-cinnabar pinning version to 0.7.2
* Let the script fetch and update to the new revision if necessary
My current understanding is that, after this script is merged, we run the provisioning command, for indexer and web-server (so, run 2 commands), and that solves the warning.  Is it correct?
https://github.com/mozsearch/mozsearch/blob/master/docs/aws.md#provisioning-and-cloud-init
=> Bug 1959328 - Bump git-cinnabar version.

infrastructure/indexer-provision.sh, infrastructure/web-server-provision.sh
I'm also speculatively trying to leverage the ability to perform a shallow checkout of submodules as well to help the disk space usage for the CI runners.  It sounds like there might have been problems in very old verisons of git if the revision wasn't the branch head but that it's no longer a problem.  We also do try and stick to the tip of the branches, so that also should moot things.
=> Bug 1959582 - Correct mozsearch-mozilla specific revision checkout for web-server

infrastructure/aws/warning-suppression.patterns
I tested this against the most recent config1 indexer run using `send-warning-email.py`'s test mechanism for when "test" is specified as the email address to use.  Pre-change, I see what got sent, post-change I see no warnings.
=> Bug 1959722 - Ignore warnings about redirecting to hg-edge.mozilla.org

infrastructure/common-provision-pre.sh
On GitHub CI, this leads to updating containernetworking-plugins, which would then conflict with node-tap for the file /usr/bin/tap.
=> Remove --allow-change-held-packages from apt dist-upgrade

tests/tests/checks/inputs/analysis/java/InlineObject.kt/method__json, tests/tests/checks/inputs/analysis/java/InlineObject.kt/method_with_return_type__json, tests/tests/checks/snapshots/analysis/java/InlineObject.kt/check_glob@method__json.snap, tests/tests/checks/snapshots/analysis/java/InlineObject.kt/check_glob@method_with_return_type__json.snap, tests/tests/checks/snapshots/web/dirs/check_glob@root_listing__html.snap, tests/tests/files/build.gradle.kts
Bugzilla URL: https://bugzilla.mozilla.org/show_bug.cgi?id=1938622
This updates the test gradle project to use Kotlin 2.1.20 and our forked semanticdb-kotlinc.
Like my patch currently on review on Phabricator it's using JitPack for the time being, until we publish the package to Maven Central or maven.mozilla.org.
=> Bug 1938622 - Update test gradle project to Kotlin 2.1.20.

infrastructure/aws/attach-index-volume.py
I'll see what our actual usage is after a successful run, but the rough math based on current usage (~241G excluding nginx-cache) and the size of mozilla-central on config1 (~65G) plus our allocation of 20G for nginx-cache means we expect to hit at least 326G, so ~74G spare is advisable.  (Also, there's the whole GB/GiB units issue.)
=> Bug 1970807 - Bump release2 EBS size from 300G to 400G.

infrastructure/aws/trigger_common.py
This is motivated by config2 hitting the limit of the 300G SSD for m5d.2xlarge. The choice of m6id is being made because it seems to both be faster and gives us a larger 474G SSD which immediately solves our sizing problem.  Also nice is that m6id.4xlarge will have a 950G SSD which means that we won't have to do any clever RAID stuff if we want even more local space than that.
Note that I will need to re-provision the lambda tarballs after this and I will do that.
=> Bug 1970807 - Update from m5d to m6id instances for indexer.

infrastructure/indexer-provision.sh, infrastructure/indexer-update.sh, infrastructure/web-server-run.sh, infrastructure/web-server-update.sh, scripts/crossref.sh, scripts/css-analyze.sh, scripts/ipdl-analyze.sh, scripts/output.sh, scripts/rust-analyze.sh, scripts/scip-analyze.sh, scripts/webtest.sh, tests/searchfox/setup, tests/tests/build
This installs Mozsearch tools to .cargo/bin and updates the scripts to expect the tools to be in `$PATH`.
The mercurial `tip` currently points at `tags-unified` instead of `default`, which failed the previous GitHub Actions run [here](https://github.com/nicolas-guichard/mozsearch/actions/runs/16626148101/job/47043005611#step:4:2799).
Also requires https://github.com/mozsearch/mozsearch-mozilla/pull/281.
This is currently deployed on kdab.searchfox.org with the Graphviz index.
=> Use mozsearch tools from PATH

.github/workflows/test.yml, infrastructure/Dockerfile, infrastructure/indexer-provision.sh, scripts/html-analyze.sh, scripts/indexer-setup.py, scripts/js-analyze.js, scripts/js-analyze.sh, scripts/mkindex.sh
This is another step to be able to point the scripts at prebuilt/prepackaged binaries.
EDIT: forgot to mention this passed a test on kdab.searchfox.org, using the Graphviz tree as usual. It has some html and xml files so html-files and js-files are non-empty and html-analyze.sh and js-analyze.sh actually call js-analyze.js.
=> Get clang plugin and wasm analyzer paths from env

tests/tests/build
On GitHub Actions, Gradle is already installed and we don't need the wrapper.
With Nix, Gradle will be wrapped with a MITM proxy to package and lock dependencies.
=> Use gradle from PATH if available

scripts/webidl-analyze.py, tools/src/file_format/config.rs
For https://bugzilla.mozilla.org/show_bug.cgi?id=1986051
This does:
* Let the webidl analysis ignore known possibly-non-existent files
There's corresponding change in config repo that adds the renamed file to non-esr branches.
This can be removed once all non-esr branches receive the [bug 1919582](https://bugzilla.mozilla.org/show_bug.cgi?id=1919582) changes.
I'll post update when the test run finishes.
This might require some more fix in the other consumer of the file list.
=> Bug 1986051 - Ignore possibly non-existent webidl files.

scripts/js-analyze.js
For https://bugzilla.mozilla.org/show_bug.cgi?id=1987330
This does:
* Add files which uses import declarations for CSS modules to the ignore list
=> Bug 1987330 - Ignore CSS-modules-related warnings.

scripts/nginx-setup.py, tools/src/bin/web-server.rs
In bug 1890435 I'd punted on this mapping early on in the process assuming we'd be burning comparatively costly and limited Elastic Load Balancer rule resources, but we ended up just having all mozilla-central links sent to the firefox-main tree and having nginx then rewrite the m-c links to f-m links so /rev/ could become /oldrev/ and unambiguously be clear about which type of rev we're dealing with.  This means there's only the additional nginx rule and the marginal increase in web-server logic, which is mainly down to copy-and-paste.  (I opted to "repeat yourself" in the interest of clarity.)
When doing the update I noticed that we didn't have path length guards on hgrev and oldrev to match rev, so I added those.  This changes what would have been a 500 because of a (caught) panic to a …
=> Bug 1989736 - Add an /oldcommit/ endpoint for old m-c /commit/ links

infrastructure/aws/trigger_common.py, scripts/nginx-setup.py, tools/src/bin/output-file.rs, tools/src/file_format/config.rs, tools/src/format.rs
This is up on https://asuth.searchfox.org/firefox-main/source/ (not that the changes are particularly complicated, but the test repo can't replicate the situation we have for firefox-main and there are changes to output-file so a fresh indexing was required).
More detail in the specific commits, but this basically is doing what https://bugzilla.mozilla.org/show_bug.cgi?id=1990128 proposes in terms of using git instead of hg for raw and doing it directly via the raw.githubusercontent.com domain plus two slipstream fixes:
- allow trigger_indexer to specify a config revision to use that differs from the revision specified for the mozsearch repo, details in comments and commit message
- nginx fix because "localhost" in docker for us can end up pointing at our IPv6 loopback which we don't bind …
=> Bug 1990128 - Various changes to use git instead of hg and use git branch names when available
